In [22]:
############################################
## ユーザーが変更すべきハイパーパラメータ
############################################

## 1) ベースパス（outlier の直下まで）
base_path <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"

## 2) 解析対象の目的変数と、そのモデル名・dataset_tag の対応
target_config <- list(
  PCEmax = list(model_name = "SVM_Radial", folder_name = "PCE", dataset_tag = "m_all_OH"),
  Jsc    = list(model_name = "gprLinear",  folder_name = "Jsc", dataset_tag = "m_all_OH"),
  Voc    = list(model_name = "RF",         folder_name = "Voc", dataset_tag = "m_base_FP"),
  FF     = list(model_name = "kNN",        folder_name = "FF",  dataset_tag = "m_all_FP")
)

## 3) bundle フォルダ名
bundle_folder_name <- "bundle_for_thesis_20260119"

## 4) 誤差ファイル内の列名
col_true   <- "Observed"   # 実測値
col_pred   <- "Predicted"  # 予測値
col_abserr <- "AbsError"   # 絶対誤差
col_id     <- "SampleID"   # サンプルID

## 5) 外れ値抽出モード
use_top_k_mode   <- FALSE   # top_k は使わない
use_abs_thr_mode <- TRUE    # 固定しきい値を使う

## 6) top_k（保険として残しておくが使わない前提）
top_k <- 10

## 7) 目的変数ごとの固定 AbsError 閾値（必要に応じて調整）
abs_error_thr_list <- list(
  PCEmax = 3.5,
  Jsc    = 5.0,
  Voc    = 0.15,
  FF     = 0.20
)

## 共通の abs_error_thr（使わないなら NA のままでOK）
abs_error_thr <- NA_real_

## 8) 出力フォルダ名プレフィックス
output_prefix <- "outlier_results"

## 9) 総括フォルダ名
summary_folder_name <- "outlier_summary_fixedThr_20260119"


############################################
## ここから下は通常変更不要
############################################

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(readr)
})

## 1目的変数を処理する関数
process_one_target <- function(target) {

  cfg <- target_config[[target]]
  if (is.null(cfg)) {
    cat("  [WARN] target_config に設定がありません: ", target, "\n")
    return(invisible(NULL))
  }

  model_name   <- cfg$model_name
  dataset_tag  <- cfg$dataset_tag
  folder_name  <- cfg$folder_name   # PCE, Jsc, Voc, FF

  cat("============================================\n")
  cat("Target:", target, "\n")
  cat(" model_name  :", model_name,  "\n")
  cat(" dataset_tag :", dataset_tag, "\n")
  cat(" folder_name :", folder_name, "\n")
  cat("============================================\n")

  ## フォルダとファイルパス生成
  bundle_path <- file.path(base_path, bundle_folder_name, folder_name)

  ## ファイル名のベース
  base_file_stub <- paste0(dataset_tag, "_rebuilt_", target)

  file_oof_err  <- file.path(bundle_path,
                             paste0(base_file_stub, "_pred_OOF_withError.csv"))
  file_oof_feat <- file.path(bundle_path,
                             paste0(base_file_stub, "_pred_OOF_withError_andFeatures.csv"))

  ## 出力フォルダ（目的変数ごと）
  out_dir <- file.path(base_path, paste0(output_prefix, "_", target))
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  cat("Input (OOF+Error):     ", file_oof_err,  "\n")
  cat("Input (WithFeatures):  ", file_oof_feat, "\n")
  cat("Output dir:            ", out_dir,       "\n\n")

  if (!file.exists(file_oof_err)) {
    cat("  [WARN] OOF+Error ファイルが見つかりません。パスやファイル名を確認してください。\n\n")
    return(invisible(NULL))
  }
  if (!file.exists(file_oof_feat)) {
    cat("  [WARN] WithError_andFeatures ファイルが見つかりません。パスやファイル名を確認してください。\n\n")
    return(invisible(NULL))
  }

  oof_err <- read_csv(file_oof_err, show_col_types = FALSE)
  feat    <- read_csv(file_oof_feat, show_col_types = FALSE) %>%
    dplyr::select(-dplyr::any_of(c("Observed", "Predicted", "AbsError")))

  needed_cols_err <- c(col_true, col_pred, col_abserr, col_id)
  miss_err <- setdiff(needed_cols_err, colnames(oof_err))
  if (length(miss_err) > 0) {
    cat("  [ERROR] OOF+Error ファイルに必要な列がありません:\n")
    print(miss_err)
    return(invisible(NULL))
  }
  if (!(col_id %in% colnames(feat))) {
    cat("  [ERROR] Features ファイルに ID 列がありません: ", col_id, "\n")
    return(invisible(NULL))
  }

  ## 誤差概要をコンソールに表示
  cat("誤差 (", col_abserr, ") summary:\n", sep = "")
  print(summary(oof_err[[col_abserr]]))
  cat("\n")

  ## ヒストグラムを保存
  p_hist <- ggplot(oof_err, aes(x = .data[[col_abserr]])) +
    geom_histogram(bins = 30, color = "black", fill = "skyblue") +
    theme_bw() +
    labs(title = paste0("Histogram of abs_error (", target, ")"))
  ggsave(filename = file.path(out_dir, paste0("hist_abs_error_", target, ".png")),
         plot = p_hist, width = 6, height = 4)

  ## 閾値決定：目的変数ごとの固定値を最優先
  chosen_abs_thr <- NA_real_

  if (isTRUE(use_abs_thr_mode)) {
    if (!is.null(abs_error_thr_list[[target]])) {
      ## 1) target固有の固定しきい値
      chosen_abs_thr <- abs_error_thr_list[[target]]
      cat("abs_error_thr_list に基づき、",
          target, " の閾値として ", chosen_abs_thr, " を使用します。\n", sep = "")
    } else if (!is.na(abs_error_thr)) {
      ## 2) 共通しきい値
      chosen_abs_thr <- abs_error_thr
      cat("共通 abs_error_thr として指定された ",
          chosen_abs_thr, " を使用します。\n", sep = "")
    } else if (isTRUE(use_top_k_mode)) {
      ## 3) 明示的な値が無い場合のみ top_k を保険的に使用
      if (is.na(top_k) || top_k <= 0) {
        cat("  [WARN] top_k が正しく設定されていません。top_k モードは無効化します。\n")
      } else {
        oof_sorted <- oof_err %>% arrange(desc(.data[[col_abserr]]))
        k_eff <- min(top_k, nrow(oof_sorted))
        chosen_abs_thr <- oof_sorted[[col_abserr]][k_eff]
        cat("top_k モードにより、", target,
            " の閾値として ", chosen_abs_thr,
            " (上位 ", k_eff, " 件目) を使用します。\n", sep = "")
      }
    } else {
      ## 4) それでも決まらない場合は IQR ベース
      q   <- quantile(oof_err[[col_abserr]], probs = 0.75, na.rm = TRUE)
      iqr <- IQR(oof_err[[col_abserr]], na.rm = TRUE)
      chosen_abs_thr <- as.numeric(q + 2 * iqr)
      cat("abs_error_thr 未指定のため、IQR ベース閾値 ",
          chosen_abs_thr, " を使用します。\n", sep = "")
    }
  }

  cat("\n最終的に使用する abs_error 閾値 =", chosen_abs_thr, "\n\n")

  ## S フラグ付け
  oof_err <- oof_err %>%
    mutate(is_S = .data[[col_abserr]] >= chosen_abs_thr)

  n_S <- sum(oof_err$is_S, na.rm = TRUE)
  cat("S (外れ値候補) の件数:", n_S, "/", nrow(oof_err), "\n")
  if (n_S > 0) {
    cat("S の abs_error 範囲:\n")
    print(range(oof_err[[col_abserr]][oof_err$is_S], na.rm = TRUE))
  }
  cat("\n")

  ## 特徴量と結合
  dat_all <- feat %>%
    left_join(oof_err %>%
                select(.data[[col_id]], .data[[col_true]], .data[[col_pred]],
                       .data[[col_abserr]], is_S),
              by = col_id)

  cat("結合後データ行数:", nrow(dat_all), "\n\n")

  ## 出力ファイルパス
  file_S        <- file.path(out_dir, paste0("high_error_Samples_", target, ".csv"))
  file_all      <- file.path(out_dir, paste0("all_with_Sflag_", target, ".csv"))
  file_summ_S   <- file.path(out_dir, paste0("summary_S_numeric_", target, ".csv"))
  file_summ_nonS<- file.path(out_dir, paste0("summary_nonS_numeric_", target, ".csv"))

  ## CSV 出力
  dat_all %>% filter(is_S)  %>% write_csv(file_S)
  write_csv(dat_all, file_all)

  ## Obs vs Pred 散布図
  p_scatter <- ggplot(dat_all,
                      aes(x = .data[[col_true]],
                          y = .data[[col_pred]],
                          color = is_S)) +
    geom_point(alpha = 0.7) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    theme_bw() +
    labs(title = paste0("Obs vs Pred (", target, ")"),
         x = paste0("Observed ", target),
         y = paste0("Predicted ", target))

  ggsave(filename = file.path(out_dir, paste0("obs_vs_pred_", target, ".png")),
         plot = p_scatter, width = 6, height = 5)

  ## S / 非S の数値要約
  num_cols <- sapply(dat_all, is.numeric)

  summ_S <- dat_all %>%
    filter(is_S) %>%
    summarise(across(which(num_cols), list(mean = mean, sd = sd), na.rm = TRUE))
  summ_nonS <- dat_all %>%
    filter(!is_S) %>%
    summarise(across(which(num_cols), list(mean = mean, sd = sd), na.rm = TRUE))

  write_csv(summ_S,    file_summ_S)
  write_csv(summ_nonS, file_summ_nonS)

  cat("結果ファイル出力完了:\n")
  cat("  S のみ:                  ", file_S, "\n")
  cat("  全サンプル+Sフラグ:      ", file_all, "\n")
  cat("  Obs vs Pred 図:          ", file.path(out_dir, paste0("obs_vs_pred_", target, ".png")), "\n")
  cat("  S 数値要約:              ", file_summ_S, "\n")
  cat("  非S 数値要約:            ", file_summ_nonS, "\n\n")

  invisible(NULL)
}

############################################
## メイン：4 目的変数を順に処理
############################################

cat("=========== 外れ値解析スクリプト開始 ===========\n\n")
cat("base_path:", base_path, "\n\n")

for (tg in names(target_config)) {
  process_one_target(tg)
}

cat("=========== 外れ値解析スクリプト終了 ===========\n\n")


############################################
## 総括フォルダを作って結果を一括コピー
############################################

summary_dir <- file.path(base_path, summary_folder_name)
if (!dir.exists(summary_dir)) dir.create(summary_dir, recursive = TRUE)

targets <- names(target_config)

for (tg in targets) {
  src_dir <- file.path(base_path, paste0(output_prefix, "_", tg))

  ## ターゲットごとのサブフォルダを総括フォルダ配下に作成
  tgt_dir <- file.path(summary_dir, tg)
  if (!dir.exists(tgt_dir)) dir.create(tgt_dir, recursive = TRUE)

  ## コピー対象のファイル名
  src_files <- c(
    paste0("high_error_Samples_",    tg, ".csv"),
    paste0("all_with_Sflag_",       tg, ".csv"),
    paste0("summary_S_numeric_",    tg, ".csv"),
    paste0("summary_nonS_numeric_", tg, ".csv"),
    paste0("obs_vs_pred_",          tg, ".png"),
    paste0("hist_abs_error_",       tg, ".png")
  )

  for (f in src_files) {
    src_path <- file.path(src_dir, f)
    if (file.exists(src_path)) {
      file.copy(src_path,
                to = file.path(tgt_dir, f),
                overwrite = TRUE)
    } else {
      message("[INFO] ファイルが見つかりませんでした: ", src_path)
    }
  }
}

cat("総括フォルダへのコピー完了:\n  ", summary_dir, "\n")

=========== <U+5916><U+308C><U+5024><U+89E3><U+6790><U+30B9><U+30AF><U+30EA><U+30D7><U+30C8><U+958B><U+59CB> ===========

base_path: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier

============================================
Target: PCEmax
 model_name  : SVM_Radial
 dataset_tag : m_all_OH
 folder_name : PCE
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/PCE/m_all_OH_rebuilt_PCEmax_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/PCE/m_all_OH_rebuilt_PCEmax_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax

<U+8AA4><U+5DEE> (AbsError) summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00063 0.33022 0.74673 0.95654 1.33754 5.47919

abs_error_thr_list <U+306B><U+57FA><U+3065><U+304D><U+3001>PCEmax <U+306E><U+95BE><U+5024><U+3068><U+3057><U+3066> 3.5 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 3.5

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 18 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1] 3.523969 5.479190

<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/high_error_Samples_PCEmax.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/all_with_Sflag_PCEmax.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/obs_vs_pred_PCEmax.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/summary_S_numeric_PCEmax.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/summary_nonS_numeric_PCEmax.csv

============================================
Target: Jsc
 model_name  : gprLinear
 dataset_tag : m_all_OH
 folder_name : Jsc
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Jsc/m_all_OH_rebuilt_Jsc_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Jsc/m_all_OH_rebuilt_Jsc_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc

<U+8AA4><U+5DEE> (AbsError) summary:
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
 0.009943  0.637469  1.366075  1.792551  2.429419 11.000708

abs_error_thr_list <U+306B><U+57FA><U+3065><U+304D><U+3001>Jsc <U+306E><U+95BE><U+5024><U+3068><U+3057><U+3066> 5 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 5

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 50 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1]  5.015526 11.000708

<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/high_error_Samples_Jsc.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/all_with_Sflag_Jsc.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/obs_vs_pred_Jsc.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/summary_S_numeric_Jsc.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/summary_nonS_numeric_Jsc.csv

============================================
Target: Voc
 model_name  : RF
 dataset_tag : m_base_FP
 folder_name : Voc
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Voc/m_base_FP_rebuilt_Voc_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Voc/m_base_FP_rebuilt_Voc_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc

<U+8AA4><U+5DEE> (AbsError) summary:
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.0001277 0.0104600 0.0242955 0.0463050 0.0548577 0.6774933

abs_error_thr_list <U+306B><U+57FA><U+3065><U+304D><U+3001>Voc <U+306E><U+95BE><U+5024><U+3068><U+3057><U+3066> 0.15 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 0.15

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 60 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1] 0.1514257 0.6774933

<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/high_error_Samples_Voc.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/all_with_Sflag_Voc.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/obs_vs_pred_Voc.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/summary_S_numeric_Voc.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/summary_nonS_numeric_Voc.csv

============================================
Target: FF
 model_name  : kNN
 dataset_tag : m_all_FP
 folder_name : FF
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/FF/m_all_FP_rebuilt_FF_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/FF/m_all_FP_rebuilt_FF_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF

<U+8AA4><U+5DEE> (AbsError) summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00000 0.02000 0.04667 0.05962 0.08233 0.39000

abs_error_thr_list <U+306B><U+57FA><U+3065><U+304D><U+3001>FF <U+306E><U+95BE><U+5024><U+3068><U+3057><U+3066> 0.2 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 0.2

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 30 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1] 0.20 0.39

<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/high_error_Samples_FF.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/all_with_Sflag_FF.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/obs_vs_pred_FF.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/summary_S_numeric_FF.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/summary_nonS_numeric_FF.csv

=========== <U+5916><U+308C><U+5024><U+89E3><U+6790><U+30B9><U+30AF><U+30EA><U+30D7><U+30C8><U+7D42><U+4E86> ===========

<U+7DCF><U+62EC><U+30D5><U+30A9><U+30EB><U+30C0><U+3078><U+306E><U+30B3><U+30D4><U+30FC><U+5B8C><U+4E86>:
   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_summary_fixedThr_20260119

In [21]:
# ############################################
# ## ユーザーが変更すべきハイパーパラメータ
# ############################################

# ## 1) ベースパス（outlier の直下まで）
# ## 必須：自分の環境に合わせて変更
# base_path <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"

# ## 2) 解析対象の目的変数と、そのモデル名・dataset_tag の対応
# ##   - PCEmax: SVM_Radial × m_all_OH.csv  → フォルダ: PCE
# ##   - Jsc   : gprLinear × m_all_OH.csv   → フォルダ: Jsc
# ##   - Voc   : RF        × m_base_FP.csv  → フォルダ: Voc
# ##   - FF    : kNN       × m_all_FP.csv   → フォルダ: FF
# target_config <- list(
#   PCEmax = list(model_name = "SVM_Radial", folder_name = "PCE", dataset_tag = "m_all_OH"),
#   Jsc    = list(model_name = "gprLinear",  folder_name = "Jsc", dataset_tag = "m_all_OH"),
#   Voc    = list(model_name = "RF",         folder_name = "Voc", dataset_tag = "m_base_FP"),
#   FF     = list(model_name = "kNN",        folder_name = "FF",  dataset_tag = "m_all_FP")
# )

# ## 3) bundle フォルダ名
# ##   outlier/bundle_for_thesis_20260119/<target_folder>/...
# bundle_folder_name <- "bundle_for_thesis_20260119"


# ## 4) 誤差ファイル内の列名
# ##   実データの列名に合わせて必要に応じて変更
# col_true   <- "Observed"   # 実測値
# col_pred   <- "Predicted"  # 予測値
# col_abserr <- "AbsError"   # 絶対誤差
# col_id     <- "SampleID"   # サンプルID


# ## 5) 外れ値抽出モード
# ##   両方 TRUE でもよいが、その場合「top_k ベースの閾値」が優先される
# use_top_k_mode   <- TRUE   # TRUE: 上位 k 件を S にする
# use_abs_thr_mode <- TRUE   # TRUE: 絶対誤差しきい値で S にする

# ## 6) 「上位 k 件」モードのパラメータ
# ##   use_top_k_mode = TRUE の場合は必須 (正の整数)。
# ##   各目的変数とも「数個〜十数個」になるよう、まず 10 から試すのがおすすめ。
# top_k <- 10

# ## 7) 「絶対誤差しきい値」モードのパラメータ
# ##   use_abs_thr_mode = TRUE のとき、指定すれば固定閾値として使われる。
# ##   NA のままなら「top_k から自動設定」になる。
# ##   PCEmax が 0〜1 スケールなら 0.05〜0.1 程度が目安。
# abs_error_thr <- NA_real_  # 必須ではない（NA も可）

# ## 8) 出力フォルダ名プレフィックス
# ##   base_path 直下に "<output_prefix>_<target>" フォルダを作成。
# output_prefix <- "outlier_results"

# ############################################
# ## ここから下は通常変更不要
# ############################################

# suppressPackageStartupMessages({
#   library(dplyr)
#   library(ggplot2)
#   library(readr)
# })

# ## 1目的変数を処理する関数
# process_one_target <- function(target) {

#   cfg <- target_config[[target]]
#   if (is.null(cfg)) {
#     cat("  [WARN] target_config に設定がありません: ", target, "\n")
#     return(invisible(NULL))
#   }

#   model_name   <- cfg$model_name
#   dataset_tag  <- cfg$dataset_tag
#   folder_name  <- cfg$folder_name   # PCE, Jsc, Voc, FF

#   cat("============================================\n")
#   cat("Target:", target, "\n")
#   cat(" model_name  :", model_name,  "\n")
#   cat(" dataset_tag :", dataset_tag, "\n")
#   cat(" folder_name :", folder_name, "\n")
#   cat("============================================\n")

#   ## フォルダとファイルパス生成
#   ## 例: .../outlier/bundle_for_thesis_20260119/PCE/
#   bundle_path <- file.path(base_path, bundle_folder_name, folder_name)

#   ## ファイル名のベース
#   ## 例: m_all_OH_rebuilt_PCEmax_pred_OOF_withError.csv
#   base_file_stub <- paste0(dataset_tag, "_rebuilt_", target)

#   file_oof_err  <- file.path(bundle_path,
#                              paste0(base_file_stub, "_pred_OOF_withError.csv"))
#   file_oof_feat <- file.path(bundle_path,
#                              paste0(base_file_stub, "_pred_OOF_withError_andFeatures.csv"))

#   ## 出力フォルダ（目的変数ごと）
#   out_dir <- file.path(base_path, paste0(output_prefix, "_", target))
#   if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

#   cat("Input (OOF+Error):     ", file_oof_err,  "\n")
#   cat("Input (WithFeatures):  ", file_oof_feat, "\n")
#   cat("Output dir:            ", out_dir,       "\n\n")

#   if (!file.exists(file_oof_err)) {
#     cat("  [WARN] OOF+Error ファイルが見つかりません。パスやファイル名を確認してください。\n\n")
#     return(invisible(NULL))
#   }
#   if (!file.exists(file_oof_feat)) {
#     cat("  [WARN] WithError_andFeatures ファイルが見つかりません。パスやファイル名を確認してください。\n\n")
#     return(invisible(NULL))
#   }

#     oof_err <- read_csv(file_oof_err, show_col_types = FALSE)

#     feat    <- read_csv(file_oof_feat, show_col_types = FALSE) %>%
#       dplyr::select(-dplyr::any_of(c("Observed", "Predicted", "AbsError")))

#   cat(">> oof_err cols:\n"); print(names(oof_err))
#   cat(">> feat cols:\n");    print(names(feat))

#   needed_cols_err <- c(col_true, col_pred, col_abserr, col_id)
#   miss_err <- setdiff(needed_cols_err, colnames(oof_err))
#   if (length(miss_err) > 0) {
#     cat("  [ERROR] OOF+Error ファイルに必要な列がありません:\n")
#     print(miss_err)
#     return(invisible(NULL))
#   }
#   if (!(col_id %in% colnames(feat))) {
#     cat("  [ERROR] Features ファイルに ID 列がありません: ", col_id, "\n")
#     return(invisible(NULL))
#   }

#   ## 誤差概要をコンソールに表示
#   cat("誤差 (", col_abserr, ") summary:\n", sep = "")
#   print(summary(oof_err[[col_abserr]]))
#   cat("\n")

#   ## ヒストグラムを保存
#   p_hist <- ggplot(oof_err, aes(x = .data[[col_abserr]])) +
#     geom_histogram(bins = 30, color = "black", fill = "skyblue") +
#     theme_bw() +
#     labs(title = paste0("Histogram of abs_error (", target, ")"))
#   ggsave(filename = file.path(out_dir, paste0("hist_abs_error_", target, ".png")),
#          plot = p_hist, width = 6, height = 4)

#   ## 閾値決定：top_k 優先
#   chosen_top_k  <- NA_integer_
#   thr_from_topk <- NA_real_

#   if (isTRUE(use_top_k_mode)) {
#     if (is.na(top_k) || top_k <= 0) {
#       cat("  [WARN] top_k が正しく設定されていません。top_k モードは無効化します。\n")
#     } else {
#       oof_sorted <- oof_err %>% arrange(desc(.data[[col_abserr]]))
#       k_eff <- min(top_k, nrow(oof_sorted))
#       thr_from_topk <- oof_sorted[[col_abserr]][k_eff]
#       chosen_top_k  <- k_eff

#       cat("top_k モード: 上位 ", k_eff, " 件目の abs_error = ", thr_from_topk,
#           " を閾値候補とします。\n", sep = "")
#     }
#   }

#   chosen_abs_thr <- abs_error_thr

#   if (isTRUE(use_abs_thr_mode)) {
#     if (is.na(abs_error_thr)) {
#       if (!is.na(chosen_top_k)) {
#         chosen_abs_thr <- thr_from_topk
#         cat("abs_error_thr 未指定のため、top_k に由来する ",
#             chosen_abs_thr, " を使用します。\n", sep = "")
#       } else {
#         ## 万一 top_k も使えない場合のバックアップ
#         q   <- quantile(oof_err[[col_abserr]], probs = 0.75, na.rm = TRUE)
#         iqr <- IQR(oof_err[[col_abserr]], na.rm = TRUE)
#         chosen_abs_thr <- as.numeric(q + 1.5 * iqr)
#         cat("abs_error_thr 未指定かつ top_k 無効のため、IQR ベース閾値 ",
#             chosen_abs_thr, " を使用します。\n", sep = "")
#       }
#     } else {
#       cat("abs_error_thr モード: 指定された閾値 ", chosen_abs_thr, " を使用します。\n", sep = "")
#     }
#   } else {
#     if (!is.na(chosen_top_k)) {
#       chosen_abs_thr <- thr_from_topk
#     } else {
#       chosen_abs_thr <- median(oof_err[[col_abserr]], na.rm = TRUE)
#     }
#   }

#   cat("\n最終的に使用する abs_error 閾値 =", chosen_abs_thr, "\n\n")

#   ## S フラグ付け
#   oof_err <- oof_err %>%
#     mutate(is_S = .data[[col_abserr]] >= chosen_abs_thr)

#   n_S <- sum(oof_err$is_S, na.rm = TRUE)
#   cat("S (外れ値候補) の件数:", n_S, "/", nrow(oof_err), "\n")
#   if (n_S > 0) {
#     cat("S の abs_error 範囲:\n")
#     print(range(oof_err[[col_abserr]][oof_err$is_S], na.rm = TRUE))
#   }
#   cat("\n")

#   dat_all <- feat %>%
#     left_join(oof_err %>%
#                 select(.data[[col_id]], .data[[col_true]], .data[[col_pred]],
#                        .data[[col_abserr]], is_S),
#               by = col_id)
#   cat(">> dat_all cols:\n"); print(names(dat_all))

#   cat("結合後データ行数:", nrow(dat_all), "\n\n")

#   ## 出力
#   file_S   <- file.path(out_dir, paste0("high_error_Samples_", target, ".csv"))
#   file_all <- file.path(out_dir, paste0("all_with_Sflag_", target, ".csv"))

#   dat_all %>% filter(is_S) %>% write_csv(file_S)
#   write_csv(dat_all, file_all)

#   p_scatter <- ggplot(dat_all,
#                       aes(x = .data[[col_true]],
#                           y = .data[[col_pred]],
#                           color = is_S)) +
#     geom_point(alpha = 0.7) +
#     geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
#     theme_bw() +
#     labs(title = paste0("Obs vs Pred (", target, ")"),
#          x = paste0("Observed ", target),
#          y = paste0("Predicted ", target))

#   ggsave(filename = file.path(out_dir, paste0("obs_vs_pred_", target, ".png")),
#          plot = p_scatter, width = 6, height = 5)

#   num_cols <- sapply(dat_all, is.numeric)

#   summ_S <- dat_all %>%
#     filter(is_S) %>%
#     summarise(across(which(num_cols), list(mean = mean, sd = sd), na.rm = TRUE))
#   summ_nonS <- dat_all %>%
#     filter(!is_S) %>%
#     summarise(across(which(num_cols), list(mean = mean, sd = sd), na.rm = TRUE))

#   file_summ_S    <- file.path(out_dir, paste0("summary_S_numeric_", target, ".csv"))
#   file_summ_nonS <- file.path(out_dir, paste0("summary_nonS_numeric_", target, ".csv"))

#   write_csv(summ_S,    file_summ_S)
#   write_csv(summ_nonS, file_summ_nonS)

#   cat("結果ファイル出力完了:\n")
#   cat("  S のみ:                  ", file_S, "\n")
#   cat("  全サンプル+Sフラグ:      ", file_all, "\n")
#   cat("  Obs vs Pred 図:          ", file.path(out_dir, paste0("obs_vs_pred_", target, ".png")), "\n")
#   cat("  S 数値要約:              ", file_summ_S, "\n")
#   cat("  非S 数値要約:            ", file_summ_nonS, "\n\n")

#   invisible(NULL)
# }

# ## メイン：4 目的変数を順に処理
# cat("=========== 外れ値解析スクリプト開始 ===========\n\n")
# cat("base_path:", base_path, "\n\n")

# for (tg in names(target_config)) {
#   process_one_target(tg)
# }

# cat("=========== 外れ値解析スクリプト終了 ===========\n")

=========== <U+5916><U+308C><U+5024><U+89E3><U+6790><U+30B9><U+30AF><U+30EA><U+30D7><U+30C8><U+958B><U+59CB> ===========

base_path: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier

============================================
Target: PCEmax
 model_name  : SVM_Radial
 dataset_tag : m_all_OH
 folder_name : PCE
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/PCE/m_all_OH_rebuilt_PCEmax_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/PCE/m_all_OH_rebuilt_PCEmax_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax

>> oof_err cols:
[1] "SampleID"           "foldID"             "Observed"
[4] "Predicted"          "Error"              "AbsError"
[7] "Type"               "HighErrorFlag"      "HighErrorThreshold"
>> feat cols:
  [1] "SampleID"
  [2] "foldID"
  [3] "Error"
  [4] "Type"
  [5] "HighErrorFlag"
  [6] "HighErrorThreshold"
  [7] "THFSVAafetrN"
  [8] "THFSVAafetrI"
  [9] "Aarea"
 [10] "Aonsetp1Mfilm"
 [11] "Abandp1Mfilm1"
 [12] "Abandp1Mfilm2"
 [13] "Abandp1Mfilm3"
 [14] "Aonsetp1MSol"
 [15] "Abandp1MSol1"
 [16] "Abandp1MSol2"
 [17] "Abandp1MSol3"
 [18] "AfAeThin"
 [19] "ALthickness"
 [20] "amountAditive"
 [21] "amountsolutionI"
 [22] "cycle"
 [23] "E12oxp1M"
 [24] "E12redp1M"
 [25] "EgDFTp1M"
 [26] "EgECnM"
 [27] "EgECp1M"
 [28] "EgoptnM"
 [29] "Egoptp1M"
 [30] "FWHMThin"
 [31] "HOMODFTp1M"
 [32] "HOMOECp1M"
 [33] "HOMOp1M"
 [34] "Lay2SCspeed"
 [35] "Lay2SCtime"
 [36] "Lay2TAtemp"
 [37] "Lay2TAtime"
 [38] "Lay2thickness"
 [39] "Lay5thickness"
 [40] "Lay6DPpreTorr"
 [41] "Lay6thickness"
 [42] "LUMOECp1M"
 [43] "LUMOnM"
 [44] "LUMOp1M"
 [45] "measureINT"
 [46] "Mmonomerp1M"
 [47] "MnkDanM"
 [48] "MnkDap1M"
 [49] "MnMp1M"
 [50] "MPDnp1M"
 [51] "MwkDap1M"
 [52] "NLthickness"
 [53] "PDInM"
 [54] "PDIp1M"
 [55] "PLthickness"
 [56] "RatioinM"
 [57] "Ratioip1M"
 [58] "Ratioip2M"
 [59] "RationM"
 [60] "Ratiop1M"
 [61] "Ratiop2M"
 [62] "SCspeed1"
 [63] "SCtime1"
 [64] "solution"
 [65] "solutionI"
 [66] "solutionN"
 [67] "solutionP"
 [68] "solutionPI"
 [69] "solutionPN"
 [70] "T5dp1M"
 [71] "TAtemp1"
 [72] "TAtime1"
 [73] "TAtimelast"
 [74] "TD1temp"
 [75] "TD2temp"
 [76] "TDtime"
 [77] "UVIntP"
 [78] "UVtimeP"
 [79] "VolRatioS1"
 [80] "Lay2Mname_"
 [81] "Lay2Mname_PEDOTPSS"
 [82] "Lay2Mname_ZnO"
 [83] "Lay2Mname_ZnOC60"
 [84] "Lay5electronodes1_"
 [85] "Lay5electronodes1_Al"
 [86] "Lay5electronodes1_BCP"
 [87] "Lay5electronodes1_C60bis"
 [88] "Lay5electronodes1_Ca"
 [89] "Lay5electronodes1_ETL.1"
 [90] "Lay5electronodes1_Li"
 [91] "Lay5electronodes1_LiF"
 [92] "Lay5electronodes1_Mg"
 [93] "Lay5electronodes1_MoO3"
 [94] "Lay5electronodes1_MoO3orV2O5"
 [95] "Lay5electronodes1_MoOx"
 [96] "Lay5electronodes1_TiOx"
 [97] "Lay6electronodes2_"
 [98] "Lay6electronodes2_Ag"
 [99] "Lay6electronodes2_Al"
[100] "Additivesname_"
[101] "Additivesname_1.8dibromoooctane"
[102] "Additivesname_1.8dicholorooctane"
[103] "Additivesname_1.8dicyanooctane"
[104] "Additivesname_1.8octanediacetate"
[105] "Additivesname_1.8octanedithiol"
[106] "Additivesname_1CN"
[107] "Additivesname_CS2"
[108] "Additivesname_DCB"
[109] "Additivesname_DIO"
[110] "Additivesname_DPE"
[111] "namessolvent1_"
[112] "namessolvent1_CB"
[113] "namessolvent1_CF"
[114] "namessolvent1_DCM"
[115] "namessolvent1_TCB"
[116] "namessolvent1_THF"
[117] "namessolvent1_oDCB"
[118] "namessolvent2_"
[119] "namessolvent2_CB"
[120] "namessolvent2_CF"
[121] "namessolvent2_DIO"
[122] "namessolvent2_oDCB"
[123] "SMILESsnameinM_PC61BM"
[124] "SMILESsnameinM_PC71BM"
[125] "SMILESsnameip1M_AtD"
[126] "SMILESsnameip1M_BP"
[127] "SMILESsnameip1M_BP.C60"
[128] "SMILESsnameip1M_Bu.BP.C60"
[129] "SMILESsnameip1M_C4DBTA"
[130] "SMILESsnameip1M_C6DBTA"
[131] "SMILESsnameip1M_C8DBTA"
[132] "SMILESsnameip1M_DTA"
[133] "SMILESsnameip1M_EBDBTA"
[134] "SMILESsnameip1M_EH.DBTA"
[135] "SMILESsnameip1M_f.BP.C60"
[136] "SMILESsnameip1M_r.BP.C60"
[137] "SMILESsnameip2M_BP"
[138] "SMILESsnamenM_C60"
[139] "SMILESsnamenM_DBFIEDOT"
[140] "SMILESsnamenM_DPc.T"
[141] "SMILESsnamenM_DPc.mP"
[142] "SMILESsnamenM_ICEM"
[143] "SMILESsnamenM_ICMA"
[144] "SMILESsnamenM_ICMM"
[145] "SMILESsnamenM_MOPFP"
[146] "SMILESsnamenM_NC70BA"
[147] "SMILESsnamenM_NCMA"
[148] "SMILESsnamenM_NCMM"
[149] "SMILESsnamenM_PC61BM"
[150] "SMILESsnamenM_PC71BM"
[151] "SMILESsnamenM_PCBM"
[152] "SMILESsnamenM_PFP"
[153] "SMILESsnamenM_PNDTI.BT"
[154] "SMILESsnamenM_PNDTI.DTT"
[155] "SMILESsnamenM_PNDTI.T"
[156] "SMILESsnamenM_PNDTI.TT"
[157] "SMILESsnamenM_PTBI2T"
[158] "SMILESsnamenM_PTBI2TR"
[159] "SMILESsnamenM_PTBI2Tz"
[160] "SMILESsnamenM_PTBITT"
[161] "SMILESsnamenM_TC61BM"
[162] "SMILESsnamenM_TC61PM"
[163] "SMILESsnamenM_TFP"
[164] "SMILESsnamenM_THPc"
[165] "SMILESsnamep1M_2.2..bithiopheneP1"
[166] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP3"
[167] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP4"
[168] "SMILESsnamep1M_9triarylamino9HcarbazoleP3"
[169] "SMILESsnamep1M_ADT"
[170] "SMILESsnamep1M_AtD"
[171] "SMILESsnamep1M_BBTzBTIDG"
[172] "SMILESsnamep1M_BBTzalkylthiopheneBTIDG"
[173] "SMILESsnamep1M_BDTC6"
[174] "SMILESsnamep1M_BDTDTKP"
[175] "SMILESsnamep1M_BDTH1"
[176] "SMILESsnamep1M_BDTH11"
[177] "SMILESsnamep1M_BDTH3"
[178] "SMILESsnamep1M_BDTH6"
[179] "SMILESsnamep1M_BDTH7"
[180] "SMILESsnamep1M_BDTH8"
[181] "SMILESsnamep1M_BDTH9"
[182] "SMILESsnamep1M_BDTT6"
[183] "SMILESsnamep1M_BP"
[184] "SMILESsnamep1M_BPC60"
[185] "SMILESsnamep1M_BPc"
[186] "SMILESsnamep1M_BPcpre1"
[187] "SMILESsnamep1M_BPcpre2"
[188] "SMILESsnamep1M_BTAnt"
[189] "SMILESsnamep1M_BTIBDTP2"
[190] "SMILESsnamep1M_BuBPC60"
[191] "SMILESsnamep1M_C10DPPBP"
[192] "SMILESsnamep1M_C2DPPBP"
[193] "SMILESsnamep1M_C3DPPTTSe"
[194] "SMILESsnamep1M_C3DPPTTT"
[195] "SMILESsnamep1M_C3DPPTTTe"
[196] "SMILESsnamep1M_C4DPPBP"
[197] "SMILESsnamep1M_C6DPPBP"
[198] "SMILESsnamep1M_C8DPPBP"
[199] "SMILESsnamep1M_CPDTDTKP"
[200] "SMILESsnamep1M_DTA"
[201] "SMILESsnamep1M_DTAnt"
[202] "SMILESsnamep1M_DTBT"
[203] "SMILESsnamep1M_DTPDPP2TBDT"
[204] "SMILESsnamep1M_DTPDPP2TDBT"
[205] "SMILESsnamep1M_DTPDPP2TTT"
[206] "SMILESsnamep1M_DTPDPP3T"
[207] "SMILESsnamep1M_DTPDPP4T"
[208] "SMILESsnamep1M_DTPDPPTPT"
[209] "SMILESsnamep1M_DTSC4"
[210] "SMILESsnamep1M_DTSC6"
[211] "SMILESsnamep1M_DTSC6L"
[212] "SMILESsnamep1M_DTSC8"
[213] "SMILESsnamep1M_DTSCEH"
[214] "SMILESsnamep1M_DTSCh"
[215] "SMILESsnamep1M_DTSChy"
[216] "SMILESsnamep1M_DTSDC"
[217] "SMILESsnamep1M_DTST6"
[218] "SMILESsnamep1M_DTSTCh"
[219] "SMILESsnamep1M_DTSTChy"
[220] "SMILESsnamep1M_DTTPTP1"
[221] "SMILESsnamep1M_DTTPTP2"
[222] "SMILESsnamep1M_DTTPTP3"
[223] "SMILESsnamep1M_DTTPTP4"
[224] "SMILESsnamep1M_DTTPTP5"
[225] "SMILESsnamep1M_DTTPTP6"
[226] "SMILESsnamep1M_DTfBT"
[227] "SMILESsnamep1M_DTffBT"
[228] "SMILESsnamep1M_EHDBTA"
[229] "SMILESsnamep1M_F0F0"
[230] "SMILESsnamep1M_F0F2"
[231] "SMILESsnamep1M_F1PDPP2TBP"
[232] "SMILESsnamep1M_F2F0"
[233] "SMILESsnamep1M_F2F2"
[234] "SMILESsnamep1M_F2PDPP2TBP"
[235] "SMILESsnamep1M_FLODTKP"
[236] "SMILESsnamep1M_P.BDTFBT."
[237] "SMILESsnamep1M_P.BDTTBT."
[238] "SMILESsnamep1M_P.BDTTTBO."
[239] "SMILESsnamep1M_P.BDTTTBT."
[240] "SMILESsnamep1M_P.BDTTTFBT."
[241] "SMILESsnamep1M_P.BDTTTHBT."
[242] "SMILESsnamep1M_P.T32EHiI."
[243] "SMILESsnamep1M_P.T3C10iI."
[244] "SMILESsnamep1M_P.T3C12iI."
[245] "SMILESsnamep1M_P.T3C6iI."
[246] "SMILESsnamep1M_P.T3C8iI."
[247] "SMILESsnamep1M_P3HNT"
[248] "SMILESsnamep1M_P3HT"
[249] "SMILESsnamep1M_P4TBT"
[250] "SMILESsnamep1M_P4TDPP"
[251] "SMILESsnamep1M_P4TDTBT"
[252] "SMILESsnamep1M_P4TPDTQ"
[253] "SMILESsnamep1M_PBDFDODTBT"
[254] "SMILESsnamep1M_PBDFDTBO"
[255] "SMILESsnamep1M_PBDFDTBT"
[256] "SMILESsnamep1M_PBDFDTBTz"
[257] "SMILESsnamep1M_PBDFFBT"
[258] "SMILESsnamep1M_PBDT.DTBSe"
[259] "SMILESsnamep1M_PBDT.DTBT"
[260] "SMILESsnamep1M_PBDTBDD"
[261] "SMILESsnamep1M_PBDTBO"
[262] "SMILESsnamep1M_PBDTBT"
[263] "SMILESsnamep1M_PBDTBTz"
[264] "SMILESsnamep1M_PBDTDPT1"
[265] "SMILESsnamep1M_PBDTDPT2"
[266] "SMILESsnamep1M_PBDTDTBTm"
[267] "SMILESsnamep1M_PBDTDTBTo"
[268] "SMILESsnamep1M_PBDTDTBTp"
[269] "SMILESsnamep1M_PBDTDTBTz"
[270] "SMILESsnamep1M_PBDTDTTTST"
[271] "SMILESsnamep1M_PBDTFBO"
[272] "SMILESsnamep1M_PBDTFBT"
[273] "SMILESsnamep1M_PBDTFQT"
[274] "SMILESsnamep1M_PBDTFQTT"
[275] "SMILESsnamep1M_PBDTHDODTHBTffP3"
[276] "SMILESsnamep1M_PBDTPBO"
[277] "SMILESsnamep1M_PBDTPDTBT"
[278] "SMILESsnamep1M_PBDTPODTBO"
[279] "SMILESsnamep1M_PBDTPODTBT"
[280] "SMILESsnamep1M_PBDTPOFBT"
[281] "SMILESsnamep1M_PBDTT10TPD"
[282] "SMILESsnamep1M_PBDTT12TPD"
[283] "SMILESsnamep1M_PBDTT8TPD"
[284] "SMILESsnamep1M_PBDTTBO"
[285] "SMILESsnamep1M_PBDTTBT"
[286] "SMILESsnamep1M_PBDTTDPP"
[287] "SMILESsnamep1M_PBDTTDTBO"
[288] "SMILESsnamep1M_PBDTTDTBT"
[289] "SMILESsnamep1M_PBDTTDTBTz"
[290] "SMILESsnamep1M_PBDTTDTTBT"
[291] "SMILESsnamep1M_PBDTTEHDTEHBTffP2"
[292] "SMILESsnamep1M_PBDTTEHDTHBTffP1"
[293] "SMILESsnamep1M_PBDTTFBSe"
[294] "SMILESsnamep1M_PBDTTFDPP"
[295] "SMILESsnamep1M_PBDTTFTTE"
[296] "SMILESsnamep1M_PBDTTPD"
[297] "SMILESsnamep1M_PBDTTPDP1"
[298] "SMILESsnamep1M_PBDTTPDP2"
[299] "SMILESsnamep1M_PBDTTPDP3"
[300] "SMILESsnamep1M_PBDTTS1"
[301] "SMILESsnamep1M_PBDTTS2"
[302] "SMILESsnamep1M_PBDTTS3"
[303] "SMILESsnamep1M_PBDTTSeDPP"
[304] "SMILESsnamep1M_PBDTTTBT"
[305] "SMILESsnamep1M_PBDTTTC"
[306] "SMILESsnamep1M_PBDTTTCF"
[307] "SMILESsnamep1M_PBDTTTE"
[308] "SMILESsnamep1M_PBDTTTS"
[309] "SMILESsnamep1M_PBDTTTST"
[310] "SMILESsnamep1M_PBPT12"
[311] "SMILESsnamep1M_PBQ1"
[312] "SMILESsnamep1M_PBQ2"
[313] "SMILESsnamep1M_PBQ3"
[314] "SMILESsnamep1M_PBQ4"
[315] "SMILESsnamep1M_PBT0F"
[316] "SMILESsnamep1M_PBT1F"
[317] "SMILESsnamep1M_PBT2F"
[318] "SMILESsnamep1M_PBT3F"
[319] "SMILESsnamep1M_PBTPyDPP"
[320] "SMILESsnamep1M_PBTff4T2OD"
[321] "SMILESsnamep1M_PBnDTFTAZ"
[322] "SMILESsnamep1M_PBnDTHTAZ"
[323] "SMILESsnamep1M_PCBTDPP"
[324] "SMILESsnamep1M_PCDTBT"
[325] "SMILESsnamep1M_PCDTBX"
[326] "SMILESsnamep1M_PCDTDPP"
[327] "SMILESsnamep1M_PCDTPT"
[328] "SMILESsnamep1M_PCDTPX"
[329] "SMILESsnamep1M_PCDTQx"
[330] "SMILESsnamep1M_PCDTTPP"
[331] "SMILESsnamep1M_PCPDTBT"
[332] "SMILESsnamep1M_PCPTDO"
[333] "SMILESsnamep1M_PCTDPP"
[334] "SMILESsnamep1M_PCV"
[335] "SMILESsnamep1M_PCVT"
[336] "SMILESsnamep1M_PCVTT"
[337] "SMILESsnamep1M_PCVTTTT"
[338] "SMILESsnamep1M_PCz"
[339] "SMILESsnamep1M_PDPP2FTC12"
[340] "SMILESsnamep1M_PDPP2FTC14"
[341] "SMILESsnamep1M_PDPP2FTC16"
[342] "SMILESsnamep1M_PDPP2T"
[343] "SMILESsnamep1M_PDPP2TBP"
[344] "SMILESsnamep1M_PDPP3T"
[345] "SMILESsnamep1M_PDPP3TaltTPT"
[346] "SMILESsnamep1M_PDPPBBT"
[347] "SMILESsnamep1M_PDPPBT"
[348] "SMILESsnamep1M_PDPPTPT"
[349] "SMILESsnamep1M_PDPPTVT"
[350] "SMILESsnamep1M_PDTPDTDPP"
[351] "SMILESsnamep1M_PDTPDTDPPBu"
[352] "SMILESsnamep1M_PDTST"
[353] "SMILESsnamep1M_PDTSTPD"
[354] "SMILESsnamep1M_PEN"
[355] "SMILESsnamep1M_PFBTBDT"
[356] "SMILESsnamep1M_PFDTBT"
[357] "SMILESsnamep1M_PFDTDPP"
[358] "SMILESsnamep1M_PGFDTBT"
[359] "SMILESsnamep1M_PGFDTDPPC4S25"
[360] "SMILESsnamep1M_PGFDTDPPC8"
[361] "SMILESsnamep1M_PICDTBT"
[362] "SMILESsnamep1M_PIDTTFBSe"
[363] "SMILESsnamep1M_PNNT12DT"
[364] "SMILESsnamep1M_PNNT12HD"
[365] "SMILESsnamep1M_PNNTDT"
[366] "SMILESsnamep1M_PNOz4T"
[367] "SMILESsnamep1M_PNT4T2OD"
[368] "SMILESsnamep1M_PNTz4T"
[369] "SMILESsnamep1M_PNTz4TF2"
[370] "SMILESsnamep1M_PNTz4TF4"
[371] "SMILESsnamep1M_PPDT2FBT"
[372] "SMILESsnamep1M_PPDTBT"
[373] "SMILESsnamep1M_PPDTFBT"
[374] "SMILESsnamep1M_PQT12"
[375] "SMILESsnamep1M_PSBTBT"
[376] "SMILESsnamep1M_PSEHTT"
[377] "SMILESsnamep1M_PTB1"
[378] "SMILESsnamep1M_PTB2"
[379] "SMILESsnamep1M_PTB3"
[380] "SMILESsnamep1M_PTB4"
[381] "SMILESsnamep1M_PTB5"
[382] "SMILESsnamep1M_PTB6"
[383] "SMILESsnamep1M_PTB7"
[384] "SMILESsnamep1M_PTB7Th"
[385] "SMILESsnamep1M_PTBDTDTBT"
[386] "SMILESsnamep1M_PTBDTffDTBT"
[387] "SMILESsnamep1M_PTBF0"
[388] "SMILESsnamep1M_PTBF1"
[389] "SMILESsnamep1M_PTBF2"
[390] "SMILESsnamep1M_PTBF3"
[391] "SMILESsnamep1M_PTBFTDTBT"
[392] "SMILESsnamep1M_PTBI2T"
[393] "SMILESsnamep1M_PTBI2TR"
[394] "SMILESsnamep1M_PTBI2Tz"
[395] "SMILESsnamep1M_PTBITT"
[396] "SMILESsnamep1M_PTzBT10HD"
[397] "SMILESsnamep1M_PTzBT10OD"
[398] "SMILESsnamep1M_PTzBT12HD"
[399] "SMILESsnamep1M_PTzBT12OD"
[400] "SMILESsnamep1M_PTzBT14HD"
[401] "SMILESsnamep1M_PTzBT14OD"
[402] "SMILESsnamep1M_PTzBTBOBO"
[403] "SMILESsnamep1M_PTzBTBOHD"
[404] "SMILESsnamep1M_PTzBTBOOD"
[405] "SMILESsnamep1M_PTzBTEHHD"
[406] "SMILESsnamep1M_PTzBTEHOD"
[407] "SMILESsnamep1M_PTzBTHD"
[408] "SMILESsnamep1M_PTzQT14"
[409] "SMILESsnamep1M_PeNPz2T"
[410] "SMILESsnamep1M_PeNPz3T"
[411] "SMILESsnamep1M_PeNPz4T"
[412] "SMILESsnamep1M_PffBT4T2OD"
[413] "SMILESsnamep1M_PhBADT"
[414] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2.thienyl..1.2.5.oxadiazolo.3.4d.pyridazine.P1"
[415] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.2.3dioctylpyrazino.2.3d.pyridazine.P2"
[416] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.pyrazino.2.3d.pyridazine.P3"
[417] "SMILESsnamep1M_RanPBDPPT"
[418] "SMILESsnamep1M_RegPBDPPT"
[419] "SMILESsnamep1M_TDPPBBT"
[420] "SMILESsnamep1M_TPDBr16"
[421] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP1"
[422] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP2"
[423] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP3"
[424] "SMILESsnamep1M_TzTzBTIDG"
[425] "SMILESsnamep1M_TzTzalkylthiopheneBTIDG"
[426] "SMILESsnamep1M_VacdepoBPc"
[427] "SMILESsnamep1M_fBPC60"
[428] "SMILESsnamep1M_pBTTT"
[429] "SMILESsnamep1M_rBPC60"
[430] "SMILESsnamep1M_ranPDPPTPDalt2T"
[431] "SMILESsnamep1M_regPDPPTPDalt2T"
[432] "SMILESsnamep1M_thieno.3.2b.thiopheneP2"
[433] "SMILESsnamep2M_PBDTTFTTE"
<U+8AA4><U+5DEE> (AbsError) summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00063 0.33022 0.74673 0.95654 1.33754 5.47919

top_k <U+30E2><U+30FC><U+30C9>: <U+4E0A><U+4F4D> 10 <U+4EF6><U+76EE><U+306E> abs_error = 3.956352 <U+3092><U+95BE><U+5024><U+5019><U+88DC><U+3068><U+3057><U+307E><U+3059><U+3002>
abs_error_thr <U+672A><U+6307><U+5B9A><U+306E><U+305F><U+3081><U+3001>top_k <U+306B><U+7531><U+6765><U+3059><U+308B> 3.956352 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 3.956352

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 10 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1] 3.956352 5.479190

>> dat_all cols:
  [1] "SampleID"
  [2] "foldID"
  [3] "Error"
  [4] "Type"
  [5] "HighErrorFlag"
  [6] "HighErrorThreshold"
  [7] "THFSVAafetrN"
  [8] "THFSVAafetrI"
  [9] "Aarea"
 [10] "Aonsetp1Mfilm"
 [11] "Abandp1Mfilm1"
 [12] "Abandp1Mfilm2"
 [13] "Abandp1Mfilm3"
 [14] "Aonsetp1MSol"
 [15] "Abandp1MSol1"
 [16] "Abandp1MSol2"
 [17] "Abandp1MSol3"
 [18] "AfAeThin"
 [19] "ALthickness"
 [20] "amountAditive"
 [21] "amountsolutionI"
 [22] "cycle"
 [23] "E12oxp1M"
 [24] "E12redp1M"
 [25] "EgDFTp1M"
 [26] "EgECnM"
 [27] "EgECp1M"
 [28] "EgoptnM"
 [29] "Egoptp1M"
 [30] "FWHMThin"
 [31] "HOMODFTp1M"
 [32] "HOMOECp1M"
 [33] "HOMOp1M"
 [34] "Lay2SCspeed"
 [35] "Lay2SCtime"
 [36] "Lay2TAtemp"
 [37] "Lay2TAtime"
 [38] "Lay2thickness"
 [39] "Lay5thickness"
 [40] "Lay6DPpreTorr"
 [41] "Lay6thickness"
 [42] "LUMOECp1M"
 [43] "LUMOnM"
 [44] "LUMOp1M"
 [45] "measureINT"
 [46] "Mmonomerp1M"
 [47] "MnkDanM"
 [48] "MnkDap1M"
 [49] "MnMp1M"
 [50] "MPDnp1M"
 [51] "MwkDap1M"
 [52] "NLthickness"
 [53] "PDInM"
 [54] "PDIp1M"
 [55] "PLthickness"
 [56] "RatioinM"
 [57] "Ratioip1M"
 [58] "Ratioip2M"
 [59] "RationM"
 [60] "Ratiop1M"
 [61] "Ratiop2M"
 [62] "SCspeed1"
 [63] "SCtime1"
 [64] "solution"
 [65] "solutionI"
 [66] "solutionN"
 [67] "solutionP"
 [68] "solutionPI"
 [69] "solutionPN"
 [70] "T5dp1M"
 [71] "TAtemp1"
 [72] "TAtime1"
 [73] "TAtimelast"
 [74] "TD1temp"
 [75] "TD2temp"
 [76] "TDtime"
 [77] "UVIntP"
 [78] "UVtimeP"
 [79] "VolRatioS1"
 [80] "Lay2Mname_"
 [81] "Lay2Mname_PEDOTPSS"
 [82] "Lay2Mname_ZnO"
 [83] "Lay2Mname_ZnOC60"
 [84] "Lay5electronodes1_"
 [85] "Lay5electronodes1_Al"
 [86] "Lay5electronodes1_BCP"
 [87] "Lay5electronodes1_C60bis"
 [88] "Lay5electronodes1_Ca"
 [89] "Lay5electronodes1_ETL.1"
 [90] "Lay5electronodes1_Li"
 [91] "Lay5electronodes1_LiF"
 [92] "Lay5electronodes1_Mg"
 [93] "Lay5electronodes1_MoO3"
 [94] "Lay5electronodes1_MoO3orV2O5"
 [95] "Lay5electronodes1_MoOx"
 [96] "Lay5electronodes1_TiOx"
 [97] "Lay6electronodes2_"
 [98] "Lay6electronodes2_Ag"
 [99] "Lay6electronodes2_Al"
[100] "Additivesname_"
[101] "Additivesname_1.8dibromoooctane"
[102] "Additivesname_1.8dicholorooctane"
[103] "Additivesname_1.8dicyanooctane"
[104] "Additivesname_1.8octanediacetate"
[105] "Additivesname_1.8octanedithiol"
[106] "Additivesname_1CN"
[107] "Additivesname_CS2"
[108] "Additivesname_DCB"
[109] "Additivesname_DIO"
[110] "Additivesname_DPE"
[111] "namessolvent1_"
[112] "namessolvent1_CB"
[113] "namessolvent1_CF"
[114] "namessolvent1_DCM"
[115] "namessolvent1_TCB"
[116] "namessolvent1_THF"
[117] "namessolvent1_oDCB"
[118] "namessolvent2_"
[119] "namessolvent2_CB"
[120] "namessolvent2_CF"
[121] "namessolvent2_DIO"
[122] "namessolvent2_oDCB"
[123] "SMILESsnameinM_PC61BM"
[124] "SMILESsnameinM_PC71BM"
[125] "SMILESsnameip1M_AtD"
[126] "SMILESsnameip1M_BP"
[127] "SMILESsnameip1M_BP.C60"
[128] "SMILESsnameip1M_Bu.BP.C60"
[129] "SMILESsnameip1M_C4DBTA"
[130] "SMILESsnameip1M_C6DBTA"
[131] "SMILESsnameip1M_C8DBTA"
[132] "SMILESsnameip1M_DTA"
[133] "SMILESsnameip1M_EBDBTA"
[134] "SMILESsnameip1M_EH.DBTA"
[135] "SMILESsnameip1M_f.BP.C60"
[136] "SMILESsnameip1M_r.BP.C60"
[137] "SMILESsnameip2M_BP"
[138] "SMILESsnamenM_C60"
[139] "SMILESsnamenM_DBFIEDOT"
[140] "SMILESsnamenM_DPc.T"
[141] "SMILESsnamenM_DPc.mP"
[142] "SMILESsnamenM_ICEM"
[143] "SMILESsnamenM_ICMA"
[144] "SMILESsnamenM_ICMM"
[145] "SMILESsnamenM_MOPFP"
[146] "SMILESsnamenM_NC70BA"
[147] "SMILESsnamenM_NCMA"
[148] "SMILESsnamenM_NCMM"
[149] "SMILESsnamenM_PC61BM"
[150] "SMILESsnamenM_PC71BM"
[151] "SMILESsnamenM_PCBM"
[152] "SMILESsnamenM_PFP"
[153] "SMILESsnamenM_PNDTI.BT"
[154] "SMILESsnamenM_PNDTI.DTT"
[155] "SMILESsnamenM_PNDTI.T"
[156] "SMILESsnamenM_PNDTI.TT"
[157] "SMILESsnamenM_PTBI2T"
[158] "SMILESsnamenM_PTBI2TR"
[159] "SMILESsnamenM_PTBI2Tz"
[160] "SMILESsnamenM_PTBITT"
[161] "SMILESsnamenM_TC61BM"
[162] "SMILESsnamenM_TC61PM"
[163] "SMILESsnamenM_TFP"
[164] "SMILESsnamenM_THPc"
[165] "SMILESsnamep1M_2.2..bithiopheneP1"
[166] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP3"
[167] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP4"
[168] "SMILESsnamep1M_9triarylamino9HcarbazoleP3"
[169] "SMILESsnamep1M_ADT"
[170] "SMILESsnamep1M_AtD"
[171] "SMILESsnamep1M_BBTzBTIDG"
[172] "SMILESsnamep1M_BBTzalkylthiopheneBTIDG"
[173] "SMILESsnamep1M_BDTC6"
[174] "SMILESsnamep1M_BDTDTKP"
[175] "SMILESsnamep1M_BDTH1"
[176] "SMILESsnamep1M_BDTH11"
[177] "SMILESsnamep1M_BDTH3"
[178] "SMILESsnamep1M_BDTH6"
[179] "SMILESsnamep1M_BDTH7"
[180] "SMILESsnamep1M_BDTH8"
[181] "SMILESsnamep1M_BDTH9"
[182] "SMILESsnamep1M_BDTT6"
[183] "SMILESsnamep1M_BP"
[184] "SMILESsnamep1M_BPC60"
[185] "SMILESsnamep1M_BPc"
[186] "SMILESsnamep1M_BPcpre1"
[187] "SMILESsnamep1M_BPcpre2"
[188] "SMILESsnamep1M_BTAnt"
[189] "SMILESsnamep1M_BTIBDTP2"
[190] "SMILESsnamep1M_BuBPC60"
[191] "SMILESsnamep1M_C10DPPBP"
[192] "SMILESsnamep1M_C2DPPBP"
[193] "SMILESsnamep1M_C3DPPTTSe"
[194] "SMILESsnamep1M_C3DPPTTT"
[195] "SMILESsnamep1M_C3DPPTTTe"
[196] "SMILESsnamep1M_C4DPPBP"
[197] "SMILESsnamep1M_C6DPPBP"
[198] "SMILESsnamep1M_C8DPPBP"
[199] "SMILESsnamep1M_CPDTDTKP"
[200] "SMILESsnamep1M_DTA"
[201] "SMILESsnamep1M_DTAnt"
[202] "SMILESsnamep1M_DTBT"
[203] "SMILESsnamep1M_DTPDPP2TBDT"
[204] "SMILESsnamep1M_DTPDPP2TDBT"
[205] "SMILESsnamep1M_DTPDPP2TTT"
[206] "SMILESsnamep1M_DTPDPP3T"
[207] "SMILESsnamep1M_DTPDPP4T"
[208] "SMILESsnamep1M_DTPDPPTPT"
[209] "SMILESsnamep1M_DTSC4"
[210] "SMILESsnamep1M_DTSC6"
[211] "SMILESsnamep1M_DTSC6L"
[212] "SMILESsnamep1M_DTSC8"
[213] "SMILESsnamep1M_DTSCEH"
[214] "SMILESsnamep1M_DTSCh"
[215] "SMILESsnamep1M_DTSChy"
[216] "SMILESsnamep1M_DTSDC"
[217] "SMILESsnamep1M_DTST6"
[218] "SMILESsnamep1M_DTSTCh"
[219] "SMILESsnamep1M_DTSTChy"
[220] "SMILESsnamep1M_DTTPTP1"
[221] "SMILESsnamep1M_DTTPTP2"
[222] "SMILESsnamep1M_DTTPTP3"
[223] "SMILESsnamep1M_DTTPTP4"
[224] "SMILESsnamep1M_DTTPTP5"
[225] "SMILESsnamep1M_DTTPTP6"
[226] "SMILESsnamep1M_DTfBT"
[227] "SMILESsnamep1M_DTffBT"
[228] "SMILESsnamep1M_EHDBTA"
[229] "SMILESsnamep1M_F0F0"
[230] "SMILESsnamep1M_F0F2"
[231] "SMILESsnamep1M_F1PDPP2TBP"
[232] "SMILESsnamep1M_F2F0"
[233] "SMILESsnamep1M_F2F2"
[234] "SMILESsnamep1M_F2PDPP2TBP"
[235] "SMILESsnamep1M_FLODTKP"
[236] "SMILESsnamep1M_P.BDTFBT."
[237] "SMILESsnamep1M_P.BDTTBT."
[238] "SMILESsnamep1M_P.BDTTTBO."
[239] "SMILESsnamep1M_P.BDTTTBT."
[240] "SMILESsnamep1M_P.BDTTTFBT."
[241] "SMILESsnamep1M_P.BDTTTHBT."
[242] "SMILESsnamep1M_P.T32EHiI."
[243] "SMILESsnamep1M_P.T3C10iI."
[244] "SMILESsnamep1M_P.T3C12iI."
[245] "SMILESsnamep1M_P.T3C6iI."
[246] "SMILESsnamep1M_P.T3C8iI."
[247] "SMILESsnamep1M_P3HNT"
[248] "SMILESsnamep1M_P3HT"
[249] "SMILESsnamep1M_P4TBT"
[250] "SMILESsnamep1M_P4TDPP"
[251] "SMILESsnamep1M_P4TDTBT"
[252] "SMILESsnamep1M_P4TPDTQ"
[253] "SMILESsnamep1M_PBDFDODTBT"
[254] "SMILESsnamep1M_PBDFDTBO"
[255] "SMILESsnamep1M_PBDFDTBT"
[256] "SMILESsnamep1M_PBDFDTBTz"
[257] "SMILESsnamep1M_PBDFFBT"
[258] "SMILESsnamep1M_PBDT.DTBSe"
[259] "SMILESsnamep1M_PBDT.DTBT"
[260] "SMILESsnamep1M_PBDTBDD"
[261] "SMILESsnamep1M_PBDTBO"
[262] "SMILESsnamep1M_PBDTBT"
[263] "SMILESsnamep1M_PBDTBTz"
[264] "SMILESsnamep1M_PBDTDPT1"
[265] "SMILESsnamep1M_PBDTDPT2"
[266] "SMILESsnamep1M_PBDTDTBTm"
[267] "SMILESsnamep1M_PBDTDTBTo"
[268] "SMILESsnamep1M_PBDTDTBTp"
[269] "SMILESsnamep1M_PBDTDTBTz"
[270] "SMILESsnamep1M_PBDTDTTTST"
[271] "SMILESsnamep1M_PBDTFBO"
[272] "SMILESsnamep1M_PBDTFBT"
[273] "SMILESsnamep1M_PBDTFQT"
[274] "SMILESsnamep1M_PBDTFQTT"
[275] "SMILESsnamep1M_PBDTHDODTHBTffP3"
[276] "SMILESsnamep1M_PBDTPBO"
[277] "SMILESsnamep1M_PBDTPDTBT"
[278] "SMILESsnamep1M_PBDTPODTBO"
[279] "SMILESsnamep1M_PBDTPODTBT"
[280] "SMILESsnamep1M_PBDTPOFBT"
[281] "SMILESsnamep1M_PBDTT10TPD"
[282] "SMILESsnamep1M_PBDTT12TPD"
[283] "SMILESsnamep1M_PBDTT8TPD"
[284] "SMILESsnamep1M_PBDTTBO"
[285] "SMILESsnamep1M_PBDTTBT"
[286] "SMILESsnamep1M_PBDTTDPP"
[287] "SMILESsnamep1M_PBDTTDTBO"
[288] "SMILESsnamep1M_PBDTTDTBT"
[289] "SMILESsnamep1M_PBDTTDTBTz"
[290] "SMILESsnamep1M_PBDTTDTTBT"
[291] "SMILESsnamep1M_PBDTTEHDTEHBTffP2"
[292] "SMILESsnamep1M_PBDTTEHDTHBTffP1"
[293] "SMILESsnamep1M_PBDTTFBSe"
[294] "SMILESsnamep1M_PBDTTFDPP"
[295] "SMILESsnamep1M_PBDTTFTTE"
[296] "SMILESsnamep1M_PBDTTPD"
[297] "SMILESsnamep1M_PBDTTPDP1"
[298] "SMILESsnamep1M_PBDTTPDP2"
[299] "SMILESsnamep1M_PBDTTPDP3"
[300] "SMILESsnamep1M_PBDTTS1"
[301] "SMILESsnamep1M_PBDTTS2"
[302] "SMILESsnamep1M_PBDTTS3"
[303] "SMILESsnamep1M_PBDTTSeDPP"
[304] "SMILESsnamep1M_PBDTTTBT"
[305] "SMILESsnamep1M_PBDTTTC"
[306] "SMILESsnamep1M_PBDTTTCF"
[307] "SMILESsnamep1M_PBDTTTE"
[308] "SMILESsnamep1M_PBDTTTS"
[309] "SMILESsnamep1M_PBDTTTST"
[310] "SMILESsnamep1M_PBPT12"
[311] "SMILESsnamep1M_PBQ1"
[312] "SMILESsnamep1M_PBQ2"
[313] "SMILESsnamep1M_PBQ3"
[314] "SMILESsnamep1M_PBQ4"
[315] "SMILESsnamep1M_PBT0F"
[316] "SMILESsnamep1M_PBT1F"
[317] "SMILESsnamep1M_PBT2F"
[318] "SMILESsnamep1M_PBT3F"
[319] "SMILESsnamep1M_PBTPyDPP"
[320] "SMILESsnamep1M_PBTff4T2OD"
[321] "SMILESsnamep1M_PBnDTFTAZ"
[322] "SMILESsnamep1M_PBnDTHTAZ"
[323] "SMILESsnamep1M_PCBTDPP"
[324] "SMILESsnamep1M_PCDTBT"
[325] "SMILESsnamep1M_PCDTBX"
[326] "SMILESsnamep1M_PCDTDPP"
[327] "SMILESsnamep1M_PCDTPT"
[328] "SMILESsnamep1M_PCDTPX"
[329] "SMILESsnamep1M_PCDTQx"
[330] "SMILESsnamep1M_PCDTTPP"
[331] "SMILESsnamep1M_PCPDTBT"
[332] "SMILESsnamep1M_PCPTDO"
[333] "SMILESsnamep1M_PCTDPP"
[334] "SMILESsnamep1M_PCV"
[335] "SMILESsnamep1M_PCVT"
[336] "SMILESsnamep1M_PCVTT"
[337] "SMILESsnamep1M_PCVTTTT"
[338] "SMILESsnamep1M_PCz"
[339] "SMILESsnamep1M_PDPP2FTC12"
[340] "SMILESsnamep1M_PDPP2FTC14"
[341] "SMILESsnamep1M_PDPP2FTC16"
[342] "SMILESsnamep1M_PDPP2T"
[343] "SMILESsnamep1M_PDPP2TBP"
[344] "SMILESsnamep1M_PDPP3T"
[345] "SMILESsnamep1M_PDPP3TaltTPT"
[346] "SMILESsnamep1M_PDPPBBT"
[347] "SMILESsnamep1M_PDPPBT"
[348] "SMILESsnamep1M_PDPPTPT"
[349] "SMILESsnamep1M_PDPPTVT"
[350] "SMILESsnamep1M_PDTPDTDPP"
[351] "SMILESsnamep1M_PDTPDTDPPBu"
[352] "SMILESsnamep1M_PDTST"
[353] "SMILESsnamep1M_PDTSTPD"
[354] "SMILESsnamep1M_PEN"
[355] "SMILESsnamep1M_PFBTBDT"
[356] "SMILESsnamep1M_PFDTBT"
[357] "SMILESsnamep1M_PFDTDPP"
[358] "SMILESsnamep1M_PGFDTBT"
[359] "SMILESsnamep1M_PGFDTDPPC4S25"
[360] "SMILESsnamep1M_PGFDTDPPC8"
[361] "SMILESsnamep1M_PICDTBT"
[362] "SMILESsnamep1M_PIDTTFBSe"
[363] "SMILESsnamep1M_PNNT12DT"
[364] "SMILESsnamep1M_PNNT12HD"
[365] "SMILESsnamep1M_PNNTDT"
[366] "SMILESsnamep1M_PNOz4T"
[367] "SMILESsnamep1M_PNT4T2OD"
[368] "SMILESsnamep1M_PNTz4T"
[369] "SMILESsnamep1M_PNTz4TF2"
[370] "SMILESsnamep1M_PNTz4TF4"
[371] "SMILESsnamep1M_PPDT2FBT"
[372] "SMILESsnamep1M_PPDTBT"
[373] "SMILESsnamep1M_PPDTFBT"
[374] "SMILESsnamep1M_PQT12"
[375] "SMILESsnamep1M_PSBTBT"
[376] "SMILESsnamep1M_PSEHTT"
[377] "SMILESsnamep1M_PTB1"
[378] "SMILESsnamep1M_PTB2"
[379] "SMILESsnamep1M_PTB3"
[380] "SMILESsnamep1M_PTB4"
[381] "SMILESsnamep1M_PTB5"
[382] "SMILESsnamep1M_PTB6"
[383] "SMILESsnamep1M_PTB7"
[384] "SMILESsnamep1M_PTB7Th"
[385] "SMILESsnamep1M_PTBDTDTBT"
[386] "SMILESsnamep1M_PTBDTffDTBT"
[387] "SMILESsnamep1M_PTBF0"
[388] "SMILESsnamep1M_PTBF1"
[389] "SMILESsnamep1M_PTBF2"
[390] "SMILESsnamep1M_PTBF3"
[391] "SMILESsnamep1M_PTBFTDTBT"
[392] "SMILESsnamep1M_PTBI2T"
[393] "SMILESsnamep1M_PTBI2TR"
[394] "SMILESsnamep1M_PTBI2Tz"
[395] "SMILESsnamep1M_PTBITT"
[396] "SMILESsnamep1M_PTzBT10HD"
[397] "SMILESsnamep1M_PTzBT10OD"
[398] "SMILESsnamep1M_PTzBT12HD"
[399] "SMILESsnamep1M_PTzBT12OD"
[400] "SMILESsnamep1M_PTzBT14HD"
[401] "SMILESsnamep1M_PTzBT14OD"
[402] "SMILESsnamep1M_PTzBTBOBO"
[403] "SMILESsnamep1M_PTzBTBOHD"
[404] "SMILESsnamep1M_PTzBTBOOD"
[405] "SMILESsnamep1M_PTzBTEHHD"
[406] "SMILESsnamep1M_PTzBTEHOD"
[407] "SMILESsnamep1M_PTzBTHD"
[408] "SMILESsnamep1M_PTzQT14"
[409] "SMILESsnamep1M_PeNPz2T"
[410] "SMILESsnamep1M_PeNPz3T"
[411] "SMILESsnamep1M_PeNPz4T"
[412] "SMILESsnamep1M_PffBT4T2OD"
[413] "SMILESsnamep1M_PhBADT"
[414] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2.thienyl..1.2.5.oxadiazolo.3.4d.pyridazine.P1"
[415] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.2.3dioctylpyrazino.2.3d.pyridazine.P2"
[416] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.pyrazino.2.3d.pyridazine.P3"
[417] "SMILESsnamep1M_RanPBDPPT"
[418] "SMILESsnamep1M_RegPBDPPT"
[419] "SMILESsnamep1M_TDPPBBT"
[420] "SMILESsnamep1M_TPDBr16"
[421] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP1"
[422] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP2"
[423] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP3"
[424] "SMILESsnamep1M_TzTzBTIDG"
[425] "SMILESsnamep1M_TzTzalkylthiopheneBTIDG"
[426] "SMILESsnamep1M_VacdepoBPc"
[427] "SMILESsnamep1M_fBPC60"
[428] "SMILESsnamep1M_pBTTT"
[429] "SMILESsnamep1M_rBPC60"
[430] "SMILESsnamep1M_ranPDPPTPDalt2T"
[431] "SMILESsnamep1M_regPDPPTPDalt2T"
[432] "SMILESsnamep1M_thieno.3.2b.thiopheneP2"
[433] "SMILESsnamep2M_PBDTTFTTE"
[434] "Observed"
[435] "Predicted"
[436] "AbsError"
[437] "is_S"
<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/high_error_Samples_PCEmax.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/all_with_Sflag_PCEmax.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/obs_vs_pred_PCEmax.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/summary_S_numeric_PCEmax.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/summary_nonS_numeric_PCEmax.csv

============================================
Target: Jsc
 model_name  : gprLinear
 dataset_tag : m_all_OH
 folder_name : Jsc
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Jsc/m_all_OH_rebuilt_Jsc_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Jsc/m_all_OH_rebuilt_Jsc_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc

>> oof_err cols:
[1] "SampleID"           "foldID"             "Observed"
[4] "Predicted"          "Error"              "AbsError"
[7] "Type"               "HighErrorFlag"      "HighErrorThreshold"
>> feat cols:
  [1] "SampleID"
  [2] "foldID"
  [3] "Error"
  [4] "Type"
  [5] "HighErrorFlag"
  [6] "HighErrorThreshold"
  [7] "THFSVAafetrN"
  [8] "THFSVAafetrI"
  [9] "Aarea"
 [10] "Aonsetp1Mfilm"
 [11] "Abandp1Mfilm1"
 [12] "Abandp1Mfilm2"
 [13] "Abandp1Mfilm3"
 [14] "Aonsetp1MSol"
 [15] "Abandp1MSol1"
 [16] "Abandp1MSol2"
 [17] "Abandp1MSol3"
 [18] "AfAeThin"
 [19] "ALthickness"
 [20] "amountAditive"
 [21] "amountsolutionI"
 [22] "cycle"
 [23] "E12oxp1M"
 [24] "E12redp1M"
 [25] "EgDFTp1M"
 [26] "EgECnM"
 [27] "EgECp1M"
 [28] "EgoptnM"
 [29] "Egoptp1M"
 [30] "FWHMThin"
 [31] "HOMODFTp1M"
 [32] "HOMOECp1M"
 [33] "HOMOp1M"
 [34] "Lay2SCspeed"
 [35] "Lay2SCtime"
 [36] "Lay2TAtemp"
 [37] "Lay2TAtime"
 [38] "Lay2thickness"
 [39] "Lay5thickness"
 [40] "Lay6DPpreTorr"
 [41] "Lay6thickness"
 [42] "LUMOECp1M"
 [43] "LUMOnM"
 [44] "LUMOp1M"
 [45] "measureINT"
 [46] "Mmonomerp1M"
 [47] "MnkDanM"
 [48] "MnkDap1M"
 [49] "MnMp1M"
 [50] "MPDnp1M"
 [51] "MwkDap1M"
 [52] "NLthickness"
 [53] "PDInM"
 [54] "PDIp1M"
 [55] "PLthickness"
 [56] "RatioinM"
 [57] "Ratioip1M"
 [58] "Ratioip2M"
 [59] "RationM"
 [60] "Ratiop1M"
 [61] "Ratiop2M"
 [62] "SCspeed1"
 [63] "SCtime1"
 [64] "solution"
 [65] "solutionI"
 [66] "solutionN"
 [67] "solutionP"
 [68] "solutionPI"
 [69] "solutionPN"
 [70] "T5dp1M"
 [71] "TAtemp1"
 [72] "TAtime1"
 [73] "TAtimelast"
 [74] "TD1temp"
 [75] "TD2temp"
 [76] "TDtime"
 [77] "UVIntP"
 [78] "UVtimeP"
 [79] "VolRatioS1"
 [80] "Lay2Mname_"
 [81] "Lay2Mname_PEDOTPSS"
 [82] "Lay2Mname_ZnO"
 [83] "Lay2Mname_ZnOC60"
 [84] "Lay5electronodes1_"
 [85] "Lay5electronodes1_Al"
 [86] "Lay5electronodes1_BCP"
 [87] "Lay5electronodes1_C60bis"
 [88] "Lay5electronodes1_Ca"
 [89] "Lay5electronodes1_ETL.1"
 [90] "Lay5electronodes1_Li"
 [91] "Lay5electronodes1_LiF"
 [92] "Lay5electronodes1_Mg"
 [93] "Lay5electronodes1_MoO3"
 [94] "Lay5electronodes1_MoO3orV2O5"
 [95] "Lay5electronodes1_MoOx"
 [96] "Lay5electronodes1_TiOx"
 [97] "Lay6electronodes2_"
 [98] "Lay6electronodes2_Ag"
 [99] "Lay6electronodes2_Al"
[100] "Additivesname_"
[101] "Additivesname_1.8dibromoooctane"
[102] "Additivesname_1.8dicholorooctane"
[103] "Additivesname_1.8dicyanooctane"
[104] "Additivesname_1.8octanediacetate"
[105] "Additivesname_1.8octanedithiol"
[106] "Additivesname_1CN"
[107] "Additivesname_CS2"
[108] "Additivesname_DCB"
[109] "Additivesname_DIO"
[110] "Additivesname_DPE"
[111] "namessolvent1_"
[112] "namessolvent1_CB"
[113] "namessolvent1_CF"
[114] "namessolvent1_DCM"
[115] "namessolvent1_TCB"
[116] "namessolvent1_THF"
[117] "namessolvent1_oDCB"
[118] "namessolvent2_"
[119] "namessolvent2_CB"
[120] "namessolvent2_CF"
[121] "namessolvent2_DIO"
[122] "namessolvent2_oDCB"
[123] "SMILESsnameinM_PC61BM"
[124] "SMILESsnameinM_PC71BM"
[125] "SMILESsnameip1M_AtD"
[126] "SMILESsnameip1M_BP"
[127] "SMILESsnameip1M_BP.C60"
[128] "SMILESsnameip1M_Bu.BP.C60"
[129] "SMILESsnameip1M_C4DBTA"
[130] "SMILESsnameip1M_C6DBTA"
[131] "SMILESsnameip1M_C8DBTA"
[132] "SMILESsnameip1M_DTA"
[133] "SMILESsnameip1M_EBDBTA"
[134] "SMILESsnameip1M_EH.DBTA"
[135] "SMILESsnameip1M_f.BP.C60"
[136] "SMILESsnameip1M_r.BP.C60"
[137] "SMILESsnameip2M_BP"
[138] "SMILESsnamenM_C60"
[139] "SMILESsnamenM_DBFIEDOT"
[140] "SMILESsnamenM_DPc.T"
[141] "SMILESsnamenM_DPc.mP"
[142] "SMILESsnamenM_ICEM"
[143] "SMILESsnamenM_ICMA"
[144] "SMILESsnamenM_ICMM"
[145] "SMILESsnamenM_MOPFP"
[146] "SMILESsnamenM_NC70BA"
[147] "SMILESsnamenM_NCMA"
[148] "SMILESsnamenM_NCMM"
[149] "SMILESsnamenM_PC61BM"
[150] "SMILESsnamenM_PC71BM"
[151] "SMILESsnamenM_PCBM"
[152] "SMILESsnamenM_PFP"
[153] "SMILESsnamenM_PNDTI.BT"
[154] "SMILESsnamenM_PNDTI.DTT"
[155] "SMILESsnamenM_PNDTI.T"
[156] "SMILESsnamenM_PNDTI.TT"
[157] "SMILESsnamenM_PTBI2T"
[158] "SMILESsnamenM_PTBI2TR"
[159] "SMILESsnamenM_PTBI2Tz"
[160] "SMILESsnamenM_PTBITT"
[161] "SMILESsnamenM_TC61BM"
[162] "SMILESsnamenM_TC61PM"
[163] "SMILESsnamenM_TFP"
[164] "SMILESsnamenM_THPc"
[165] "SMILESsnamep1M_2.2..bithiopheneP1"
[166] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP3"
[167] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP4"
[168] "SMILESsnamep1M_9triarylamino9HcarbazoleP3"
[169] "SMILESsnamep1M_ADT"
[170] "SMILESsnamep1M_AtD"
[171] "SMILESsnamep1M_BBTzBTIDG"
[172] "SMILESsnamep1M_BBTzalkylthiopheneBTIDG"
[173] "SMILESsnamep1M_BDTC6"
[174] "SMILESsnamep1M_BDTDTKP"
[175] "SMILESsnamep1M_BDTH1"
[176] "SMILESsnamep1M_BDTH11"
[177] "SMILESsnamep1M_BDTH3"
[178] "SMILESsnamep1M_BDTH6"
[179] "SMILESsnamep1M_BDTH7"
[180] "SMILESsnamep1M_BDTH8"
[181] "SMILESsnamep1M_BDTH9"
[182] "SMILESsnamep1M_BDTT6"
[183] "SMILESsnamep1M_BP"
[184] "SMILESsnamep1M_BPC60"
[185] "SMILESsnamep1M_BPc"
[186] "SMILESsnamep1M_BPcpre1"
[187] "SMILESsnamep1M_BPcpre2"
[188] "SMILESsnamep1M_BTAnt"
[189] "SMILESsnamep1M_BTIBDTP2"
[190] "SMILESsnamep1M_BuBPC60"
[191] "SMILESsnamep1M_C10DPPBP"
[192] "SMILESsnamep1M_C2DPPBP"
[193] "SMILESsnamep1M_C3DPPTTSe"
[194] "SMILESsnamep1M_C3DPPTTT"
[195] "SMILESsnamep1M_C3DPPTTTe"
[196] "SMILESsnamep1M_C4DPPBP"
[197] "SMILESsnamep1M_C6DPPBP"
[198] "SMILESsnamep1M_C8DPPBP"
[199] "SMILESsnamep1M_CPDTDTKP"
[200] "SMILESsnamep1M_DTA"
[201] "SMILESsnamep1M_DTAnt"
[202] "SMILESsnamep1M_DTBT"
[203] "SMILESsnamep1M_DTPDPP2TBDT"
[204] "SMILESsnamep1M_DTPDPP2TDBT"
[205] "SMILESsnamep1M_DTPDPP2TTT"
[206] "SMILESsnamep1M_DTPDPP3T"
[207] "SMILESsnamep1M_DTPDPP4T"
[208] "SMILESsnamep1M_DTPDPPTPT"
[209] "SMILESsnamep1M_DTSC4"
[210] "SMILESsnamep1M_DTSC6"
[211] "SMILESsnamep1M_DTSC6L"
[212] "SMILESsnamep1M_DTSC8"
[213] "SMILESsnamep1M_DTSCEH"
[214] "SMILESsnamep1M_DTSCh"
[215] "SMILESsnamep1M_DTSChy"
[216] "SMILESsnamep1M_DTSDC"
[217] "SMILESsnamep1M_DTST6"
[218] "SMILESsnamep1M_DTSTCh"
[219] "SMILESsnamep1M_DTSTChy"
[220] "SMILESsnamep1M_DTTPTP1"
[221] "SMILESsnamep1M_DTTPTP2"
[222] "SMILESsnamep1M_DTTPTP3"
[223] "SMILESsnamep1M_DTTPTP4"
[224] "SMILESsnamep1M_DTTPTP5"
[225] "SMILESsnamep1M_DTTPTP6"
[226] "SMILESsnamep1M_DTfBT"
[227] "SMILESsnamep1M_DTffBT"
[228] "SMILESsnamep1M_EHDBTA"
[229] "SMILESsnamep1M_F0F0"
[230] "SMILESsnamep1M_F0F2"
[231] "SMILESsnamep1M_F1PDPP2TBP"
[232] "SMILESsnamep1M_F2F0"
[233] "SMILESsnamep1M_F2F2"
[234] "SMILESsnamep1M_F2PDPP2TBP"
[235] "SMILESsnamep1M_FLODTKP"
[236] "SMILESsnamep1M_P.BDTFBT."
[237] "SMILESsnamep1M_P.BDTTBT."
[238] "SMILESsnamep1M_P.BDTTTBO."
[239] "SMILESsnamep1M_P.BDTTTBT."
[240] "SMILESsnamep1M_P.BDTTTFBT."
[241] "SMILESsnamep1M_P.BDTTTHBT."
[242] "SMILESsnamep1M_P.T32EHiI."
[243] "SMILESsnamep1M_P.T3C10iI."
[244] "SMILESsnamep1M_P.T3C12iI."
[245] "SMILESsnamep1M_P.T3C6iI."
[246] "SMILESsnamep1M_P.T3C8iI."
[247] "SMILESsnamep1M_P3HNT"
[248] "SMILESsnamep1M_P3HT"
[249] "SMILESsnamep1M_P4TBT"
[250] "SMILESsnamep1M_P4TDPP"
[251] "SMILESsnamep1M_P4TDTBT"
[252] "SMILESsnamep1M_P4TPDTQ"
[253] "SMILESsnamep1M_PBDFDODTBT"
[254] "SMILESsnamep1M_PBDFDTBO"
[255] "SMILESsnamep1M_PBDFDTBT"
[256] "SMILESsnamep1M_PBDFDTBTz"
[257] "SMILESsnamep1M_PBDFFBT"
[258] "SMILESsnamep1M_PBDT.DTBSe"
[259] "SMILESsnamep1M_PBDT.DTBT"
[260] "SMILESsnamep1M_PBDTBDD"
[261] "SMILESsnamep1M_PBDTBO"
[262] "SMILESsnamep1M_PBDTBT"
[263] "SMILESsnamep1M_PBDTBTz"
[264] "SMILESsnamep1M_PBDTDPT1"
[265] "SMILESsnamep1M_PBDTDPT2"
[266] "SMILESsnamep1M_PBDTDTBTm"
[267] "SMILESsnamep1M_PBDTDTBTo"
[268] "SMILESsnamep1M_PBDTDTBTp"
[269] "SMILESsnamep1M_PBDTDTBTz"
[270] "SMILESsnamep1M_PBDTDTTTST"
[271] "SMILESsnamep1M_PBDTFBO"
[272] "SMILESsnamep1M_PBDTFBT"
[273] "SMILESsnamep1M_PBDTFQT"
[274] "SMILESsnamep1M_PBDTFQTT"
[275] "SMILESsnamep1M_PBDTHDODTHBTffP3"
[276] "SMILESsnamep1M_PBDTPBO"
[277] "SMILESsnamep1M_PBDTPDTBT"
[278] "SMILESsnamep1M_PBDTPODTBO"
[279] "SMILESsnamep1M_PBDTPODTBT"
[280] "SMILESsnamep1M_PBDTPOFBT"
[281] "SMILESsnamep1M_PBDTT10TPD"
[282] "SMILESsnamep1M_PBDTT12TPD"
[283] "SMILESsnamep1M_PBDTT8TPD"
[284] "SMILESsnamep1M_PBDTTBO"
[285] "SMILESsnamep1M_PBDTTBT"
[286] "SMILESsnamep1M_PBDTTDPP"
[287] "SMILESsnamep1M_PBDTTDTBO"
[288] "SMILESsnamep1M_PBDTTDTBT"
[289] "SMILESsnamep1M_PBDTTDTBTz"
[290] "SMILESsnamep1M_PBDTTDTTBT"
[291] "SMILESsnamep1M_PBDTTEHDTEHBTffP2"
[292] "SMILESsnamep1M_PBDTTEHDTHBTffP1"
[293] "SMILESsnamep1M_PBDTTFBSe"
[294] "SMILESsnamep1M_PBDTTFDPP"
[295] "SMILESsnamep1M_PBDTTFTTE"
[296] "SMILESsnamep1M_PBDTTPD"
[297] "SMILESsnamep1M_PBDTTPDP1"
[298] "SMILESsnamep1M_PBDTTPDP2"
[299] "SMILESsnamep1M_PBDTTPDP3"
[300] "SMILESsnamep1M_PBDTTS1"
[301] "SMILESsnamep1M_PBDTTS2"
[302] "SMILESsnamep1M_PBDTTS3"
[303] "SMILESsnamep1M_PBDTTSeDPP"
[304] "SMILESsnamep1M_PBDTTTBT"
[305] "SMILESsnamep1M_PBDTTTC"
[306] "SMILESsnamep1M_PBDTTTCF"
[307] "SMILESsnamep1M_PBDTTTE"
[308] "SMILESsnamep1M_PBDTTTS"
[309] "SMILESsnamep1M_PBDTTTST"
[310] "SMILESsnamep1M_PBPT12"
[311] "SMILESsnamep1M_PBQ1"
[312] "SMILESsnamep1M_PBQ2"
[313] "SMILESsnamep1M_PBQ3"
[314] "SMILESsnamep1M_PBQ4"
[315] "SMILESsnamep1M_PBT0F"
[316] "SMILESsnamep1M_PBT1F"
[317] "SMILESsnamep1M_PBT2F"
[318] "SMILESsnamep1M_PBT3F"
[319] "SMILESsnamep1M_PBTPyDPP"
[320] "SMILESsnamep1M_PBTff4T2OD"
[321] "SMILESsnamep1M_PBnDTFTAZ"
[322] "SMILESsnamep1M_PBnDTHTAZ"
[323] "SMILESsnamep1M_PCBTDPP"
[324] "SMILESsnamep1M_PCDTBT"
[325] "SMILESsnamep1M_PCDTBX"
[326] "SMILESsnamep1M_PCDTDPP"
[327] "SMILESsnamep1M_PCDTPT"
[328] "SMILESsnamep1M_PCDTPX"
[329] "SMILESsnamep1M_PCDTQx"
[330] "SMILESsnamep1M_PCDTTPP"
[331] "SMILESsnamep1M_PCPDTBT"
[332] "SMILESsnamep1M_PCPTDO"
[333] "SMILESsnamep1M_PCTDPP"
[334] "SMILESsnamep1M_PCV"
[335] "SMILESsnamep1M_PCVT"
[336] "SMILESsnamep1M_PCVTT"
[337] "SMILESsnamep1M_PCVTTTT"
[338] "SMILESsnamep1M_PCz"
[339] "SMILESsnamep1M_PDPP2FTC12"
[340] "SMILESsnamep1M_PDPP2FTC14"
[341] "SMILESsnamep1M_PDPP2FTC16"
[342] "SMILESsnamep1M_PDPP2T"
[343] "SMILESsnamep1M_PDPP2TBP"
[344] "SMILESsnamep1M_PDPP3T"
[345] "SMILESsnamep1M_PDPP3TaltTPT"
[346] "SMILESsnamep1M_PDPPBBT"
[347] "SMILESsnamep1M_PDPPBT"
[348] "SMILESsnamep1M_PDPPTPT"
[349] "SMILESsnamep1M_PDPPTVT"
[350] "SMILESsnamep1M_PDTPDTDPP"
[351] "SMILESsnamep1M_PDTPDTDPPBu"
[352] "SMILESsnamep1M_PDTST"
[353] "SMILESsnamep1M_PDTSTPD"
[354] "SMILESsnamep1M_PEN"
[355] "SMILESsnamep1M_PFBTBDT"
[356] "SMILESsnamep1M_PFDTBT"
[357] "SMILESsnamep1M_PFDTDPP"
[358] "SMILESsnamep1M_PGFDTBT"
[359] "SMILESsnamep1M_PGFDTDPPC4S25"
[360] "SMILESsnamep1M_PGFDTDPPC8"
[361] "SMILESsnamep1M_PICDTBT"
[362] "SMILESsnamep1M_PIDTTFBSe"
[363] "SMILESsnamep1M_PNNT12DT"
[364] "SMILESsnamep1M_PNNT12HD"
[365] "SMILESsnamep1M_PNNTDT"
[366] "SMILESsnamep1M_PNOz4T"
[367] "SMILESsnamep1M_PNT4T2OD"
[368] "SMILESsnamep1M_PNTz4T"
[369] "SMILESsnamep1M_PNTz4TF2"
[370] "SMILESsnamep1M_PNTz4TF4"
[371] "SMILESsnamep1M_PPDT2FBT"
[372] "SMILESsnamep1M_PPDTBT"
[373] "SMILESsnamep1M_PPDTFBT"
[374] "SMILESsnamep1M_PQT12"
[375] "SMILESsnamep1M_PSBTBT"
[376] "SMILESsnamep1M_PSEHTT"
[377] "SMILESsnamep1M_PTB1"
[378] "SMILESsnamep1M_PTB2"
[379] "SMILESsnamep1M_PTB3"
[380] "SMILESsnamep1M_PTB4"
[381] "SMILESsnamep1M_PTB5"
[382] "SMILESsnamep1M_PTB6"
[383] "SMILESsnamep1M_PTB7"
[384] "SMILESsnamep1M_PTB7Th"
[385] "SMILESsnamep1M_PTBDTDTBT"
[386] "SMILESsnamep1M_PTBDTffDTBT"
[387] "SMILESsnamep1M_PTBF0"
[388] "SMILESsnamep1M_PTBF1"
[389] "SMILESsnamep1M_PTBF2"
[390] "SMILESsnamep1M_PTBF3"
[391] "SMILESsnamep1M_PTBFTDTBT"
[392] "SMILESsnamep1M_PTBI2T"
[393] "SMILESsnamep1M_PTBI2TR"
[394] "SMILESsnamep1M_PTBI2Tz"
[395] "SMILESsnamep1M_PTBITT"
[396] "SMILESsnamep1M_PTzBT10HD"
[397] "SMILESsnamep1M_PTzBT10OD"
[398] "SMILESsnamep1M_PTzBT12HD"
[399] "SMILESsnamep1M_PTzBT12OD"
[400] "SMILESsnamep1M_PTzBT14HD"
[401] "SMILESsnamep1M_PTzBT14OD"
[402] "SMILESsnamep1M_PTzBTBOBO"
[403] "SMILESsnamep1M_PTzBTBOHD"
[404] "SMILESsnamep1M_PTzBTBOOD"
[405] "SMILESsnamep1M_PTzBTEHHD"
[406] "SMILESsnamep1M_PTzBTEHOD"
[407] "SMILESsnamep1M_PTzBTHD"
[408] "SMILESsnamep1M_PTzQT14"
[409] "SMILESsnamep1M_PeNPz2T"
[410] "SMILESsnamep1M_PeNPz3T"
[411] "SMILESsnamep1M_PeNPz4T"
[412] "SMILESsnamep1M_PffBT4T2OD"
[413] "SMILESsnamep1M_PhBADT"
[414] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2.thienyl..1.2.5.oxadiazolo.3.4d.pyridazine.P1"
[415] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.2.3dioctylpyrazino.2.3d.pyridazine.P2"
[416] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.pyrazino.2.3d.pyridazine.P3"
[417] "SMILESsnamep1M_RanPBDPPT"
[418] "SMILESsnamep1M_RegPBDPPT"
[419] "SMILESsnamep1M_TDPPBBT"
[420] "SMILESsnamep1M_TPDBr16"
[421] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP1"
[422] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP2"
[423] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP3"
[424] "SMILESsnamep1M_TzTzBTIDG"
[425] "SMILESsnamep1M_TzTzalkylthiopheneBTIDG"
[426] "SMILESsnamep1M_VacdepoBPc"
[427] "SMILESsnamep1M_fBPC60"
[428] "SMILESsnamep1M_pBTTT"
[429] "SMILESsnamep1M_rBPC60"
[430] "SMILESsnamep1M_ranPDPPTPDalt2T"
[431] "SMILESsnamep1M_regPDPPTPDalt2T"
[432] "SMILESsnamep1M_thieno.3.2b.thiopheneP2"
[433] "SMILESsnamep2M_PBDTTFTTE"
<U+8AA4><U+5DEE> (AbsError) summary:
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
 0.009943  0.637469  1.366075  1.792551  2.429419 11.000708

top_k <U+30E2><U+30FC><U+30C9>: <U+4E0A><U+4F4D> 10 <U+4EF6><U+76EE><U+306E> abs_error = 7.726259 <U+3092><U+95BE><U+5024><U+5019><U+88DC><U+3068><U+3057><U+307E><U+3059><U+3002>
abs_error_thr <U+672A><U+6307><U+5B9A><U+306E><U+305F><U+3081><U+3001>top_k <U+306B><U+7531><U+6765><U+3059><U+308B> 7.726259 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 7.726259

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 10 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1]  7.726259 11.000708

>> dat_all cols:
  [1] "SampleID"
  [2] "foldID"
  [3] "Error"
  [4] "Type"
  [5] "HighErrorFlag"
  [6] "HighErrorThreshold"
  [7] "THFSVAafetrN"
  [8] "THFSVAafetrI"
  [9] "Aarea"
 [10] "Aonsetp1Mfilm"
 [11] "Abandp1Mfilm1"
 [12] "Abandp1Mfilm2"
 [13] "Abandp1Mfilm3"
 [14] "Aonsetp1MSol"
 [15] "Abandp1MSol1"
 [16] "Abandp1MSol2"
 [17] "Abandp1MSol3"
 [18] "AfAeThin"
 [19] "ALthickness"
 [20] "amountAditive"
 [21] "amountsolutionI"
 [22] "cycle"
 [23] "E12oxp1M"
 [24] "E12redp1M"
 [25] "EgDFTp1M"
 [26] "EgECnM"
 [27] "EgECp1M"
 [28] "EgoptnM"
 [29] "Egoptp1M"
 [30] "FWHMThin"
 [31] "HOMODFTp1M"
 [32] "HOMOECp1M"
 [33] "HOMOp1M"
 [34] "Lay2SCspeed"
 [35] "Lay2SCtime"
 [36] "Lay2TAtemp"
 [37] "Lay2TAtime"
 [38] "Lay2thickness"
 [39] "Lay5thickness"
 [40] "Lay6DPpreTorr"
 [41] "Lay6thickness"
 [42] "LUMOECp1M"
 [43] "LUMOnM"
 [44] "LUMOp1M"
 [45] "measureINT"
 [46] "Mmonomerp1M"
 [47] "MnkDanM"
 [48] "MnkDap1M"
 [49] "MnMp1M"
 [50] "MPDnp1M"
 [51] "MwkDap1M"
 [52] "NLthickness"
 [53] "PDInM"
 [54] "PDIp1M"
 [55] "PLthickness"
 [56] "RatioinM"
 [57] "Ratioip1M"
 [58] "Ratioip2M"
 [59] "RationM"
 [60] "Ratiop1M"
 [61] "Ratiop2M"
 [62] "SCspeed1"
 [63] "SCtime1"
 [64] "solution"
 [65] "solutionI"
 [66] "solutionN"
 [67] "solutionP"
 [68] "solutionPI"
 [69] "solutionPN"
 [70] "T5dp1M"
 [71] "TAtemp1"
 [72] "TAtime1"
 [73] "TAtimelast"
 [74] "TD1temp"
 [75] "TD2temp"
 [76] "TDtime"
 [77] "UVIntP"
 [78] "UVtimeP"
 [79] "VolRatioS1"
 [80] "Lay2Mname_"
 [81] "Lay2Mname_PEDOTPSS"
 [82] "Lay2Mname_ZnO"
 [83] "Lay2Mname_ZnOC60"
 [84] "Lay5electronodes1_"
 [85] "Lay5electronodes1_Al"
 [86] "Lay5electronodes1_BCP"
 [87] "Lay5electronodes1_C60bis"
 [88] "Lay5electronodes1_Ca"
 [89] "Lay5electronodes1_ETL.1"
 [90] "Lay5electronodes1_Li"
 [91] "Lay5electronodes1_LiF"
 [92] "Lay5electronodes1_Mg"
 [93] "Lay5electronodes1_MoO3"
 [94] "Lay5electronodes1_MoO3orV2O5"
 [95] "Lay5electronodes1_MoOx"
 [96] "Lay5electronodes1_TiOx"
 [97] "Lay6electronodes2_"
 [98] "Lay6electronodes2_Ag"
 [99] "Lay6electronodes2_Al"
[100] "Additivesname_"
[101] "Additivesname_1.8dibromoooctane"
[102] "Additivesname_1.8dicholorooctane"
[103] "Additivesname_1.8dicyanooctane"
[104] "Additivesname_1.8octanediacetate"
[105] "Additivesname_1.8octanedithiol"
[106] "Additivesname_1CN"
[107] "Additivesname_CS2"
[108] "Additivesname_DCB"
[109] "Additivesname_DIO"
[110] "Additivesname_DPE"
[111] "namessolvent1_"
[112] "namessolvent1_CB"
[113] "namessolvent1_CF"
[114] "namessolvent1_DCM"
[115] "namessolvent1_TCB"
[116] "namessolvent1_THF"
[117] "namessolvent1_oDCB"
[118] "namessolvent2_"
[119] "namessolvent2_CB"
[120] "namessolvent2_CF"
[121] "namessolvent2_DIO"
[122] "namessolvent2_oDCB"
[123] "SMILESsnameinM_PC61BM"
[124] "SMILESsnameinM_PC71BM"
[125] "SMILESsnameip1M_AtD"
[126] "SMILESsnameip1M_BP"
[127] "SMILESsnameip1M_BP.C60"
[128] "SMILESsnameip1M_Bu.BP.C60"
[129] "SMILESsnameip1M_C4DBTA"
[130] "SMILESsnameip1M_C6DBTA"
[131] "SMILESsnameip1M_C8DBTA"
[132] "SMILESsnameip1M_DTA"
[133] "SMILESsnameip1M_EBDBTA"
[134] "SMILESsnameip1M_EH.DBTA"
[135] "SMILESsnameip1M_f.BP.C60"
[136] "SMILESsnameip1M_r.BP.C60"
[137] "SMILESsnameip2M_BP"
[138] "SMILESsnamenM_C60"
[139] "SMILESsnamenM_DBFIEDOT"
[140] "SMILESsnamenM_DPc.T"
[141] "SMILESsnamenM_DPc.mP"
[142] "SMILESsnamenM_ICEM"
[143] "SMILESsnamenM_ICMA"
[144] "SMILESsnamenM_ICMM"
[145] "SMILESsnamenM_MOPFP"
[146] "SMILESsnamenM_NC70BA"
[147] "SMILESsnamenM_NCMA"
[148] "SMILESsnamenM_NCMM"
[149] "SMILESsnamenM_PC61BM"
[150] "SMILESsnamenM_PC71BM"
[151] "SMILESsnamenM_PCBM"
[152] "SMILESsnamenM_PFP"
[153] "SMILESsnamenM_PNDTI.BT"
[154] "SMILESsnamenM_PNDTI.DTT"
[155] "SMILESsnamenM_PNDTI.T"
[156] "SMILESsnamenM_PNDTI.TT"
[157] "SMILESsnamenM_PTBI2T"
[158] "SMILESsnamenM_PTBI2TR"
[159] "SMILESsnamenM_PTBI2Tz"
[160] "SMILESsnamenM_PTBITT"
[161] "SMILESsnamenM_TC61BM"
[162] "SMILESsnamenM_TC61PM"
[163] "SMILESsnamenM_TFP"
[164] "SMILESsnamenM_THPc"
[165] "SMILESsnamep1M_2.2..bithiopheneP1"
[166] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP3"
[167] "SMILESsnamep1M_3hexylthieno.3.2b.thiopheneP4"
[168] "SMILESsnamep1M_9triarylamino9HcarbazoleP3"
[169] "SMILESsnamep1M_ADT"
[170] "SMILESsnamep1M_AtD"
[171] "SMILESsnamep1M_BBTzBTIDG"
[172] "SMILESsnamep1M_BBTzalkylthiopheneBTIDG"
[173] "SMILESsnamep1M_BDTC6"
[174] "SMILESsnamep1M_BDTDTKP"
[175] "SMILESsnamep1M_BDTH1"
[176] "SMILESsnamep1M_BDTH11"
[177] "SMILESsnamep1M_BDTH3"
[178] "SMILESsnamep1M_BDTH6"
[179] "SMILESsnamep1M_BDTH7"
[180] "SMILESsnamep1M_BDTH8"
[181] "SMILESsnamep1M_BDTH9"
[182] "SMILESsnamep1M_BDTT6"
[183] "SMILESsnamep1M_BP"
[184] "SMILESsnamep1M_BPC60"
[185] "SMILESsnamep1M_BPc"
[186] "SMILESsnamep1M_BPcpre1"
[187] "SMILESsnamep1M_BPcpre2"
[188] "SMILESsnamep1M_BTAnt"
[189] "SMILESsnamep1M_BTIBDTP2"
[190] "SMILESsnamep1M_BuBPC60"
[191] "SMILESsnamep1M_C10DPPBP"
[192] "SMILESsnamep1M_C2DPPBP"
[193] "SMILESsnamep1M_C3DPPTTSe"
[194] "SMILESsnamep1M_C3DPPTTT"
[195] "SMILESsnamep1M_C3DPPTTTe"
[196] "SMILESsnamep1M_C4DPPBP"
[197] "SMILESsnamep1M_C6DPPBP"
[198] "SMILESsnamep1M_C8DPPBP"
[199] "SMILESsnamep1M_CPDTDTKP"
[200] "SMILESsnamep1M_DTA"
[201] "SMILESsnamep1M_DTAnt"
[202] "SMILESsnamep1M_DTBT"
[203] "SMILESsnamep1M_DTPDPP2TBDT"
[204] "SMILESsnamep1M_DTPDPP2TDBT"
[205] "SMILESsnamep1M_DTPDPP2TTT"
[206] "SMILESsnamep1M_DTPDPP3T"
[207] "SMILESsnamep1M_DTPDPP4T"
[208] "SMILESsnamep1M_DTPDPPTPT"
[209] "SMILESsnamep1M_DTSC4"
[210] "SMILESsnamep1M_DTSC6"
[211] "SMILESsnamep1M_DTSC6L"
[212] "SMILESsnamep1M_DTSC8"
[213] "SMILESsnamep1M_DTSCEH"
[214] "SMILESsnamep1M_DTSCh"
[215] "SMILESsnamep1M_DTSChy"
[216] "SMILESsnamep1M_DTSDC"
[217] "SMILESsnamep1M_DTST6"
[218] "SMILESsnamep1M_DTSTCh"
[219] "SMILESsnamep1M_DTSTChy"
[220] "SMILESsnamep1M_DTTPTP1"
[221] "SMILESsnamep1M_DTTPTP2"
[222] "SMILESsnamep1M_DTTPTP3"
[223] "SMILESsnamep1M_DTTPTP4"
[224] "SMILESsnamep1M_DTTPTP5"
[225] "SMILESsnamep1M_DTTPTP6"
[226] "SMILESsnamep1M_DTfBT"
[227] "SMILESsnamep1M_DTffBT"
[228] "SMILESsnamep1M_EHDBTA"
[229] "SMILESsnamep1M_F0F0"
[230] "SMILESsnamep1M_F0F2"
[231] "SMILESsnamep1M_F1PDPP2TBP"
[232] "SMILESsnamep1M_F2F0"
[233] "SMILESsnamep1M_F2F2"
[234] "SMILESsnamep1M_F2PDPP2TBP"
[235] "SMILESsnamep1M_FLODTKP"
[236] "SMILESsnamep1M_P.BDTFBT."
[237] "SMILESsnamep1M_P.BDTTBT."
[238] "SMILESsnamep1M_P.BDTTTBO."
[239] "SMILESsnamep1M_P.BDTTTBT."
[240] "SMILESsnamep1M_P.BDTTTFBT."
[241] "SMILESsnamep1M_P.BDTTTHBT."
[242] "SMILESsnamep1M_P.T32EHiI."
[243] "SMILESsnamep1M_P.T3C10iI."
[244] "SMILESsnamep1M_P.T3C12iI."
[245] "SMILESsnamep1M_P.T3C6iI."
[246] "SMILESsnamep1M_P.T3C8iI."
[247] "SMILESsnamep1M_P3HNT"
[248] "SMILESsnamep1M_P3HT"
[249] "SMILESsnamep1M_P4TBT"
[250] "SMILESsnamep1M_P4TDPP"
[251] "SMILESsnamep1M_P4TDTBT"
[252] "SMILESsnamep1M_P4TPDTQ"
[253] "SMILESsnamep1M_PBDFDODTBT"
[254] "SMILESsnamep1M_PBDFDTBO"
[255] "SMILESsnamep1M_PBDFDTBT"
[256] "SMILESsnamep1M_PBDFDTBTz"
[257] "SMILESsnamep1M_PBDFFBT"
[258] "SMILESsnamep1M_PBDT.DTBSe"
[259] "SMILESsnamep1M_PBDT.DTBT"
[260] "SMILESsnamep1M_PBDTBDD"
[261] "SMILESsnamep1M_PBDTBO"
[262] "SMILESsnamep1M_PBDTBT"
[263] "SMILESsnamep1M_PBDTBTz"
[264] "SMILESsnamep1M_PBDTDPT1"
[265] "SMILESsnamep1M_PBDTDPT2"
[266] "SMILESsnamep1M_PBDTDTBTm"
[267] "SMILESsnamep1M_PBDTDTBTo"
[268] "SMILESsnamep1M_PBDTDTBTp"
[269] "SMILESsnamep1M_PBDTDTBTz"
[270] "SMILESsnamep1M_PBDTDTTTST"
[271] "SMILESsnamep1M_PBDTFBO"
[272] "SMILESsnamep1M_PBDTFBT"
[273] "SMILESsnamep1M_PBDTFQT"
[274] "SMILESsnamep1M_PBDTFQTT"
[275] "SMILESsnamep1M_PBDTHDODTHBTffP3"
[276] "SMILESsnamep1M_PBDTPBO"
[277] "SMILESsnamep1M_PBDTPDTBT"
[278] "SMILESsnamep1M_PBDTPODTBO"
[279] "SMILESsnamep1M_PBDTPODTBT"
[280] "SMILESsnamep1M_PBDTPOFBT"
[281] "SMILESsnamep1M_PBDTT10TPD"
[282] "SMILESsnamep1M_PBDTT12TPD"
[283] "SMILESsnamep1M_PBDTT8TPD"
[284] "SMILESsnamep1M_PBDTTBO"
[285] "SMILESsnamep1M_PBDTTBT"
[286] "SMILESsnamep1M_PBDTTDPP"
[287] "SMILESsnamep1M_PBDTTDTBO"
[288] "SMILESsnamep1M_PBDTTDTBT"
[289] "SMILESsnamep1M_PBDTTDTBTz"
[290] "SMILESsnamep1M_PBDTTDTTBT"
[291] "SMILESsnamep1M_PBDTTEHDTEHBTffP2"
[292] "SMILESsnamep1M_PBDTTEHDTHBTffP1"
[293] "SMILESsnamep1M_PBDTTFBSe"
[294] "SMILESsnamep1M_PBDTTFDPP"
[295] "SMILESsnamep1M_PBDTTFTTE"
[296] "SMILESsnamep1M_PBDTTPD"
[297] "SMILESsnamep1M_PBDTTPDP1"
[298] "SMILESsnamep1M_PBDTTPDP2"
[299] "SMILESsnamep1M_PBDTTPDP3"
[300] "SMILESsnamep1M_PBDTTS1"
[301] "SMILESsnamep1M_PBDTTS2"
[302] "SMILESsnamep1M_PBDTTS3"
[303] "SMILESsnamep1M_PBDTTSeDPP"
[304] "SMILESsnamep1M_PBDTTTBT"
[305] "SMILESsnamep1M_PBDTTTC"
[306] "SMILESsnamep1M_PBDTTTCF"
[307] "SMILESsnamep1M_PBDTTTE"
[308] "SMILESsnamep1M_PBDTTTS"
[309] "SMILESsnamep1M_PBDTTTST"
[310] "SMILESsnamep1M_PBPT12"
[311] "SMILESsnamep1M_PBQ1"
[312] "SMILESsnamep1M_PBQ2"
[313] "SMILESsnamep1M_PBQ3"
[314] "SMILESsnamep1M_PBQ4"
[315] "SMILESsnamep1M_PBT0F"
[316] "SMILESsnamep1M_PBT1F"
[317] "SMILESsnamep1M_PBT2F"
[318] "SMILESsnamep1M_PBT3F"
[319] "SMILESsnamep1M_PBTPyDPP"
[320] "SMILESsnamep1M_PBTff4T2OD"
[321] "SMILESsnamep1M_PBnDTFTAZ"
[322] "SMILESsnamep1M_PBnDTHTAZ"
[323] "SMILESsnamep1M_PCBTDPP"
[324] "SMILESsnamep1M_PCDTBT"
[325] "SMILESsnamep1M_PCDTBX"
[326] "SMILESsnamep1M_PCDTDPP"
[327] "SMILESsnamep1M_PCDTPT"
[328] "SMILESsnamep1M_PCDTPX"
[329] "SMILESsnamep1M_PCDTQx"
[330] "SMILESsnamep1M_PCDTTPP"
[331] "SMILESsnamep1M_PCPDTBT"
[332] "SMILESsnamep1M_PCPTDO"
[333] "SMILESsnamep1M_PCTDPP"
[334] "SMILESsnamep1M_PCV"
[335] "SMILESsnamep1M_PCVT"
[336] "SMILESsnamep1M_PCVTT"
[337] "SMILESsnamep1M_PCVTTTT"
[338] "SMILESsnamep1M_PCz"
[339] "SMILESsnamep1M_PDPP2FTC12"
[340] "SMILESsnamep1M_PDPP2FTC14"
[341] "SMILESsnamep1M_PDPP2FTC16"
[342] "SMILESsnamep1M_PDPP2T"
[343] "SMILESsnamep1M_PDPP2TBP"
[344] "SMILESsnamep1M_PDPP3T"
[345] "SMILESsnamep1M_PDPP3TaltTPT"
[346] "SMILESsnamep1M_PDPPBBT"
[347] "SMILESsnamep1M_PDPPBT"
[348] "SMILESsnamep1M_PDPPTPT"
[349] "SMILESsnamep1M_PDPPTVT"
[350] "SMILESsnamep1M_PDTPDTDPP"
[351] "SMILESsnamep1M_PDTPDTDPPBu"
[352] "SMILESsnamep1M_PDTST"
[353] "SMILESsnamep1M_PDTSTPD"
[354] "SMILESsnamep1M_PEN"
[355] "SMILESsnamep1M_PFBTBDT"
[356] "SMILESsnamep1M_PFDTBT"
[357] "SMILESsnamep1M_PFDTDPP"
[358] "SMILESsnamep1M_PGFDTBT"
[359] "SMILESsnamep1M_PGFDTDPPC4S25"
[360] "SMILESsnamep1M_PGFDTDPPC8"
[361] "SMILESsnamep1M_PICDTBT"
[362] "SMILESsnamep1M_PIDTTFBSe"
[363] "SMILESsnamep1M_PNNT12DT"
[364] "SMILESsnamep1M_PNNT12HD"
[365] "SMILESsnamep1M_PNNTDT"
[366] "SMILESsnamep1M_PNOz4T"
[367] "SMILESsnamep1M_PNT4T2OD"
[368] "SMILESsnamep1M_PNTz4T"
[369] "SMILESsnamep1M_PNTz4TF2"
[370] "SMILESsnamep1M_PNTz4TF4"
[371] "SMILESsnamep1M_PPDT2FBT"
[372] "SMILESsnamep1M_PPDTBT"
[373] "SMILESsnamep1M_PPDTFBT"
[374] "SMILESsnamep1M_PQT12"
[375] "SMILESsnamep1M_PSBTBT"
[376] "SMILESsnamep1M_PSEHTT"
[377] "SMILESsnamep1M_PTB1"
[378] "SMILESsnamep1M_PTB2"
[379] "SMILESsnamep1M_PTB3"
[380] "SMILESsnamep1M_PTB4"
[381] "SMILESsnamep1M_PTB5"
[382] "SMILESsnamep1M_PTB6"
[383] "SMILESsnamep1M_PTB7"
[384] "SMILESsnamep1M_PTB7Th"
[385] "SMILESsnamep1M_PTBDTDTBT"
[386] "SMILESsnamep1M_PTBDTffDTBT"
[387] "SMILESsnamep1M_PTBF0"
[388] "SMILESsnamep1M_PTBF1"
[389] "SMILESsnamep1M_PTBF2"
[390] "SMILESsnamep1M_PTBF3"
[391] "SMILESsnamep1M_PTBFTDTBT"
[392] "SMILESsnamep1M_PTBI2T"
[393] "SMILESsnamep1M_PTBI2TR"
[394] "SMILESsnamep1M_PTBI2Tz"
[395] "SMILESsnamep1M_PTBITT"
[396] "SMILESsnamep1M_PTzBT10HD"
[397] "SMILESsnamep1M_PTzBT10OD"
[398] "SMILESsnamep1M_PTzBT12HD"
[399] "SMILESsnamep1M_PTzBT12OD"
[400] "SMILESsnamep1M_PTzBT14HD"
[401] "SMILESsnamep1M_PTzBT14OD"
[402] "SMILESsnamep1M_PTzBTBOBO"
[403] "SMILESsnamep1M_PTzBTBOHD"
[404] "SMILESsnamep1M_PTzBTBOOD"
[405] "SMILESsnamep1M_PTzBTEHHD"
[406] "SMILESsnamep1M_PTzBTEHOD"
[407] "SMILESsnamep1M_PTzBTHD"
[408] "SMILESsnamep1M_PTzQT14"
[409] "SMILESsnamep1M_PeNPz2T"
[410] "SMILESsnamep1M_PeNPz3T"
[411] "SMILESsnamep1M_PeNPz4T"
[412] "SMILESsnamep1M_PffBT4T2OD"
[413] "SMILESsnamep1M_PhBADT"
[414] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2.thienyl..1.2.5.oxadiazolo.3.4d.pyridazine.P1"
[415] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.2.3dioctylpyrazino.2.3d.pyridazine.P2"
[416] "SMILESsnamep1M_Poly.N9.fheptadecanyl2.7carbazolealt5.5.4.f.7.fdi2thienyl.pyrazino.2.3d.pyridazine.P3"
[417] "SMILESsnamep1M_RanPBDPPT"
[418] "SMILESsnamep1M_RegPBDPPT"
[419] "SMILESsnamep1M_TDPPBBT"
[420] "SMILESsnamep1M_TPDBr16"
[421] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP1"
[422] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP2"
[423] "SMILESsnamep1M_Thieno.3.4c.pyrrole4.6dioneP3"
[424] "SMILESsnamep1M_TzTzBTIDG"
[425] "SMILESsnamep1M_TzTzalkylthiopheneBTIDG"
[426] "SMILESsnamep1M_VacdepoBPc"
[427] "SMILESsnamep1M_fBPC60"
[428] "SMILESsnamep1M_pBTTT"
[429] "SMILESsnamep1M_rBPC60"
[430] "SMILESsnamep1M_ranPDPPTPDalt2T"
[431] "SMILESsnamep1M_regPDPPTPDalt2T"
[432] "SMILESsnamep1M_thieno.3.2b.thiopheneP2"
[433] "SMILESsnamep2M_PBDTTFTTE"
[434] "Observed"
[435] "Predicted"
[436] "AbsError"
[437] "is_S"
<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/high_error_Samples_Jsc.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/all_with_Sflag_Jsc.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/obs_vs_pred_Jsc.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/summary_S_numeric_Jsc.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/summary_nonS_numeric_Jsc.csv

============================================
Target: Voc
 model_name  : RF
 dataset_tag : m_base_FP
 folder_name : Voc
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Voc/m_base_FP_rebuilt_Voc_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/Voc/m_base_FP_rebuilt_Voc_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc

>> oof_err cols:
[1] "SampleID"           "foldID"             "Observed"
[4] "Predicted"          "Error"              "AbsError"
[7] "Type"               "HighErrorFlag"      "HighErrorThreshold"
>> feat cols:
  [1] "SampleID"           "foldID"             "Error"
  [4] "Type"               "HighErrorFlag"      "HighErrorThreshold"
  [7] "Egoptp1M"           "HOMOp1M"            "LUMOp1M"
 [10] "Mmonomerp1M"        "MnkDap1M"           "MwkDap1M"
 [13] "PDIp1M"             "X100.1"             "X100.3"
 [16] "X100.4"             "X101.3"             "X101.4"
 [19] "X101.5"             "X102.4"             "X105"
 [22] "X105.1"             "X105.3"             "X105.4"
 [25] "X107.4"             "X108.1"             "X108.3"
 [28] "X108.4"             "X109.1"             "X109.3"
 [31] "X109.4"             "X110.3"             "X110.4"
 [34] "X111.3"             "X111.4"             "X112.1"
 [37] "X112.3"             "X112.4"             "X113.3"
 [40] "X113.4"             "X114.1"             "X114.3"
 [43] "X114.4"             "X115.1"             "X115.3"
 [46] "X115.4"             "X116.3"             "X116.4"
 [49] "X118.1"             "X118.3"             "X118.4"
 [52] "X119.4"             "X120.3"             "X120.4"
 [55] "X121.1"             "X121.3"             "X121.4"
 [58] "X122.3"             "X122.4"             "X123.3"
 [61] "X123.4"             "X124.4"             "X125.3"
 [64] "X125.4"             "X126.3"             "X127.3"
 [67] "X127.4"             "X128.1"             "X128.3"
 [70] "X128.4"             "X129.3"             "X129.4"
 [73] "X130.4"             "X131.1"             "X131.3"
 [76] "X131.4"             "X132.3"             "X132.4"
 [79] "X133.4"             "X134.4"             "X135.4"
 [82] "X136.4"             "X137.3"             "X137.4"
 [85] "X138.3"             "X138.4"             "X139.4"
 [88] "X140.4"             "X141.1"             "X141.4"
 [91] "X142.4"             "X144.3"             "X144.4"
 [94] "X145.4"             "X146.4"             "X147.3"
 [97] "X148.4"             "X149.1"             "X149.3"
[100] "X149.4"             "X150.1"             "X150.3"
[103] "X150.4"             "X152.4"             "X153.1"
[106] "X153.4"             "X154.3"             "X154.4"
[109] "X155.1"             "X155.4"             "X157.3"
[112] "X158.4"             "X159.4"             "X160.3"
[115] "X160.4"             "X162.4"             "X163.3"
[118] "X163.4"             "X164.3"             "X164.4"
[121] "X165.2"             "X166.4"             "X17.1"
[124] "X17.4"              "X19.3"              "X19.4"
[127] "X20.4"              "X22.4"              "X26.1"
[130] "X26.3"              "X26.4"              "X3.4"
[133] "X30.4"              "X33.4"              "X34.4"
[136] "X36.1"              "X36.3"              "X36.4"
[139] "X44.3"              "X44.4"              "X45.4"
[142] "X46.4"              "X47.3"              "X47.4"
[145] "X50.3"              "X50.4"              "X51.4"
[148] "X52.4"              "X57.4"              "X58.4"
[151] "X59.4"              "X62.1"              "X62.3"
[154] "X62.4"              "X65.3"              "X65.4"
[157] "X66.4"              "X70.4"              "X71.4"
[160] "X72.4"              "X74.4"              "X76.4"
[163] "X77.4"              "X79.4"              "X80.4"
[166] "X83.3"              "X85.4"              "X86.3"
[169] "X89.4"              "X90.4"              "X91.4"
[172] "X93.3"              "X94.4"              "X95.4"
[175] "X96.3"              "X97.4"              "X98.3"
[178] "X98.4"              "X99.4"
<U+8AA4><U+5DEE> (AbsError) summary:
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.0001277 0.0104600 0.0242955 0.0463050 0.0548577 0.6774933

top_k <U+30E2><U+30FC><U+30C9>: <U+4E0A><U+4F4D> 10 <U+4EF6><U+76EE><U+306E> abs_error = 0.33197 <U+3092><U+95BE><U+5024><U+5019><U+88DC><U+3068><U+3057><U+307E><U+3059><U+3002>
abs_error_thr <U+672A><U+6307><U+5B9A><U+306E><U+305F><U+3081><U+3001>top_k <U+306B><U+7531><U+6765><U+3059><U+308B> 0.33197 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 0.33197

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 10 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1] 0.3319700 0.6774933

>> dat_all cols:
  [1] "SampleID"           "foldID"             "Error"
  [4] "Type"               "HighErrorFlag"      "HighErrorThreshold"
  [7] "Egoptp1M"           "HOMOp1M"            "LUMOp1M"
 [10] "Mmonomerp1M"        "MnkDap1M"           "MwkDap1M"
 [13] "PDIp1M"             "X100.1"             "X100.3"
 [16] "X100.4"             "X101.3"             "X101.4"
 [19] "X101.5"             "X102.4"             "X105"
 [22] "X105.1"             "X105.3"             "X105.4"
 [25] "X107.4"             "X108.1"             "X108.3"
 [28] "X108.4"             "X109.1"             "X109.3"
 [31] "X109.4"             "X110.3"             "X110.4"
 [34] "X111.3"             "X111.4"             "X112.1"
 [37] "X112.3"             "X112.4"             "X113.3"
 [40] "X113.4"             "X114.1"             "X114.3"
 [43] "X114.4"             "X115.1"             "X115.3"
 [46] "X115.4"             "X116.3"             "X116.4"
 [49] "X118.1"             "X118.3"             "X118.4"
 [52] "X119.4"             "X120.3"             "X120.4"
 [55] "X121.1"             "X121.3"             "X121.4"
 [58] "X122.3"             "X122.4"             "X123.3"
 [61] "X123.4"             "X124.4"             "X125.3"
 [64] "X125.4"             "X126.3"             "X127.3"
 [67] "X127.4"             "X128.1"             "X128.3"
 [70] "X128.4"             "X129.3"             "X129.4"
 [73] "X130.4"             "X131.1"             "X131.3"
 [76] "X131.4"             "X132.3"             "X132.4"
 [79] "X133.4"             "X134.4"             "X135.4"
 [82] "X136.4"             "X137.3"             "X137.4"
 [85] "X138.3"             "X138.4"             "X139.4"
 [88] "X140.4"             "X141.1"             "X141.4"
 [91] "X142.4"             "X144.3"             "X144.4"
 [94] "X145.4"             "X146.4"             "X147.3"
 [97] "X148.4"             "X149.1"             "X149.3"
[100] "X149.4"             "X150.1"             "X150.3"
[103] "X150.4"             "X152.4"             "X153.1"
[106] "X153.4"             "X154.3"             "X154.4"
[109] "X155.1"             "X155.4"             "X157.3"
[112] "X158.4"             "X159.4"             "X160.3"
[115] "X160.4"             "X162.4"             "X163.3"
[118] "X163.4"             "X164.3"             "X164.4"
[121] "X165.2"             "X166.4"             "X17.1"
[124] "X17.4"              "X19.3"              "X19.4"
[127] "X20.4"              "X22.4"              "X26.1"
[130] "X26.3"              "X26.4"              "X3.4"
[133] "X30.4"              "X33.4"              "X34.4"
[136] "X36.1"              "X36.3"              "X36.4"
[139] "X44.3"              "X44.4"              "X45.4"
[142] "X46.4"              "X47.3"              "X47.4"
[145] "X50.3"              "X50.4"              "X51.4"
[148] "X52.4"              "X57.4"              "X58.4"
[151] "X59.4"              "X62.1"              "X62.3"
[154] "X62.4"              "X65.3"              "X65.4"
[157] "X66.4"              "X70.4"              "X71.4"
[160] "X72.4"              "X74.4"              "X76.4"
[163] "X77.4"              "X79.4"              "X80.4"
[166] "X83.3"              "X85.4"              "X86.3"
[169] "X89.4"              "X90.4"              "X91.4"
[172] "X93.3"              "X94.4"              "X95.4"
[175] "X96.3"              "X97.4"              "X98.3"
[178] "X98.4"              "X99.4"              "Observed"
[181] "Predicted"          "AbsError"           "is_S"
<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/high_error_Samples_Voc.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/all_with_Sflag_Voc.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/obs_vs_pred_Voc.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/summary_S_numeric_Voc.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/summary_nonS_numeric_Voc.csv

============================================
Target: FF
 model_name  : kNN
 dataset_tag : m_all_FP
 folder_name : FF
============================================
Input (OOF+Error):      /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/FF/m_all_FP_rebuilt_FF_pred_OOF_withError.csv
Input (WithFeatures):   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/bundle_for_thesis_20260119/FF/m_all_FP_rebuilt_FF_pred_OOF_withError_andFeatures.csv
Output dir:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF

>> oof_err cols:
[1] "SampleID"           "foldID"             "Observed"
[4] "Predicted"          "Error"              "AbsError"
[7] "Type"               "HighErrorFlag"      "HighErrorThreshold"
>> feat cols:
  [1] "SampleID"                         "foldID"
  [3] "Error"                            "Type"
  [5] "HighErrorFlag"                    "HighErrorThreshold"
  [7] "THFSVAafetrN"                     "THFSVAafetrI"
  [9] "Aarea"                            "Aonsetp1Mfilm"
 [11] "Abandp1Mfilm1"                    "Abandp1Mfilm2"
 [13] "Abandp1Mfilm3"                    "Aonsetp1MSol"
 [15] "Abandp1MSol1"                     "Abandp1MSol2"
 [17] "Abandp1MSol3"                     "AfAeThin"
 [19] "ALthickness"                      "amountAditive"
 [21] "amountsolutionI"                  "cycle"
 [23] "E12oxp1M"                         "E12redp1M"
 [25] "EgDFTp1M"                         "EgECnM"
 [27] "EgECp1M"                          "EgoptnM"
 [29] "Egoptp1M"                         "FWHMThin"
 [31] "HOMODFTp1M"                       "HOMOECp1M"
 [33] "HOMOp1M"                          "Lay2SCspeed"
 [35] "Lay2SCtime"                       "Lay2TAtemp"
 [37] "Lay2TAtime"                       "Lay2thickness"
 [39] "Lay5thickness"                    "Lay6DPpreTorr"
 [41] "Lay6thickness"                    "LUMOECp1M"
 [43] "LUMOnM"                           "LUMOp1M"
 [45] "measureINT"                       "Mmonomerp1M"
 [47] "MnkDanM"                          "MnkDap1M"
 [49] "MnMp1M"                           "MPDnp1M"
 [51] "MwkDap1M"                         "NLthickness"
 [53] "PDInM"                            "PDIp1M"
 [55] "PLthickness"                      "RatioinM"
 [57] "Ratioip1M"                        "Ratioip2M"
 [59] "RationM"                          "Ratiop1M"
 [61] "Ratiop2M"                         "SCspeed1"
 [63] "SCtime1"                          "solution"
 [65] "solutionI"                        "solutionN"
 [67] "solutionP"                        "solutionPI"
 [69] "solutionPN"                       "T5dp1M"
 [71] "TAtemp1"                          "TAtime1"
 [73] "TAtimelast"                       "TD1temp"
 [75] "TD2temp"                          "TDtime"
 [77] "UVIntP"                           "UVtimeP"
 [79] "VolRatioS1"                       "Lay2Mname_"
 [81] "Lay2Mname_PEDOTPSS"               "Lay2Mname_ZnO"
 [83] "Lay2Mname_ZnOC60"                 "Lay5electronodes1_"
 [85] "Lay5electronodes1_Al"             "Lay5electronodes1_BCP"
 [87] "Lay5electronodes1_C60bis"         "Lay5electronodes1_Ca"
 [89] "Lay5electronodes1_ETL.1"          "Lay5electronodes1_Li"
 [91] "Lay5electronodes1_LiF"            "Lay5electronodes1_Mg"
 [93] "Lay5electronodes1_MoO3"           "Lay5electronodes1_MoO3orV2O5"
 [95] "Lay5electronodes1_MoOx"           "Lay5electronodes1_TiOx"
 [97] "Lay6electronodes2_"               "Lay6electronodes2_Ag"
 [99] "Lay6electronodes2_Al"             "Additivesname_"
[101] "Additivesname_1.8dibromoooctane"  "Additivesname_1.8dicholorooctane"
[103] "Additivesname_1.8dicyanooctane"   "Additivesname_1.8octanediacetate"
[105] "Additivesname_1.8octanedithiol"   "Additivesname_1CN"
[107] "Additivesname_CS2"                "Additivesname_DCB"
[109] "Additivesname_DIO"                "Additivesname_DPE"
[111] "namessolvent1_"                   "namessolvent1_CB"
[113] "namessolvent1_CF"                 "namessolvent1_DCM"
[115] "namessolvent1_TCB"                "namessolvent1_THF"
[117] "namessolvent1_oDCB"               "namessolvent2_"
[119] "namessolvent2_CB"                 "namessolvent2_CF"
[121] "namessolvent2_DIO"                "namessolvent2_TCB"
[123] "namessolvent2_oDCB"               "X100.4"
[125] "X101.3"                           "X101.4"
[127] "X102.4"                           "X105.4"
[129] "X107.4"                           "X108.1"
[131] "X108.3"                           "X108.4"
[133] "X109.3"                           "X111.3"
[135] "X111.4"                           "X112.1"
[137] "X112.3"                           "X112.4"
[139] "X113.4"                           "X114.4"
[141] "X115.1"                           "X115.3"
[143] "X115.4"                           "X116.4"
[145] "X117.4"                           "X118.3"
[147] "X119.4"                           "X120.3"
[149] "X120.4"                           "X122.4"
[151] "X123.3"                           "X123.4"
[153] "X124.4"                           "X125.4"
[155] "X126.3"                           "X128.3"
[157] "X128.4"                           "X129.1"
[159] "X129.3"                           "X129.4"
[161] "X130.4"                           "X132.3"
[163] "X132.4"                           "X133.4"
[165] "X134.4"                           "X135.4"
[167] "X136.4"                           "X137.3"
[169] "X137.4"                           "X138.3"
[171] "X138.4"                           "X139.4"
[173] "X140.4"                           "X141.1"
[175] "X141.4"                           "X142.3"
[177] "X142.4"                           "X143.3"
[179] "X143.4"                           "X144.3"
[181] "X144.4"                           "X145.3"
[183] "X145.4"                           "X146.3"
[185] "X146.4"                           "X147.1"
[187] "X147.3"                           "X147.4"
[189] "X148.4"                           "X149.1"
[191] "X149.3"                           "X149.4"
[193] "X150.1"                           "X150.3"
[195] "X150.4"                           "X151.1"
[197] "X151.3"                           "X151.4"
[199] "X152.3"                           "X152.4"
[201] "X153.1"                           "X153.3"
[203] "X153.4"                           "X154.4"
[205] "X155.1"                           "X155.3"
[207] "X155.4"                           "X157.3"
[209] "X157.4"                           "X158.1"
[211] "X158.3"                           "X158.4"
[213] "X159.3"                           "X159.4"
[215] "X160.1"                           "X160.3"
[217] "X160.4"                           "X161.1"
[219] "X161.3"                           "X161.4"
[221] "X163.3"                           "X163.4"
[223] "X164.1"                           "X164.3"
[225] "X164.4"                           "X165"
[227] "X165.1"                           "X165.2"
[229] "X165.3"                           "X165.4"
[231] "X165.5"                           "X166.4"
[233] "X17.1"                            "X17.4"
[235] "X19.4"                            "X20.4"
[237] "X22.3"                            "X22.4"
[239] "X26.3"                            "X26.4"
[241] "X3.4"                             "X33.4"
[243] "X34.4"                            "X44.3"
[245] "X44.4"                            "X45.4"
[247] "X46.4"                            "X47.3"
[249] "X47.4"                            "X50.1"
[251] "X50.4"                            "X52.4"
[253] "X57.4"                            "X62.1"
[255] "X62.3"                            "X62.4"
[257] "X64.4"                            "X65.4"
[259] "X66.4"                            "X67.4"
[261] "X70.4"                            "X71.4"
[263] "X72.4"                            "X73.4"
[265] "X74.4"                            "X76.4"
[267] "X77.4"                            "X79.3"
[269] "X79.4"                            "X80.4"
[271] "X83.3"                            "X85.4"
[273] "X86.3"                            "X86.4"
[275] "X88.1"                            "X88.3"
[277] "X88.4"                            "X89.4"
[279] "X90.4"                            "X91.4"
[281] "X93.3"                            "X94.4"
[283] "X95.4"                            "X96.3"
[285] "X97.4"                            "X98.3"
[287] "X98.4"                            "X99.3"
[289] "X99.4"
<U+8AA4><U+5DEE> (AbsError) summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00000 0.02000 0.04667 0.05962 0.08233 0.39000

top_k <U+30E2><U+30FC><U+30C9>: <U+4E0A><U+4F4D> 10 <U+4EF6><U+76EE><U+306E> abs_error = 0.2571667 <U+3092><U+95BE><U+5024><U+5019><U+88DC><U+3068><U+3057><U+307E><U+3059><U+3002>
abs_error_thr <U+672A><U+6307><U+5B9A><U+306E><U+305F><U+3081><U+3001>top_k <U+306B><U+7531><U+6765><U+3059><U+308B> 0.2571667 <U+3092><U+4F7F><U+7528><U+3057><U+307E><U+3059><U+3002>

<U+6700><U+7D42><U+7684><U+306B><U+4F7F><U+7528><U+3059><U+308B> abs_error <U+95BE><U+5024> = 0.2571667

S (<U+5916><U+308C><U+5024><U+5019><U+88DC>) <U+306E><U+4EF6><U+6570>: 10 / 1045
S <U+306E> abs_error <U+7BC4><U+56F2>:
[1] 0.2571667 0.3900000

>> dat_all cols:
  [1] "SampleID"                         "foldID"
  [3] "Error"                            "Type"
  [5] "HighErrorFlag"                    "HighErrorThreshold"
  [7] "THFSVAafetrN"                     "THFSVAafetrI"
  [9] "Aarea"                            "Aonsetp1Mfilm"
 [11] "Abandp1Mfilm1"                    "Abandp1Mfilm2"
 [13] "Abandp1Mfilm3"                    "Aonsetp1MSol"
 [15] "Abandp1MSol1"                     "Abandp1MSol2"
 [17] "Abandp1MSol3"                     "AfAeThin"
 [19] "ALthickness"                      "amountAditive"
 [21] "amountsolutionI"                  "cycle"
 [23] "E12oxp1M"                         "E12redp1M"
 [25] "EgDFTp1M"                         "EgECnM"
 [27] "EgECp1M"                          "EgoptnM"
 [29] "Egoptp1M"                         "FWHMThin"
 [31] "HOMODFTp1M"                       "HOMOECp1M"
 [33] "HOMOp1M"                          "Lay2SCspeed"
 [35] "Lay2SCtime"                       "Lay2TAtemp"
 [37] "Lay2TAtime"                       "Lay2thickness"
 [39] "Lay5thickness"                    "Lay6DPpreTorr"
 [41] "Lay6thickness"                    "LUMOECp1M"
 [43] "LUMOnM"                           "LUMOp1M"
 [45] "measureINT"                       "Mmonomerp1M"
 [47] "MnkDanM"                          "MnkDap1M"
 [49] "MnMp1M"                           "MPDnp1M"
 [51] "MwkDap1M"                         "NLthickness"
 [53] "PDInM"                            "PDIp1M"
 [55] "PLthickness"                      "RatioinM"
 [57] "Ratioip1M"                        "Ratioip2M"
 [59] "RationM"                          "Ratiop1M"
 [61] "Ratiop2M"                         "SCspeed1"
 [63] "SCtime1"                          "solution"
 [65] "solutionI"                        "solutionN"
 [67] "solutionP"                        "solutionPI"
 [69] "solutionPN"                       "T5dp1M"
 [71] "TAtemp1"                          "TAtime1"
 [73] "TAtimelast"                       "TD1temp"
 [75] "TD2temp"                          "TDtime"
 [77] "UVIntP"                           "UVtimeP"
 [79] "VolRatioS1"                       "Lay2Mname_"
 [81] "Lay2Mname_PEDOTPSS"               "Lay2Mname_ZnO"
 [83] "Lay2Mname_ZnOC60"                 "Lay5electronodes1_"
 [85] "Lay5electronodes1_Al"             "Lay5electronodes1_BCP"
 [87] "Lay5electronodes1_C60bis"         "Lay5electronodes1_Ca"
 [89] "Lay5electronodes1_ETL.1"          "Lay5electronodes1_Li"
 [91] "Lay5electronodes1_LiF"            "Lay5electronodes1_Mg"
 [93] "Lay5electronodes1_MoO3"           "Lay5electronodes1_MoO3orV2O5"
 [95] "Lay5electronodes1_MoOx"           "Lay5electronodes1_TiOx"
 [97] "Lay6electronodes2_"               "Lay6electronodes2_Ag"
 [99] "Lay6electronodes2_Al"             "Additivesname_"
[101] "Additivesname_1.8dibromoooctane"  "Additivesname_1.8dicholorooctane"
[103] "Additivesname_1.8dicyanooctane"   "Additivesname_1.8octanediacetate"
[105] "Additivesname_1.8octanedithiol"   "Additivesname_1CN"
[107] "Additivesname_CS2"                "Additivesname_DCB"
[109] "Additivesname_DIO"                "Additivesname_DPE"
[111] "namessolvent1_"                   "namessolvent1_CB"
[113] "namessolvent1_CF"                 "namessolvent1_DCM"
[115] "namessolvent1_TCB"                "namessolvent1_THF"
[117] "namessolvent1_oDCB"               "namessolvent2_"
[119] "namessolvent2_CB"                 "namessolvent2_CF"
[121] "namessolvent2_DIO"                "namessolvent2_TCB"
[123] "namessolvent2_oDCB"               "X100.4"
[125] "X101.3"                           "X101.4"
[127] "X102.4"                           "X105.4"
[129] "X107.4"                           "X108.1"
[131] "X108.3"                           "X108.4"
[133] "X109.3"                           "X111.3"
[135] "X111.4"                           "X112.1"
[137] "X112.3"                           "X112.4"
[139] "X113.4"                           "X114.4"
[141] "X115.1"                           "X115.3"
[143] "X115.4"                           "X116.4"
[145] "X117.4"                           "X118.3"
[147] "X119.4"                           "X120.3"
[149] "X120.4"                           "X122.4"
[151] "X123.3"                           "X123.4"
[153] "X124.4"                           "X125.4"
[155] "X126.3"                           "X128.3"
[157] "X128.4"                           "X129.1"
[159] "X129.3"                           "X129.4"
[161] "X130.4"                           "X132.3"
[163] "X132.4"                           "X133.4"
[165] "X134.4"                           "X135.4"
[167] "X136.4"                           "X137.3"
[169] "X137.4"                           "X138.3"
[171] "X138.4"                           "X139.4"
[173] "X140.4"                           "X141.1"
[175] "X141.4"                           "X142.3"
[177] "X142.4"                           "X143.3"
[179] "X143.4"                           "X144.3"
[181] "X144.4"                           "X145.3"
[183] "X145.4"                           "X146.3"
[185] "X146.4"                           "X147.1"
[187] "X147.3"                           "X147.4"
[189] "X148.4"                           "X149.1"
[191] "X149.3"                           "X149.4"
[193] "X150.1"                           "X150.3"
[195] "X150.4"                           "X151.1"
[197] "X151.3"                           "X151.4"
[199] "X152.3"                           "X152.4"
[201] "X153.1"                           "X153.3"
[203] "X153.4"                           "X154.4"
[205] "X155.1"                           "X155.3"
[207] "X155.4"                           "X157.3"
[209] "X157.4"                           "X158.1"
[211] "X158.3"                           "X158.4"
[213] "X159.3"                           "X159.4"
[215] "X160.1"                           "X160.3"
[217] "X160.4"                           "X161.1"
[219] "X161.3"                           "X161.4"
[221] "X163.3"                           "X163.4"
[223] "X164.1"                           "X164.3"
[225] "X164.4"                           "X165"
[227] "X165.1"                           "X165.2"
[229] "X165.3"                           "X165.4"
[231] "X165.5"                           "X166.4"
[233] "X17.1"                            "X17.4"
[235] "X19.4"                            "X20.4"
[237] "X22.3"                            "X22.4"
[239] "X26.3"                            "X26.4"
[241] "X3.4"                             "X33.4"
[243] "X34.4"                            "X44.3"
[245] "X44.4"                            "X45.4"
[247] "X46.4"                            "X47.3"
[249] "X47.4"                            "X50.1"
[251] "X50.4"                            "X52.4"
[253] "X57.4"                            "X62.1"
[255] "X62.3"                            "X62.4"
[257] "X64.4"                            "X65.4"
[259] "X66.4"                            "X67.4"
[261] "X70.4"                            "X71.4"
[263] "X72.4"                            "X73.4"
[265] "X74.4"                            "X76.4"
[267] "X77.4"                            "X79.3"
[269] "X79.4"                            "X80.4"
[271] "X83.3"                            "X85.4"
[273] "X86.3"                            "X86.4"
[275] "X88.1"                            "X88.3"
[277] "X88.4"                            "X89.4"
[279] "X90.4"                            "X91.4"
[281] "X93.3"                            "X94.4"
[283] "X95.4"                            "X96.3"
[285] "X97.4"                            "X98.3"
[287] "X98.4"                            "X99.3"
[289] "X99.4"                            "Observed"
[291] "Predicted"                        "AbsError"
[293] "is_S"
<U+7D50><U+5408><U+5F8C><U+30C7><U+30FC><U+30BF><U+884C><U+6570>: 1045

<U+7D50><U+679C><U+30D5><U+30A1><U+30A4><U+30EB><U+51FA><U+529B><U+5B8C><U+4E86>:
  S <U+306E><U+307F>:                   /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/high_error_Samples_FF.csv
  <U+5168><U+30B5><U+30F3><U+30D7><U+30EB>+S<U+30D5><U+30E9><U+30B0>:       /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/all_with_Sflag_FF.csv
  Obs vs Pred <U+56F3>:           /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/obs_vs_pred_FF.png
  S <U+6570><U+5024><U+8981><U+7D04>:               /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/summary_S_numeric_FF.csv
  <U+975E>S <U+6570><U+5024><U+8981><U+7D04>:             /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/summary_nonS_numeric_FF.csv

=========== <U+5916><U+308C><U+5024><U+89E3><U+6790><U+30B9><U+30AF><U+30EA><U+30D7><U+30C8><U+7D42><U+4E86> ===========

In [24]:
library(dplyr)
library(readr)
library(tidyr)

base_path       <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix   <- "outlier_results"
target_config   <- list(
  PCEmax = list(folder_name = "PCE"),
  Jsc    = list(folder_name = "Jsc"),
  Voc    = list(folder_name = "Voc"),
  FF     = list(folder_name = "FF")
)
targets <- names(target_config)

# 関心のある特徴量名（実データの列名に合わせて調整）
key_features <- c(
  "EgDFTp1M",      # Eg
  "Lay2thickness", # 膜厚
  "Aarea",         # 素子面積など
  "TAtemp1",       # アニール温度
  "TAtime1"        # アニール時間
  # 必要に応じて追加
)
basic_list <- lapply(targets, function(tg) {
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))

  dat <- read_csv(file_all, show_col_types = FALSE)

  # しきい値 = S / 非S の境界（S の中の最小 AbsError）
  thr <- dat %>%
    filter(is_S) %>%
    summarise(thr = min(AbsError, na.rm = TRUE)) %>%
    pull(thr)

  # S / 非S の件数と比率
  n_tot <- nrow(dat)
  n_S   <- sum(dat$is_S, na.rm = TRUE)
  n_nonS<- n_tot - n_S

  tibble(
    target         = tg,
    thr_AbsError   = thr,
    n_total        = n_tot,
    n_S            = n_S,
    n_nonS         = n_nonS,
    rate_S         = n_S / n_tot
  )
})

basic_summary <- bind_rows(basic_list)
write_csv(basic_summary,
          file.path(base_path, "summary_basic_S_rate_by_target.csv"))
abs_summary_list <- lapply(targets, function(tg) {
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))

  dat <- read_csv(file_all, show_col_types = FALSE)

  dat %>%
    group_by(is_S) %>%
    summarise(
      n      = n(),
      min    = min(AbsError, na.rm = TRUE),
      q1     = quantile(AbsError, 0.25, na.rm = TRUE),
      median = median(AbsError, na.rm = TRUE),
      mean   = mean(AbsError, na.rm = TRUE),
      q3     = quantile(AbsError, 0.75, na.rm = TRUE),
      max    = max(AbsError, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(target = tg) %>%
    select(target, is_S, n, min, q1, median, mean, q3, max)
})

abs_summary <- bind_rows(abs_summary_list)
write_csv(abs_summary,
          file.path(base_path, "summary_AbsError_S_vs_nonS_by_target.csv"))
feat_summary_list <- lapply(targets, function(tg) {
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))

  dat <- read_csv(file_all, show_col_types = FALSE)

  # 実際に存在する列だけに絞る（ターゲットによっては無い特徴量もあるので）
  feat_exist <- intersect(key_features, colnames(dat))
  if (length(feat_exist) == 0) return(NULL)

  dat %>%
    group_by(is_S) %>%
    summarise(
      across(
        all_of(feat_exist),
        list(mean = ~mean(.x, na.rm = TRUE),
             sd   = ~sd(.x,   na.rm = TRUE)),
        .names = "{.col}_{.fn}"
      ),
      .groups = "drop"
    ) %>%
    mutate(target = tg) %>%
    select(target, is_S, everything())
})

feat_summary <- bind_rows(feat_summary_list)
write_csv(feat_summary,
          file.path(base_path, "summary_features_S_vs_nonS_by_target.csv"))
# 3-1 の表から差分を計算
feat_long <- feat_summary %>%
  pivot_longer(
    cols = -c(target, is_S),
    names_to  = "feat_stat",
    values_to = "value"
  ) %>%
  separate(feat_stat, into = c("feature", "stat"), sep = "_(?=[^_]+$)")

feat_diff <- feat_long %>%
  filter(stat == "mean") %>%
  select(target, is_S, feature, value) %>%
  pivot_wider(
    names_from  = is_S,
    values_from = value,
    names_prefix = "mean_is_S_"
  ) %>%
  mutate(
    diff_S_minus_nonS = mean_is_S_TRUE - mean_is_S_FALSE
  )

write_csv(feat_diff,
          file.path(base_path, "summary_feature_mean_diff_S_minus_nonS_by_target.csv"))
model_difficulty <- abs_summary %>%
  group_by(target, is_S) %>%
  summarise(
    median_AbsError = median,
    mean_AbsError   = mean,
    .groups = "drop"
  ) %>%
  mutate(group = ifelse(is_S, "S", "nonS")) %>%
  select(target, group, median_AbsError, mean_AbsError) %>%
  pivot_wider(
    names_from  = group,
    values_from = c(median_AbsError, mean_AbsError),
    names_sep   = "_"
  ) %>%
  left_join(basic_summary, by = "target")

write_csv(model_difficulty,
          file.path(base_path, "summary_model_difficulty_by_target.csv"))

ERROR: Error: object 'feat' not found

In [25]:
library(dplyr)
library(readr)

# しきい値などの設定 --------------------------
file_diff <- "summary_feature_mean_diff_S_minus_nonS_by_target.csv"

# 「重要そうな目的変数」
important_targets <- c("Jsc", "PCEmax")

# diff の絶対値しきい値
abs_diff_thr <- 0.05

# 何個以上の重要ターゲットで差が出ていれば採用するか
min_imp_targets <- 1   # 例: 少なくとも Jsc または PCEmax のどちらかで効いていればOK

# 何個以上の全ターゲットで同じ向きの差が出ていれば「一貫している」とみなすか
min_total_targets_same_sign <- 2


# データ読み込み -----------------------------
diff_tbl <- read_csv(file_diff, show_col_types = FALSE)
# 列: target, feature, mean_is_S_FALSE, mean_is_S_TRUE, diff_S_minus_nonS


# 1) まず diff の絶対値が大きい行だけに絞る --------------------------
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)


# 2) 重要ターゲットでの効き具合を集計 -------------------------------
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets = n(),                                 # Jsc / PCEmax で効いている数
    max_abs_diff_imp = max(abs_diff),                   # その中で一番大きい差
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)


# 3) 全ターゲットでの「符号の一貫性」を評価 -------------------------
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets = n(),                                    # 有効なターゲット数
    n_pos     = sum(sign > 0),
    n_neg     = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups   = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),                   # 多い方の符号の個数
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )


# 4) 重要ターゲットで効いていて、かつ符号も一貫している変数だけ抽出 ----
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

suspicious_vars

  feature  n_imp_targets max_abs_diff_imp n_targets n_pos n_neg
1 EgDFTp1M 2             0.11452591       2         0     2
2 TAtime1  2             0.11394941       2         2     0
3 Aarea    2             0.07347052       2         0     2
  max_abs_diff_all n_same_sign sign_major
1 0.11452591       2           negative
2 0.11394941       2           positive
3 0.07347052       2           negative

In [26]:
library(dplyr)
library(readr)

# しきい値などの設定 --------------------------
file_diff <- "summary_feature_mean_diff_S_minus_nonS_by_target.csv"

# 「重要そうな目的変数」
important_targets <- c("PCEmax")

# diff の絶対値しきい値
abs_diff_thr <- 0.05

# 何個以上の重要ターゲットで差が出ていれば採用するか
min_imp_targets <- 1   # 例: 少なくとも Jsc または PCEmax のどちらかで効いていればOK

# 何個以上の全ターゲットで同じ向きの差が出ていれば「一貫している」とみなすか
min_total_targets_same_sign <- 2


# データ読み込み -----------------------------
diff_tbl <- read_csv(file_diff, show_col_types = FALSE)
# 列: target, feature, mean_is_S_FALSE, mean_is_S_TRUE, diff_S_minus_nonS


# 1) まず diff の絶対値が大きい行だけに絞る --------------------------
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)


# 2) 重要ターゲットでの効き具合を集計 -------------------------------
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets = n(),                                 # Jsc / PCEmax で効いている数
    max_abs_diff_imp = max(abs_diff),                   # その中で一番大きい差
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)


# 3) 全ターゲットでの「符号の一貫性」を評価 -------------------------
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets = n(),                                    # 有効なターゲット数
    n_pos     = sum(sign > 0),
    n_neg     = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups   = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),                   # 多い方の符号の個数
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )


# 4) 重要ターゲットで効いていて、かつ符号も一貫している変数だけ抽出 ----
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

suspicious_vars

  feature  n_imp_targets max_abs_diff_imp n_targets n_pos n_neg
1 TAtime1  1             0.09644862       2         2     0
2 EgDFTp1M 1             0.07470064       2         0     2
3 Aarea    1             0.07347052       2         0     2
  max_abs_diff_all n_same_sign sign_major
1 0.11394941       2           positive
2 0.11452591       2           negative
3 0.07347052       2           negative

In [27]:
library(dplyr)
library(readr)

# しきい値などの設定 --------------------------
file_diff <- "summary_feature_mean_diff_S_minus_nonS_by_target.csv"

# 「重要そうな目的変数」
important_targets <- c("Jsc")

# diff の絶対値しきい値
abs_diff_thr <- 0.05

# 何個以上の重要ターゲットで差が出ていれば採用するか
min_imp_targets <- 1   # 例: 少なくとも Jsc または PCEmax のどちらかで効いていればOK

# 何個以上の全ターゲットで同じ向きの差が出ていれば「一貫している」とみなすか
min_total_targets_same_sign <- 2


# データ読み込み -----------------------------
diff_tbl <- read_csv(file_diff, show_col_types = FALSE)
# 列: target, feature, mean_is_S_FALSE, mean_is_S_TRUE, diff_S_minus_nonS


# 1) まず diff の絶対値が大きい行だけに絞る --------------------------
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)


# 2) 重要ターゲットでの効き具合を集計 -------------------------------
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets = n(),                                 # Jsc / PCEmax で効いている数
    max_abs_diff_imp = max(abs_diff),                   # その中で一番大きい差
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)


# 3) 全ターゲットでの「符号の一貫性」を評価 -------------------------
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets = n(),                                    # 有効なターゲット数
    n_pos     = sum(sign > 0),
    n_neg     = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups   = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),                   # 多い方の符号の個数
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )


# 4) 重要ターゲットで効いていて、かつ符号も一貫している変数だけ抽出 ----
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

suspicious_vars

  feature  n_imp_targets max_abs_diff_imp n_targets n_pos n_neg
1 EgDFTp1M 1             0.11452591       2         0     2
2 TAtime1  1             0.11394941       2         2     0
3 Aarea    1             0.06829025       2         0     2
  max_abs_diff_all n_same_sign sign_major
1 0.11452591       2           negative
2 0.11394941       2           positive
3 0.07347052       2           negative

In [49]:
library(dplyr)
library(readr)

# しきい値などの設定 --------------------------
file_diff <- "summary_feature_mean_diff_S_minus_nonS_by_target.csv"

# 「重要そうな目的変数」
important_targets <- c("Voc")

# diff の絶対値しきい値
abs_diff_thr <- 0.000001

# 何個以上の重要ターゲットで差が出ていれば採用するか
min_imp_targets <- 1   # 例: 少なくとも Jsc または PCEmax のどちらかで効いていればOK

# 何個以上の全ターゲットで同じ向きの差が出ていれば「一貫している」とみなすか
min_total_targets_same_sign <- 2


# データ読み込み -----------------------------
diff_tbl <- read_csv(file_diff, show_col_types = FALSE)
# 列: target, feature, mean_is_S_FALSE, mean_is_S_TRUE, diff_S_minus_nonS


# 1) まず diff の絶対値が大きい行だけに絞る --------------------------
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)


# 2) 重要ターゲットでの効き具合を集計 -------------------------------
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets = n(),                                 # Jsc / PCEmax で効いている数
    max_abs_diff_imp = max(abs_diff),                   # その中で一番大きい差
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)


# 3) 全ターゲットでの「符号の一貫性」を評価 -------------------------
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets = n(),                                    # 有効なターゲット数
    n_pos     = sum(sign > 0),
    n_neg     = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups   = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),                   # 多い方の符号の個数
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )


# 4) 重要ターゲットで効いていて、かつ符号も一貫している変数だけ抽出 ----
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

suspicious_vars

Warning message:
"There was 1 warning in `summarise()`.
i In argument: `max_abs_diff_imp = max(abs_diff)`.
Caused by warning in `max()`:
! no non-missing arguments to max; returning -Inf"

     feature n_imp_targets max_abs_diff_imp n_targets n_pos n_neg
     max_abs_diff_all n_same_sign sign_major

In [50]:
library(dplyr)
library(readr)

# しきい値などの設定 --------------------------
file_diff <- "summary_feature_mean_diff_S_minus_nonS_by_target.csv"

# 「重要そうな目的変数」
important_targets <- c("FF")

# diff の絶対値しきい値
abs_diff_thr <- 0.01

# 何個以上の重要ターゲットで差が出ていれば採用するか
min_imp_targets <- 1   # 例: 少なくとも Jsc または PCEmax のどちらかで効いていればOK

# 何個以上の全ターゲットで同じ向きの差が出ていれば「一貫している」とみなすか
min_total_targets_same_sign <- 2


# データ読み込み -----------------------------
diff_tbl <- read_csv(file_diff, show_col_types = FALSE)
# 列: target, feature, mean_is_S_FALSE, mean_is_S_TRUE, diff_S_minus_nonS


# 1) まず diff の絶対値が大きい行だけに絞る --------------------------
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)


# 2) 重要ターゲットでの効き具合を集計 -------------------------------
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets = n(),                                 # Jsc / PCEmax で効いている数
    max_abs_diff_imp = max(abs_diff),                   # その中で一番大きい差
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)


# 3) 全ターゲットでの「符号の一貫性」を評価 -------------------------
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets = n(),                                    # 有効なターゲット数
    n_pos     = sum(sign > 0),
    n_neg     = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups   = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),                   # 多い方の符号の個数
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )


# 4) 重要ターゲットで効いていて、かつ符号も一貫している変数だけ抽出 ----
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

suspicious_vars

  feature       n_imp_targets max_abs_diff_imp n_targets n_pos n_neg
1 TAtime1       1             0.04395091       3         2     1
2 Aarea         1             0.04288601       3         1     2
3 Lay2thickness 1             0.02674466       2         0     2
  max_abs_diff_all n_same_sign sign_major
1 0.11394941       2           positive
2 0.07347052       2           negative
3 0.03428392       2           negative

In [47]:
library(dplyr)
library(readr)
min_imp_targets <- 1
# 1) 入力ファイル
file_diff <- "summary_feature_mean_diff_S_minus_nonS_by_target.csv"

# 2) ターゲットとしきい値の設定 --------------------------
important_targets <- c("Voc")  # Voc だけを見る
abs_diff_thr <- 0.00000000000001           # |S-非S| が 0.05 以上の特徴量だけを怪しいとみなす

# 3) データ読み込み ---------------------------------------
diff_tbl <- read_csv(file_diff, show_col_types = FALSE)
# 列: target, feature, mean_is_S_FALSE, mean_is_S_TRUE, diff_S_minus_nonS

# 4) Voc だけに絞って、「差の大きい順」に並べる ----------------
suspicious_vars_voc <- diff_tbl %>%
  filter(target %in% important_targets) %>%     # Voc 行だけ
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>% # 絶対値を計算
  filter(abs_diff >= abs_diff_thr) %>%          # 閾値以上だけ残す
  arrange(desc(abs_diff))                       # 差が大きい順に並べる

suspicious_vars_voc

     target feature mean_is_S_FALSE mean_is_S_TRUE diff_S_minus_nonS abs_diff

In [48]:
exists("oof_err")
ls()

[1] FALSE

 [1] "abs_diff_thr"                "abs_error_thr"
 [3] "abs_error_thr_list"          "abs_summary"
 [5] "abs_summary_list"            "base_path"
 [7] "basic_list"                  "basic_summary"
 [9] "bundle_folder_name"          "col_abserr"
[11] "col_id"                      "col_pred"
[13] "col_true"                    "diff_large"
[15] "diff_tbl"                    "f"
[17] "feat_diff"                   "feat_long"
[19] "feat_summary"                "feat_summary_all"
[21] "feat_summary_list"           "file_diff"
[23] "file_feat_diff"              "file_feat_summary"
[25] "imp_effect"                  "important_targets"
[27] "key_features"                "min_imp_targets"
[29] "min_total_targets_same_sign" "model_difficulty"
[31] "oof_pce"                     "output_prefix"
[33] "process_one_target"          "sign_consistency"
[35] "src_dir"                     "src_files"
[37] "src_path"                    "summary_dir"
[39] "summary_folder_name"         "suspicious_vars"
[41] "suspicious_vars_allTargets"  "suspicious_vars_voc"
[43] "target_config"               "targets"
[45] "test_oof"                    "tg"
[47] "tgt_dir"                     "top_k"
[49] "use_abs_thr_mode"            "use_top_k_mode"

In [13]:
test_oof <- readr::read_csv(
  file.path(
    base_path,
    bundle_folder_name,
    "PCE",
    "m_all_OH_rebuilt_PCEmax_pred_OOF_withError.csv"
  ),
  show_col_types = FALSE
)
names(test_oof)

[1] "SampleID"           "foldID"             "Observed"
[4] "Predicted"          "Error"              "AbsError"
[7] "Type"               "HighErrorFlag"      "HighErrorThreshold"

In [41]:
library(dplyr)
library(readr)
library(tidyr)

base_path     <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix <- "outlier_results"

# 解析するターゲット
targets <- c("PCEmax", "Jsc", "Voc", "FF")

# 1) 各ターゲットについて、全数値列の S/非S 平均・SD を計算
feat_summary_list <- lapply(targets, function(tg) {
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))

  dat <- read_csv(file_all, show_col_types = FALSE)

  # 数値列を抽出（AbsError, is_S, ID系 など除外したい列はここで除く）
  num_cols <- names(dat)[sapply(dat, is.numeric)]
  num_cols <- setdiff(num_cols, c("AbsError", "is_S", "SampleID", "foldID"))

  if (length(num_cols) == 0) return(NULL)

  dat %>%
    group_by(is_S) %>%
    summarise(
      across(
        all_of(num_cols),
        list(mean = ~mean(.x, na.rm = TRUE),
             sd   = ~sd(.x,   na.rm = TRUE)),
        .names = "{.col}_{.fn}"
      ),
      .groups = "drop"
    ) %>%
    mutate(target = tg) %>%
    select(target, is_S, everything())
})

feat_summary_all <- bind_rows(feat_summary_list)

# 保存
file_feat_summary <- file.path(base_path, "summary_features_S_vs_nonS_allTargets_allNumeric.csv")
write_csv(feat_summary_all, file_feat_summary)

In [42]:
# 1) wide → long に展開して、mean だけ取り出す
feat_long <- feat_summary_all %>%
  pivot_longer(
    cols = -c(target, is_S),
    names_to  = "feat_stat",
    values_to = "value"
  ) %>%
  separate(feat_stat, into = c("feature", "stat"), sep = "_(?=[^_]+$)")

# 2) mean だけ残して、S/非S を横持ちにして差分
feat_diff <- feat_long %>%
  filter(stat == "mean") %>%
  select(target, is_S, feature, value) %>%
  pivot_wider(
    names_from  = is_S,
    values_from = value,
    names_prefix = "mean_is_S_"
  ) %>%
  mutate(
    diff_S_minus_nonS = mean_is_S_TRUE - mean_is_S_FALSE
  )

file_feat_diff <- file.path(base_path, "summary_feature_mean_diff_S_minus_nonS_allTargets_allNumeric.csv")
write_csv(feat_diff, file_feat_diff)

In [46]:
abs_diff_thr <- 0.01
min_total_targets_same_sign <- 1  # 何目的変数で同じ向きなら「一貫」とみなすか

# diff_tbl は summary_feature_mean_diff_... を読んだものとする
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)

sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets        = n(),
    n_pos            = sum(sign > 0),
    n_neg            = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )

suspicious_vars_allTargets <- sign_consistency %>%
  arrange(desc(max_abs_diff_all))

suspicious_vars_allTargets

  feature       n_targets n_pos n_neg max_abs_diff_all n_same_sign sign_major
1 EgDFTp1M      2         0     2     0.11452591       2           negative
2 TAtime1       3         2     1     0.11394941       2           positive
3 Aarea         3         1     2     0.07347052       2           negative
4 Lay2thickness 2         0     2     0.03428392       2           negative

In [ ]:
# ここまでがあなたのコード
abs_diff_thr <- 0.05
min_total_targets_same_sign <- 2

diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)

sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets        = n(),
    n_pos            = sum(sign > 0),
    n_neg            = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )

suspicious_vars_allTargets <- sign_consistency %>%
  arrange(desc(max_abs_diff_all))

# ここから出力部分 ------------------------------

library(readr)

# ベースパス（必要ならあなたの環境に合わせて変更）
base_path <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"

# しきい値をファイル名に埋め込む（. を _ に置き換えると安全）
abs_str  <- gsub("\\.", "p", as.character(abs_diff_thr))
nsame_str <- as.character(min_total_targets_same_sign)

file_out <- file.path(
  base_path,
  paste0(
    "suspicious_features_allTargets_abs", abs_str,
    "_nsame", nsame_str,
    ".csv"
  )
)

write_csv(suspicious_vars_allTargets, file_out)

cat("書き出し先: ", file_out, "\n")

In [53]:
library(dplyr)
library(readr)
library(tidyr)

base_path     <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix <- "outlier_results"

# 解析するターゲット
targets <- c("PCEmax", "Jsc", "Voc", "FF")

# 1) 各ターゲットについて、全数値列の S/非S 平均・SD を計算
feat_summary_list <- lapply(targets, function(tg) {
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))

  dat <- read_csv(file_all, show_col_types = FALSE)

  # 数値列を抽出（AbsError, is_S, ID系 など除外したい列はここで除く）
  num_cols <- names(dat)[sapply(dat, is.numeric)]
  num_cols <- setdiff(num_cols, c("AbsError", "is_S", "SampleID", "foldID"))

  if (length(num_cols) == 0) return(NULL)

  dat %>%
    group_by(is_S) %>%
    summarise(
      across(
        all_of(num_cols),
        list(mean = ~mean(.x, na.rm = TRUE),
             sd   = ~sd(.x,   na.rm = TRUE)),
        .names = "{.col}_{.fn}"
      ),
      .groups = "drop"
    ) %>%
    mutate(target = tg) %>%
    select(target, is_S, everything())
})

feat_summary_all <- bind_rows(feat_summary_list)

# 保存
file_feat_summary <- file.path(base_path, "summary_features_S_vs_nonS_allTargets_allNumeric.csv")
write_csv(feat_summary_all, file_feat_summary)

In [54]:
# 1) wide → long に展開して、mean だけ取り出す
feat_long <- feat_summary_all %>%
  pivot_longer(
    cols = -c(target, is_S),
    names_to  = "feat_stat",
    values_to = "value"
  ) %>%
  separate(feat_stat, into = c("feature", "stat"), sep = "_(?=[^_]+$)")

# 2) mean だけ残して、S/非S を横持ちにして差分
feat_diff <- feat_long %>%
  filter(stat == "mean") %>%
  select(target, is_S, feature, value) %>%
  pivot_wider(
    names_from  = is_S,
    values_from = value,
    names_prefix = "mean_is_S_"
  ) %>%
  mutate(
    diff_S_minus_nonS = mean_is_S_TRUE - mean_is_S_FALSE
  )

file_feat_diff <- file.path(base_path, "summary_feature_mean_diff_S_minus_nonS_allTargets_allNumeric.csv")
write_csv(feat_diff, file_feat_diff)

In [55]:
# 設定 ---------------------------
important_targets <- c("Jsc", "PCEmax", "Voc", "FF")  # 重視する目的変数
abs_diff_thr <- 0.05                    # |S-非S| のしきい値
min_imp_targets <- 1                    # 重要ターゲットの中で何個以上効いていれば採用するか
min_total_targets_same_sign <- 2        # 何目的変数で同じ向きなら「一貫」とみなすか

diff_tbl <- read_csv(file_feat_diff, show_col_types = FALSE)

# 1) 絶対差が大きい行だけ
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)

# 2) 重要ターゲットでの効き具合
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets   = n(),
    max_abs_diff_imp = max(abs_diff),
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)

# 3) 全ターゲットでの符号の一貫性
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets       = n(),
    n_pos           = sum(sign > 0),
    n_neg           = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )

# 4) 両方の条件を満たす「怪しい変数」
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

file_suspicious <- file.path(base_path, "suspicious_features_allNumeric_Jsc_PCEmax.csv")
write_csv(suspicious_vars, file_suspicious)

suspicious_vars

   feature                 n_imp_targets max_abs_diff_imp n_targets n_pos n_neg
1  Error                   2             1.00195386       4         4     0
2  Predicted               2             0.85151568       3         2     1
3  Observed                2             0.70514874       4         0     4
4  UVIntP                  2             0.43323695       2         0     2
5  SMILESsnamenM_PC61BM    2             0.30211055       2         0     2
6  Lay5electronodes1_LiF   2             0.27839196       3         2     1
7  Lay2Mname_PEDOTPSS      1             0.26693467       2         2     0
8  TAtimelast              2             0.26413965       3         1     2
9  namessolvent1_CF        2             0.26150754       3         2     1
10 AfAeThin                2             0.25644370       3         1     2
11 Lay6electronodes2_Ag    2             0.23607054       3         1     2
12 SMILESsnamenM_PC71BM    2             0.23276382       2         2     0
13 MnMp1M                  2             0.21026477       2         2     0
14 Lay5electronodes1_Ca    2             0.20442211       3         1     2
15 HOMOECp1M               2             0.19829912       2         2     0
16 PDInM                   2             0.19403873       3         1     2
17 Lay2SCtime              2             0.18944066       3         1     2
18 Abandp1Mfilm2           2             0.18492540       3         2     1
19 PLthickness             2             0.17566750       3         2     1
20 UVtimeP                 2             0.17450212       3         0     3
21 TDtime                  2             0.16676653       2         2     0
22 Abandp1MSol1            2             0.16369947       3         2     1
23 namessolvent1_          2             0.16206859       3         2     1
24 Lay2Mname_ZnO           2             0.15296482       3         0     3
25 Abandp1Mfilm3           2             0.15202567       3         2     1
26 Lay6electronodes2_      2             0.14183707       3         2     1
27 RationM                 2             0.13879726       2         2     0
28 Ratiop1M                2             0.13804611       2         0     2
29 Additivesname_          2             0.13199178       3         2     1
30 SCspeed1                2             0.13118381       3         3     0
31 LUMOECp1M               2             0.12356205       2         2     0
32 HOMOp1M                 1             0.12165755       2         2     0
33 EgDFTp1M                2             0.11452591       2         0     2
34 TAtime1                 2             0.11394941       2         2     0
35 TD2temp                 2             0.10804122       3         3     0
36 Lay5electronodes1_MoOx  2             0.10673367       3         1     2
37 Lay2Mname_              2             0.10391960       3         2     1
38 Lay6electronodes2_Al    1             0.09423347       2         0     2
39 SMILESsnamep1M_DTPDPP3T 2             0.09358433       2         2     0
40 SCtime1                 1             0.09165709       2         0     2
41 SMILESsnamep1M_PPDT2FBT 2             0.09163691       2         2     0
42 E12oxp1M                2             0.08505019       3         2     1
43 solutionPI              2             0.07968076       2         0     2
44 HOMODFTp1M              1             0.07570450       2         0     2
45 Aarea                   2             0.07347052       2         0     2
46 SMILESsnamep1M_DTA      2             0.06834171       2         0     2
47 SMILESsnamep1M_PNTz4T   2             0.06030151       2         0     2
48 Lay5electronodes1_MoO3  2             0.05628141       3         0     3
49 SMILESsnamep1M_PBDTFQT  2             0.05226131       2         0     2
50 SMILESsnamep1M_PTB7     2             0.05226131       2         0     2
51 Additivesname_DIO       1             0.05020015       2         0     2
   max_abs_diff_all n_same_sign sign_major
1  1.00195386       4           positive
2  0.85151568       2           positive
3  0.70514874       4           negative
4  0.43323695       2           negative
5  0.30211055       2           negative
6  0.27839196       2           positive
7  0.26693467       2           positive
8  0.26413965       2           negative
9  0.29753695       2           positive
10 0.25644370       2           negative
11 0.23607054       2           negative
12 0.23276382       2           positive
13 0.21026477       2           positive
14 0.20442211       2           negative
15 0.19829912       2           positive
16 0.19403873       2           negative
17 0.18944066       2           negative
18 0.18492540       2           positive
19 0.17566750       2           positive
20 0.17450212       3           negative
21 0.16676653       2           positive
22 0.16369947       2           positive
23 0.16206859       2           positive
24 0.19113300       3           negative
25 0.15202567       2           positive
26 0.26830870       2           positive
27 0.13879726       2           positive
28 0.13804611       2           negative
29 0.31658456       2           positive
30 0.13118381       3           positive
31 0.12356205       2           positive
32 0.16900311       2           positive
33 0.11452591       2           negative
34 0.11394941       2           positive
35 0.17795567       3           positive
36 0.10673367       2           negative
37 0.10391960       2           positive
38 0.11822660       2           negative
39 0.09358433       2           positive
40 0.09165709       2           negative
41 0.09163691       2           positive
42 0.08505019       2           positive
43 0.07968076       2           negative
44 0.14311731       2           negative
45 0.07347052       2           negative
46 0.06834171       2           negative
47 0.06030151       2           negative
48 0.05628141       3           negative
49 0.05226131       2           negative
50 0.05226131       2           negative
51 0.23382594       2           negative

In [56]:
# 設定 ---------------------------
important_targets <- c("Jsc", "PCEmax", "Voc", "FF")  # 重視する目的変数
abs_diff_thr <- 0.05                    # |S-非S| のしきい値
min_imp_targets <- 1                    # 重要ターゲットの中で何個以上効いていれば採用するか
min_total_targets_same_sign <- 2        # 何目的変数で同じ向きなら「一貫」とみなすか

diff_tbl <- read_csv(file_feat_diff, show_col_types = FALSE)

# 1) 絶対差が大きい行だけ
diff_large <- diff_tbl %>%
  mutate(abs_diff = abs(diff_S_minus_nonS)) %>%
  filter(abs_diff >= abs_diff_thr)

# 2) 重要ターゲットでの効き具合
imp_effect <- diff_large %>%
  filter(target %in% important_targets) %>%
  group_by(feature) %>%
  summarise(
    n_imp_targets   = n(),
    max_abs_diff_imp = max(abs_diff),
    .groups = "drop"
  ) %>%
  filter(n_imp_targets >= min_imp_targets)

# 3) 全ターゲットでの符号の一貫性
sign_consistency <- diff_large %>%
  mutate(sign = sign(diff_S_minus_nonS)) %>%
  group_by(feature) %>%
  summarise(
    n_targets       = n(),
    n_pos           = sum(sign > 0),
    n_neg           = sum(sign < 0),
    max_abs_diff_all = max(abs_diff),
    .groups = "drop"
  ) %>%
  mutate(
    n_same_sign = pmax(n_pos, n_neg),
    sign_major  = dplyr::case_when(
      n_pos > n_neg ~ "positive",
      n_neg > n_pos ~ "negative",
      TRUE          ~ "mixed"
    )
  ) %>%
  filter(
    sign_major != "mixed",
    n_same_sign >= min_total_targets_same_sign
  )

# 4) 両方の条件を満たす「怪しい変数」
suspicious_vars <- imp_effect %>%
  inner_join(sign_consistency, by = "feature") %>%
  arrange(desc(max_abs_diff_imp))

file_suspicious <- file.path(base_path, "suspicious_features_allNumeric_Jsc_PCEmax.csv")
write_csv(suspicious_vars, file_suspicious)

suspicious_vars

    feature                 n_imp_targets max_abs_diff_imp n_targets n_pos
1   Error                   4             1.0019539        4         4
2   Predicted               3             0.8515157        3         2
3   Observed                4             0.7051487        4         0
4   UVIntP                  2             0.4332369        2         0
5   X149.4                  2             0.4266010        2         0
6   X141.4                  2             0.4246305        2         0
7   X108.4                  2             0.4128079        2         0
8   X101.4                  2             0.4091954        2         0
9   X150.4                  2             0.3769882        2         0
10  X97.4                   2             0.3513957        2         0
11  X160.4                  2             0.3244501        2         0
12  X115.4                  2             0.3224196        2         0
13  X155.4                  2             0.3224196        2         0
14  X159.4                  2             0.3206430        2         0
15  X114.4                  2             0.3193739        2         0
16  X116.4                  2             0.3193739        2         0
17  Additivesname_          3             0.3165846        3         2
18  X129.4                  2             0.3061760        2         0
19  X128.4                  2             0.3051607        2         0
20  SMILESsnamenM_PC61BM    2             0.3021106        2         0
21  X136.4                  2             0.2998358        2         0
22  namessolvent1_CF        3             0.2975369        3         2
23  X153.4                  2             0.2950085        2         0
24  X164.4                  2             0.2923858        2         0
25  X100.4                  2             0.2840722        2         0
26  Lay5electronodes1_LiF   3             0.2783920        3         2
27  X146.4                  2             0.2709360        2         0
28  Lay6electronodes2_      3             0.2683087        3         2
29  Lay2Mname_PEDOTPSS      2             0.2669347        2         2
30  TAtimelast              3             0.2641396        3         1
... ...                     ...           ...              ...       ...
59  HOMOp1M                 2             0.16900311       2         2
60  TDtime                  2             0.16676653       2         2
61  Abandp1MSol1            3             0.16369947       3         2
62  namessolvent1_          3             0.16206859       3         2
63  Abandp1Mfilm3           3             0.15202567       3         2
64  X33.4                   2             0.14610829       2         0
65  X158.4                  2             0.14351396       2         0
66  HOMODFTp1M              2             0.14311731       2         0
67  RationM                 2             0.13879726       2         2
68  Ratiop1M                2             0.13804611       2         0
69  SCspeed1                3             0.13118381       3         3
70  LUMOECp1M               2             0.12356205       2         2
71  Lay6electronodes2_Al    2             0.11822660       2         0
72  EgDFTp1M                2             0.11452591       2         0
73  TAtime1                 2             0.11394941       2         2
74  X102.4                  2             0.11034483       2         0
75  Lay5electronodes1_MoOx  3             0.10673367       3         1
76  Lay2Mname_              3             0.10391960       3         2
77  X47.4                   2             0.10311987       2         2
78  SMILESsnamep1M_DTPDPP3T 2             0.09358433       2         2
79  SCtime1                 2             0.09165709       2         0
80  SMILESsnamep1M_PPDT2FBT 2             0.09163691       2         2
81  E12oxp1M                3             0.08505019       3         2
82  solutionPI              2             0.07968076       2         0
83  Aarea                   2             0.07347052       2         0
84  SMILESsnamep1M_DTA      2             0.06834171       2         0
85  SMILESsnamep1M_PNTz4T   2             0.06030151       2         0
86  Lay5electronodes1_MoO3  3             0.05628141       3         0
87  SMILESsnamep1M_PBDTFQT  2             0.05226131       2         0
88  SMILESsnamep1M_PTB7     2             0.05226131       2         0
    n_neg max_abs_diff_all n_same_sign sign_major
1   0     1.0019539        4           positive
2   1     0.8515157        2           positive
3   4     0.7051487        4           negative
4   2     0.4332369        2           negative
5   2     0.4266010        2           negative
6   2     0.4246305        2           negative
7   2     0.4128079        2           negative
8   2     0.4091954        2           negative
9   2     0.3769882        2           negative
10  2     0.3513957        2           negative
11  2     0.3244501        2           negative
12  2     0.3224196        2           negative
13  2     0.3224196        2           negative
14  2     0.3206430        2           negative
15  2     0.3193739        2           negative
16  2     0.3193739        2           negative
17  1     0.3165846        2           positive
18  2     0.3061760        2           negative
19  2     0.3051607        2           negative
20  2     0.3021106        2           negative
21  2     0.2998358        2           negative
22  1     0.2975369        2           positive
23  2     0.2950085        2           negative
24  2     0.2923858        2           negative
25  2     0.2840722        2           negative
26  1     0.2783920        2           positive
27  2     0.2709360        2           negative
28  1     0.2683087        2           positive
29  0     0.2669347        2           positive
30  2     0.2641396        2           negative
... ...   ...              ...         ...
59  0     0.16900311       2           positive
60  0     0.16676653       2           positive
61  1     0.16369947       2           positive
62  1     0.16206859       2           positive
63  1     0.15202567       2           positive
64  2     0.14610829       2           negative
65  2     0.14351396       2           negative
66  2     0.14311731       2           negative
67  0     0.13879726       2           positive
68  2     0.13804611       2           negative
69  0     0.13118381       3           positive
70  0     0.12356205       2           positive
71  2     0.11822660       2           negative
72  2     0.11452591       2           negative
73  0     0.11394941       2           positive
74  2     0.11034483       2           negative
75  2     0.10673367       2           negative
76  1     0.10391960       2           positive
77  0     0.10311987       2           positive
78  0     0.09358433       2           positive
79  2     0.09165709       2           negative
80  0     0.09163691       2           positive
81  1     0.08505019       2           positive
82  2     0.07968076       2           negative
83  2     0.07347052       2           negative
84  2     0.06834171       2           negative
85  2     0.06030151       2           negative
86  3     0.05628141       3           negative
87  2     0.05226131       2           negative
88  2     0.05226131       2           negative

In [57]:
library(dplyr)
library(readr)
library(ggplot2)
library(purrr)

base_path     <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix <- "outlier_results"

targets <- c("PCEmax", "Jsc", "Voc", "FF")

# 注目する変数（このリストにさっきの suspicious な変数を追加していけばOK）
focus_vars <- c("UVIntP", "TAtimelast", "Aarea", "EgDFTp1M")

# 「Error が大きいサンプル」の定義
# ここでは各ターゲットごとに AbsError の上位 5% を「Error大」とする例。
top_error_frac <- 0.05

In [61]:
analyze_target <- function(tg) {
  cat("\n====================\n")
  cat("Target:", tg, "\n")
  cat("====================\n\n")
  
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))
  
  dat <- read_csv(file_all, show_col_types = FALSE)
  
  # 必要な列があるかざっと確認
  needed <- c("Observed", "Predicted", "AbsError", "is_S")
  miss   <- setdiff(needed, names(dat))
  if (length(miss) > 0) {
    cat("[WARN]", tg, ": 必要な列が欠けています:", paste(miss, collapse = ", "), "\n")
    return(invisible(NULL))
  }
  
  # Error 大サンプルの閾値（上位 top_error_frac）
  thr_err <- quantile(dat$AbsError, probs = 1 - top_error_frac, na.rm = TRUE)
  dat <- dat %>%
    mutate(
      is_high_error = AbsError >= thr_err
    )
  
  cat("AbsError しきい値 (上位", top_error_frac*100, "%): ", thr_err, "\n", sep = "")
  cat("  高誤差サンプル数:", sum(dat$is_high_error, na.rm = TRUE),
      "/", nrow(dat), "\n")
  cat("  S (is_S=TRUE)   数:", sum(dat$is_S, na.rm = TRUE), "\n\n")
  
  # 注目変数が存在するものだけを対象に
  vars_exist <- intersect(focus_vars, names(dat))
  if (length(vars_exist) == 0) {
    cat("[INFO]", tg, ": 注目変数が1つも存在しません。\n")
  }
  
  # 各変数について、S/非S と高誤差/非高誤差の要約をコンソールに出す
  for (v in vars_exist) {
    cat("---- 変数:", v, " ----\n")
    tmp <- dat %>%
      group_by(is_S, is_high_error) %>%
      summarise(
        n    = n(),
        mean = mean(.data[[v]], na.rm = TRUE),
        sd   = sd(.data[[v]],   na.rm = TRUE),
        .groups = "drop"
      )
    print(tmp)
    cat("\n")
  }
  
  # プロット出力用フォルダ
  plot_dir <- file.path(out_dir, "plots_focusVars")
  if (!dir.exists(plot_dir)) dir.create(plot_dir, recursive = TRUE)
  
  # 1) 注目変数のヒストグラム（S/非S + 高誤差色分け）
  for (v in vars_exist) {
    p_hist <- ggplot(dat, aes(x = .data[[v]], fill = interaction(is_S, is_high_error))) +
      geom_histogram(position = "identity", alpha = 0.5, bins = 30, color = "black") +
      theme_bw() +
      labs(
        title = paste0(tg, " - Histogram of ", v),
        fill  = "is_S.is_high_error"
      )
    ggsave(
      filename = file.path(plot_dir, paste0("hist_", tg, "_", v, ".png")),
      plot     = p_hist, width = 6, height = 4
    )
    
    # 箱ひげ（S/非S × 高誤差）
    p_box <- ggplot(dat, aes(x = interaction(is_S, is_high_error), y = .data[[v]], fill = is_S)) +
      geom_boxplot(outlier.alpha = 0.5) +
      theme_bw() +
      labs(
        title = paste0(tg, " - Boxplot of ", v),
        x     = "is_S.is_high_error"
      )
    ggsave(
      filename = file.path(plot_dir, paste0("box_", tg, "_", v, ".png")),
      plot     = p_box, width = 5, height = 4
    )
  }
  
  # 2) Obs vs Pred 図上での位置（S/非S + 高誤差で色分け）
  dat <- dat %>%
    mutate(
      group_flag = case_when(
        is_S & is_high_error  ~ "S & highErr",
        is_S & !is_high_error ~ "S & normalErr",
        !is_S & is_high_error ~ "nonS & highErr",
        TRUE                  ~ "nonS & normalErr"
      )
    )
  
  p_scatter <- ggplot(dat,
                      aes(x = Observed, y = Predicted, color = group_flag)) +
    geom_point(alpha = 0.7) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
    theme_bw() +
    labs(
      title = paste0(tg, " - Obs vs Pred (colored by S/highError)"),
      color = "group"
    )
  
  ggsave(
    filename = file.path(plot_dir, paste0("obs_vs_pred_", tg, "_S_highErr.png")),
    plot     = p_scatter, width = 6, height = 5
  )
  
  cat("プロット出力先:", plot_dir, "\n\n")
  
  invisible(NULL)
}
walk(targets, analyze_target)

====================
Target: PCEmax
====================

AbsError <U+3057><U+304D><U+3044><U+5024> (<U+4E0A><U+4F4D>5%): 2.581999
  <U+9AD8><U+8AA4><U+5DEE><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  S (is_S=TRUE)   <U+6570>: 18

---- <U+5909><U+6570>: UVIntP  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.357 0.711
2 FALSE TRUE             35 -0.592 0.605
3 TRUE  TRUE             18 -0.798 0.473

---- <U+5909><U+6570>: TAtimelast  ----
# A tibble: 3 x 5
  is_S  is_high_error     n    mean    sd
  <lgl> <lgl>         <int>   <dbl> <dbl>
1 FALSE FALSE           992  0.124  0.932
2 FALSE TRUE             35  0.0580 0.948
3 TRUE  TRUE             18 -0.110  0.851

---- <U+5909><U+6570>: Aarea  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.790 0.363
2 FALSE TRUE             35 -0.784 0.322
3 TRUE  TRUE             18 -0.863 0.107

---- <U+5909><U+6570>: EgDFTp1M  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.164 0.722
2 FALSE TRUE             35 -0.210 0.708
3 TRUE  TRUE             18 -0.240 0.648

<U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/plots_focusVars


====================
Target: Jsc
====================

AbsError <U+3057><U+304D><U+3044><U+5024> (<U+4E0A><U+4F4D>5%): 4.878994
  <U+9AD8><U+8AA4><U+5DEE><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  S (is_S=TRUE)   <U+6570>: 50

---- <U+5909><U+6570>: UVIntP  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.360 0.713
2 FALSE TRUE              3 -0.697 0.525
3 TRUE  TRUE             50 -0.595 0.565

---- <U+5909><U+6570>: TAtimelast  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992  0.106 0.932
2 FALSE TRUE              3 -0.298 1.13
3 TRUE  TRUE             50  0.369 0.868

---- <U+5909><U+6570>: Aarea  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.787 0.367
2 FALSE TRUE              3 -0.892 0.102
3 TRUE  TRUE             50 -0.856 0.104

---- <U+5909><U+6570>: EgDFTp1M  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean     sd
  <lgl> <lgl>         <int>  <dbl>  <dbl>
1 FALSE FALSE           992 -0.163 0.720
2 FALSE TRUE              3  0.517 0.0230
3 TRUE  TRUE             50 -0.276 0.707

<U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/plots_focusVars


====================
Target: Voc
====================

AbsError <U+3057><U+304D><U+3044><U+5024> (<U+4E0A><U+4F4D>5%): 0.1582603
  <U+9AD8><U+8AA4><U+5DEE><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  S (is_S=TRUE)   <U+6570>: 60

[INFO] Voc : <U+6CE8><U+76EE><U+5909><U+6570><U+304C>1<U+3064><U+3082><U+5B58><U+5728><U+3057><U+307E><U+305B><U+3093><U+3002>
<U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/plots_focusVars


====================
Target: FF
====================

AbsError <U+3057><U+304D><U+3044><U+5024> (<U+4E0A><U+4F4D>5%): 0.1629467
  <U+9AD8><U+8AA4><U+5DEE><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  S (is_S=TRUE)   <U+6570>: 30

---- <U+5909><U+6570>: UVIntP  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.369 0.708
2 FALSE TRUE             23 -0.518 0.695
3 TRUE  TRUE             30 -0.373 0.710

---- <U+5909><U+6570>: TAtimelast  ----
# A tibble: 3 x 5
  is_S  is_high_error     n    mean    sd
  <lgl> <lgl>         <int>   <dbl> <dbl>
1 FALSE FALSE           992  0.119  0.933
2 FALSE TRUE             23  0.277  0.870
3 TRUE  TRUE             30 -0.0737 0.918

---- <U+5909><U+6570>: Aarea  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.793 0.351
2 FALSE TRUE             23 -0.742 0.555
3 TRUE  TRUE             30 -0.749 0.437

---- <U+5909><U+6570>: EgDFTp1M  ----
# A tibble: 3 x 5
  is_S  is_high_error     n   mean    sd
  <lgl> <lgl>         <int>  <dbl> <dbl>
1 FALSE FALSE           992 -0.166 0.719
2 FALSE TRUE             23 -0.203 0.763
3 TRUE  TRUE             30 -0.162 0.745

<U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/plots_focusVars

In [62]:
library(dplyr)
library(readr)
library(ggplot2)
library(purrr)
library(tidyr)

# 設定 -----------------------------
base_path     <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix <- "outlier_results"

target <- "Jsc"  # ここを PCEmax / Voc / FF に変えれば他の目的変数も見られる

# 注目する説明変数
focus_vars <- c(
  "UVIntP", "TAtimelast", "Aarea", "EgDFTp1M",   # 例: 怪しいとわかっているもの
  "TAtime1"                                      # 必要に応じて追加
)

# データ読み込み -------------------
out_dir  <- file.path(base_path, paste0(output_prefix, "_", target))
file_all <- file.path(out_dir, paste0("all_with_Sflag_", target, ".csv"))

dat <- read_csv(file_all, show_col_types = FALSE)

# 実際に存在する列だけに絞る
focus_vars <- intersect(focus_vars, names(dat))

if (length(focus_vars) == 0) {
  stop("指定した focus_vars がこの目的変数のデータに存在しません。")
}

# 目的変数・誤差など
y_var      <- "Observed"
yhat_var   <- "Predicted"
error_var  <- "AbsError"

# 「誤差が大きいサンプル」フラグ（上位5%）
top_error_frac <- 0.05
thr_err <- quantile(dat[[error_var]], probs = 1 - top_error_frac, na.rm = TRUE)

dat <- dat %>%
  mutate(
    is_high_error = !!as.name(error_var) >= thr_err
  )

cat("Target:", target, "\n")
cat("  高誤差しきい値 AbsError >=", thr_err, "\n")
cat("  高誤差サンプル数:", sum(dat$is_high_error, na.rm = TRUE), "/", nrow(dat), "\n\n")

Target: Jsc
  <U+9AD8><U+8AA4><U+5DEE><U+3057><U+304D><U+3044><U+5024> AbsError >= 4.878994
  <U+9AD8><U+8AA4><U+5DEE><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045

In [63]:
# long 形式にして facet_wrap でまとめて描く
plot_df <- dat %>%
  select(all_of(c(y_var, focus_vars, "is_S", "is_high_error"))) %>%
  pivot_longer(cols = all_of(focus_vars),
               names_to = "feature",
               values_to = "x_val")

# S / 非S × 高誤差の組み合わせを色で区別
plot_df <- plot_df %>%
  mutate(
    group_flag = case_when(
      is_S & is_high_error  ~ "S & highErr",
      is_S & !is_high_error ~ "S & normalErr",
      !is_S & is_high_error ~ "nonS & highErr",
      TRUE                  ~ "nonS & normalErr"
    )
  )

p_scatter_grid <- ggplot(plot_df,
                         aes(x = x_val, y = .data[[y_var]], color = group_flag)) +
  geom_point(alpha = 0.6, size = 1.2) +
  theme_bw() +
  facet_wrap(~ feature, scales = "free_x") +
  labs(
    title = paste0("Target = ", target,
                   " : ", y_var, " vs multiple features"),
    x     = "feature value",
    y     = y_var,
    color = "group"
  )

ggsave(
  filename = file.path(out_dir,
                       paste0("multiFeature_vs_", y_var, "_", target, ".png")),
  plot     = p_scatter_grid,
  width    = 10,
  height   = 8
)

In [64]:
# 箱ひげ: 目的変数ごとの高誤差 vs 非高誤差での分布差
p_box_grid <- plot_df %>%
  mutate(err_flag = ifelse(is_high_error, "highErr", "normalErr")) %>%
  ggplot(aes(x = err_flag, y = x_val, fill = err_flag)) +
  geom_boxplot(outlier.alpha = 0.5) +
  theme_bw() +
  facet_wrap(~ feature, scales = "free_y") +
  labs(
    title = paste0("Target = ", target,
                   " : feature distributions (highErr vs normal)"),
    x = "error group",
    y = "feature value"
  )

ggsave(
  filename = file.path(out_dir,
                       paste0("multiFeature_box_highErr_vs_normal_", target, ".png")),
  plot     = p_box_grid,
  width    = 10,
  height   = 8
)

In [65]:
cat("=== ", target, " : 高誤差 vs 非高誤差 の要約 ===\n")

for (v in focus_vars) {
  cat("\n--- feature:", v, " ---\n")
  tmp <- dat %>%
    mutate(err_flag = ifelse(is_high_error, "highErr", "normalErr")) %>%
    group_by(err_flag) %>%
    summarise(
      n    = n(),
      mean = mean(.data[[v]], na.rm = TRUE),
      sd   = sd(.data[[v]],   na.rm = TRUE),
      q1   = quantile(.data[[v]], 0.25, na.rm = TRUE),
      med  = median(.data[[v]], na.rm = TRUE),
      q3   = quantile(.data[[v]], 0.75, na.rm = TRUE),
      .groups = "drop"
    )
  print(tmp)
}

===  Jsc  : <U+9AD8><U+8AA4><U+5DEE> vs <U+975E><U+9AD8><U+8AA4><U+5DEE> <U+306E><U+8981><U+7D04> ===

--- feature: UVIntP  ---
# A tibble: 2 x 7
  err_flag      n   mean    sd    q1   med      q3
  <chr>     <int>  <dbl> <dbl> <dbl> <dbl>   <dbl>
1 highErr      53 -0.601 0.558    -1    -1 -0.0909
2 normalErr   992 -0.360 0.713    -1    -1  0.364

--- feature: TAtimelast  ---
# A tibble: 2 x 7
  err_flag      n  mean    sd     q1   med    q3
  <chr>     <int> <dbl> <dbl>  <dbl> <dbl> <dbl>
1 highErr      53 0.331 0.885 -0.895     1     1
2 normalErr   992 0.106 0.932 -0.895     1     1

--- feature: Aarea  ---
# A tibble: 2 x 7
  err_flag      n   mean    sd     q1    med     q3
  <chr>     <int>  <dbl> <dbl>  <dbl>  <dbl>  <dbl>
1 highErr      53 -0.858 0.103 -0.969 -0.865 -0.744
2 normalErr   992 -0.787 0.367 -0.969 -0.846 -0.723

--- feature: EgDFTp1M  ---
# A tibble: 2 x 7
  err_flag      n   mean    sd     q1   med    q3
  <chr>     <int>  <dbl> <dbl>  <dbl> <dbl> <dbl>
1 highErr      53 -0.231 0.711 -1     0.148 0.494
2 normalErr   992 -0.163 0.720 -0.961 0.148 0.494

--- feature: TAtime1  ---
# A tibble: 2 x 7
  err_flag      n   mean    sd     q1    med      q3
  <chr>     <int>  <dbl> <dbl>  <dbl>  <dbl>   <dbl>
1 highErr      53 -0.431 0.451 -0.695 -0.695 -0.0169
2 normalErr   992 -0.557 0.365 -0.695 -0.695 -0.525

In [66]:
library(dplyr)
library(readr)
library(purrr)

# ===== 設定 ======================================================

base_path     <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix <- "outlier_results"

# 対象とする目的変数
targets <- c("PCEmax", "Jsc", "Voc", "FF")

# 誤差列名（あなたの環境に合わせて）
error_var <- "AbsError"

# 外れサンプルとみなす割合（上位何%の誤差を外れとするか）
top_error_frac <- 0.05


# ===== 1目的変数ぶんの処理をする関数 ============================

analyze_target_outlier_causes <- function(tg) {
  cat("\n=====================================\n")
  cat("Target:", tg, "\n")
  cat("=====================================\n")
  
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))
  
  if (!file.exists(file_all)) {
    cat("[WARN]", file_all, "が見つからないためスキップします。\n")
    return(invisible(NULL))
  }
  
  dat <- read_csv(file_all, show_col_types = FALSE)
  
  if (!error_var %in% names(dat)) {
    cat("[WARN]", tg, ": 列", error_var, "がありません。スキップします。\n")
    return(invisible(NULL))
  }
  
  # --- 1) 外れサンプルを特定 -----------------------------------
  thr_err <- quantile(dat[[error_var]], probs = 1 - top_error_frac, na.rm = TRUE)
  
  dat <- dat %>%
    mutate(
      is_outlier = .data[[error_var]] >= thr_err
    )
  
  n_out  <- sum(dat$is_outlier, na.rm = TRUE)
  n_all  <- nrow(dat)
  
  cat("  外れしきい値:", error_var, ">=", thr_err, "\n")
  cat("  外れサンプル数:", n_out, "/", n_all, "\n")
  
  if (n_out == 0 || n_out == n_all) {
    cat("  [INFO] 全部 or 全く外れになっているため、原因分析をスキップします。\n")
    return(invisible(NULL))
  }
  
  # --- 2) 説明変数の平均乖離を計算 -----------------------------
  # 説明変数として扱わない列
  exclude_cols <- c(
    "Observed", "Predicted", error_var,
    "is_outlier", "is_S",      # フラグ類
    "SampleID", "foldID"      # ID系があれば
  )
  
  num_cols <- names(dat)[sapply(dat, is.numeric)]
  feature_cols <- setdiff(num_cols, exclude_cols)
  
  if (length(feature_cols) == 0) {
    cat("  [INFO] 説明変数として扱える数値列がありません。\n")
    return(invisible(NULL))
  }
  
  cause_tbl <- map_dfr(
    feature_cols,
    function(v) {
      tmp <- dat %>%
        group_by(is_outlier) %>%
        summarise(
          n    = n(),
          mean = mean(.data[[v]], na.rm = TRUE),
          sd   = sd(.data[[v]],   na.rm = TRUE),
          .groups = "drop"
        )
      
      row_out  <- tmp[tmp$is_outlier == TRUE, , drop = FALSE]
      row_norm <- tmp[tmp$is_outlier == FALSE, , drop = FALSE]
      
      if (nrow(row_out) == 0 || nrow(row_norm) == 0) return(NULL)
      
      tibble(
        feature         = v,
        n_outlier       = row_out$n,
        n_normal        = row_norm$n,
        mean_outlier    = row_out$mean,
        mean_normal     = row_norm$mean,
        sd_outlier      = row_out$sd,
        sd_normal       = row_norm$sd,
        diff_mean       = mean_outlier - mean_normal,
        abs_diff_mean   = abs(diff_mean)
      )
    }
  )
  
  if (nrow(cause_tbl) == 0) {
    cat("  [INFO] 有効な要約が作れませんでした（NAが多いなど）。\n")
    return(invisible(NULL))
  }
  
  cause_tbl <- cause_tbl %>%
    arrange(desc(abs_diff_mean))
  
  cat("  上位5つの原因候補変数:\n")
  print(head(cause_tbl, 5))
  
  # --- 3) 結果を書き出し --------------------------------------
  file_cause <- file.path(
    out_dir,
    paste0("outlier_feature_divergence_", tg, ".csv")
  )
  
  write_csv(cause_tbl, file_cause)
  cat("  書き出し:", file_cause, "\n")
  
  invisible(NULL)
}


# ===== 4目的変数をまとめて処理 ==================================

walk(targets, analyze_target_outlier_causes)

=====================================
Target: PCEmax
=====================================
  <U+5916><U+308C><U+3057><U+304D><U+3044><U+5024>: AbsError >= 2.581999
  <U+5916><U+308C><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+4E0A><U+4F4D>5<U+3064><U+306E><U+539F><U+56E0><U+5019><U+88DC><U+5909><U+6570>:
# A tibble: 5 x 9
  feature       n_outlier n_normal mean_outlier mean_normal sd_outlier sd_normal
  <chr>             <int>    <int>        <dbl>       <dbl>      <dbl>     <dbl>
1 SMILESsnamen~        53      992       0.358       0.0423      0.942     1.00
2 Lay6electron~        53      992       0.0189      0.331       1.01      0.944
3 UVIntP               53      992      -0.662      -0.357       0.568     0.711
4 SMILESsnamen~        53      992      -0.472      -0.177       0.890     0.985
5 Lay6electron~        53      992      -0.547      -0.800       0.845     0.600
# i 2 more variables: diff_mean <dbl>, abs_diff_mean <dbl>
  <U+66F8><U+304D><U+51FA><U+3057>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/outlier_feature_divergence_PCEmax.csv

=====================================
Target: Jsc
=====================================
  <U+5916><U+308C><U+3057><U+304D><U+3044><U+5024>: AbsError >= 4.878994
  <U+5916><U+308C><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+4E0A><U+4F4D>5<U+3064><U+306E><U+539F><U+56E0><U+5019><U+88DC><U+5909><U+6570>:
# A tibble: 5 x 9
  feature       n_outlier n_normal mean_outlier mean_normal sd_outlier sd_normal
  <chr>             <int>    <int>        <dbl>       <dbl>      <dbl>     <dbl>
1 Error                53      992        0.457      0.0102      6.70      1.94
2 namessolvent~        53      992       -0.509     -0.171       0.869     0.986
3 Lay2Mname_PE~        53      992        0.698      0.411       0.723     0.912
4 Lay5electron~        53      992       -0.396     -0.679       0.927     0.734
5 SMILESsnamen~        53      992       -0.434     -0.179       0.910     0.984
# i 2 more variables: diff_mean <dbl>, abs_diff_mean <dbl>
  <U+66F8><U+304D><U+51FA><U+3057>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/outlier_feature_divergence_Jsc.csv

=====================================
Target: Voc
=====================================
  <U+5916><U+308C><U+3057><U+304D><U+3044><U+5024>: AbsError >= 0.1582603
  <U+5916><U+308C><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+4E0A><U+4F4D>5<U+3064><U+306E><U+539F><U+56E0><U+5019><U+88DC><U+5909><U+6570>:
# A tibble: 5 x 9
  feature n_outlier n_normal mean_outlier mean_normal sd_outlier sd_normal
  <chr>       <int>    <int>        <dbl>       <dbl>      <dbl>     <dbl>
1 X149.4         53      992        0.509       0.928      0.505     0.258
2 X141.4         53      992        0.509       0.927      0.505     0.260
3 X150.4         53      992        0.434       0.843      0.500     0.364
4 X160.4         53      992        0.585       0.941      0.497     0.237
5 X115.4         53      992        0.585       0.939      0.497     0.240
# i 2 more variables: diff_mean <dbl>, abs_diff_mean <dbl>
  <U+66F8><U+304D><U+51FA><U+3057>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/outlier_feature_divergence_Voc.csv

=====================================
Target: FF
=====================================
  <U+5916><U+308C><U+3057><U+304D><U+3044><U+5024>: AbsError >= 0.1629467
  <U+5916><U+308C><U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+4E0A><U+4F4D>5<U+3064><U+306E><U+539F><U+56E0><U+5019><U+88DC><U+5909><U+6570>:
# A tibble: 5 x 9
  feature       n_outlier n_normal mean_outlier mean_normal sd_outlier sd_normal
  <chr>             <int>    <int>        <dbl>       <dbl>      <dbl>     <dbl>
1 X124.4               53      992       -0.660      -0.369      0.758     0.930
2 X130.4               53      992       -0.660      -0.373      0.758     0.928
3 X88.4                53      992        0.660       0.946      0.758     0.326
4 X67.4                53      992       -0.774      -0.510      0.640     0.861
5 Lay6electron~        53      992       -0.283      -0.540      0.968     0.842
# i 2 more variables: diff_mean <dbl>, abs_diff_mean <dbl>
  <U+66F8><U+304D><U+51FA><U+3057>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/outlier_feature_divergence_FF.csv

In [67]:
library(dplyr)
library(readr)
library(ggplot2)
library(purrr)
library(tidyr)

base_path     <- "/Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier"
output_prefix <- "outlier_results"

targets    <- c("PCEmax", "Jsc", "Voc", "FF")
error_var  <- "AbsError"      # 誤差列
top_k_feat <- 5               # 各目的変数で上位いくつの原因候補変数を見るか
top_error_frac <- 0.05        # highErr の定義（AbsError 上位5%）


analyze_target_plots <- function(tg) {
  cat("\n==============================\n")
  cat("Target:", tg, "\n")
  cat("==============================\n")
  
  out_dir  <- file.path(base_path, paste0(output_prefix, "_", tg))
  file_all <- file.path(out_dir, paste0("all_with_Sflag_", tg, ".csv"))
  file_cause <- file.path(out_dir, paste0("outlier_feature_divergence_", tg, ".csv"))
  
  if (!file.exists(file_all)) {
    cat("[WARN]", file_all, "がありません。スキップ。\n")
    return(invisible(NULL))
  }
  if (!file.exists(file_cause)) {
    cat("[WARN]", file_cause, "がありません（原因候補ランキングが未作成）。スキップ。\n")
    return(invisible(NULL))
  }
  
  dat <- read_csv(file_all, show_col_types = FALSE)
  cause_tbl <- read_csv(file_cause, show_col_types = FALSE)
  
  # highErr フラグを付与（安全のため再計算）
  if (!error_var %in% names(dat)) {
    cat("[WARN]", tg, ": 列", error_var, "がありません。スキップ。\n")
    return(invisible(NULL))
  }
  
  thr_err <- quantile(dat[[error_var]], probs = 1 - top_error_frac, na.rm = TRUE)
  dat <- dat %>%
    mutate(
      is_high_error = .data[[error_var]] >= thr_err
    )
  
  cat("  highErr しきい値:", error_var, ">=", thr_err, "\n")
  cat("  highErr サンプル数:", sum(dat$is_high_error, na.rm = TRUE),
      "/", nrow(dat), "\n")
  
  # 上位 top_k_feat の原因候補変数を取得
  top_feats <- cause_tbl %>%
    arrange(desc(abs_diff_mean)) %>%
    slice_head(n = top_k_feat) %>%
    pull(feature)
  
  # 実際に存在しない列が入っていたら除く
  top_feats <- intersect(top_feats, names(dat))
  if (length(top_feats) == 0) {
    cat("  [INFO] 上位候補変数がデータに存在しません。\n")
    return(invisible(NULL))
  }
  
  cat("  プロット対象の上位候補変数:\n")
  print(top_feats)
  
  # プロット出力先
  plot_dir <- file.path(out_dir, "plots_outlier_causes_top")
  if (!dir.exists(plot_dir)) dir.create(plot_dir, recursive = TRUE)
  
  # 目的変数・予測値
  if (!all(c("Observed", "Predicted") %in% names(dat))) {
    cat("  [WARN] Observed / Predicted 列がないため Obs vs Pred 図はスキップします。\n")
  }
  
  # long 形式に変換
  plot_df <- dat %>%
    select(all_of(c("Observed", "Predicted", "is_high_error", "is_S", top_feats))) %>%
    pivot_longer(cols = all_of(top_feats),
                 names_to  = "feature",
                 values_to = "x_val") %>%
    mutate(
      group_flag = case_when(
        is_S & is_high_error  ~ "S & highErr",
        is_S & !is_high_error ~ "S & normalErr",
        !is_S & is_high_error ~ "nonS & highErr",
        TRUE                  ~ "nonS & normalErr"
      ),
      err_flag = ifelse(is_high_error, "highErr", "normalErr")
    )
  
  # 1) highErr vs normal の箱ひげ・ヒストグラム -----------------
  
  # 箱ひげ図（highErr vs normal）
  p_box <- ggplot(plot_df, aes(x = err_flag, y = x_val, fill = err_flag)) +
    geom_boxplot(outlier.alpha = 0.4) +
    theme_bw() +
    facet_wrap(~ feature, scales = "free_y") +
    labs(
      title = paste0("Target = ", tg,
                     " : feature distributions (highErr vs normal)"),
      x = "error group",
      y = "feature value"
    )
  
  ggsave(
    filename = file.path(plot_dir, paste0("box_highErr_vs_normal_", tg, ".png")),
    plot     = p_box,
    width    = 10, height = 8
  )
  
  # ヒストグラム（highErr / normal を色分け）
  p_hist <- ggplot(plot_df,
                   aes(x = x_val, fill = err_flag)) +
    geom_histogram(position = "identity", alpha = 0.5,
                   bins = 30, color = "black") +
    theme_bw() +
    facet_wrap(~ feature, scales = "free_x") +
    labs(
      title = paste0("Target = ", tg,
                     " : histograms of top features (highErr vs normal)"),
      x = "feature value",
      y = "count",
      fill = "error group"
    )
  
  ggsave(
    filename = file.path(plot_dir, paste0("hist_highErr_vs_normal_", tg, ".png")),
    plot     = p_hist,
    width    = 10, height = 8
  )
  
  # 2) Obs vs Pred における highErr 点の分布 --------------------
  if (all(c("Observed", "Predicted") %in% names(dat))) {
    p_scatter <- ggplot(dat,
                        aes(x = Observed, y = Predicted,
                            color = is_high_error, shape = is_S)) +
      geom_point(alpha = 0.7) +
      geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
      theme_bw() +
      scale_color_manual(values = c("FALSE" = "gray50", "TRUE" = "red")) +
      labs(
        title = paste0("Target = ", tg,
                       " : Obs vs Pred (highErr in red)"),
        color = "is_high_error",
        shape = "is_S"
      )
    
    ggsave(
      filename = file.path(plot_dir, paste0("obs_vs_pred_highErr_", tg, ".png")),
      plot     = p_scatter,
      width    = 7, height = 6
    )
  }
  
  cat("  プロット出力先:", plot_dir, "\n")
  invisible(NULL)
}

# 4目的変数まとめて実行
walk(targets, analyze_target_plots)

==============================
Target: PCEmax
==============================
  highErr <U+3057><U+304D><U+3044><U+5024>: AbsError >= 2.581999
  highErr <U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+30D7><U+30ED><U+30C3><U+30C8><U+5BFE><U+8C61><U+306E><U+4E0A><U+4F4D><U+5019><U+88DC><U+5909><U+6570>:
[1] "SMILESsnamenM_PC71BM" "Lay6electronodes2_Al" "UVIntP"
[4] "SMILESsnamenM_PC61BM" "Lay6electronodes2_Ag"
  <U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_PCEmax/plots_outlier_causes_top

==============================
Target: Jsc
==============================
  highErr <U+3057><U+304D><U+3044><U+5024>: AbsError >= 4.878994
  highErr <U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+30D7><U+30ED><U+30C3><U+30C8><U+5BFE><U+8C61><U+306E><U+4E0A><U+4F4D><U+5019><U+88DC><U+5909><U+6570>:
[1] "Error"                 "namessolvent1_oDCB"    "Lay2Mname_PEDOTPSS"
[4] "Lay5electronodes1_LiF" "SMILESsnamenM_PC61BM"
  <U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Jsc/plots_outlier_causes_top

==============================
Target: Voc
==============================
  highErr <U+3057><U+304D><U+3044><U+5024>: AbsError >= 0.1582603
  highErr <U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+30D7><U+30ED><U+30C3><U+30C8><U+5BFE><U+8C61><U+306E><U+4E0A><U+4F4D><U+5019><U+88DC><U+5909><U+6570>:
[1] "X149.4" "X141.4" "X150.4" "X160.4" "X115.4"
  <U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_Voc/plots_outlier_causes_top

==============================
Target: FF
==============================
  highErr <U+3057><U+304D><U+3044><U+5024>: AbsError >= 0.1629467
  highErr <U+30B5><U+30F3><U+30D7><U+30EB><U+6570>: 53 / 1045
  <U+30D7><U+30ED><U+30C3><U+30C8><U+5BFE><U+8C61><U+306E><U+4E0A><U+4F4D><U+5019><U+88DC><U+5909><U+6570>:
[1] "X124.4"             "X130.4"             "X88.4"
[4] "X67.4"              "Lay6electronodes2_"
  <U+30D7><U+30ED><U+30C3><U+30C8><U+51FA><U+529B><U+5148>: /Volumes/csbdeep11/_yasu-i/20250303_rebuiled/after_20251225/outlier/outlier_results_FF/plots_outlier_causes_top