In [2]:
if(!require(caret)){
  install.packages("caret")
  library(caret)
}

#setwd("~/Desktop")
if(!require(rcdk)){
  install.packages("rcdk")
  library(rcdk)
}
if(!require(fingerprint)){
  install.packages("fingerprint")
  library(fingerprint)
}

if(!require(pls)){
  install.packages("pls")
  library(pls)
}
if(!require(Metrics)){
  install.packages("Metrics")
  library(Metrics)
}
if(!require(monmlp)){
  install.packages("monmlp")
  library(monmlp)
}

if(!require(frbs)){
install.packages("frbs")
library(frbs)
}

if(!require(Rborist)){    
install.packages("Rborist")
library(Rborist)
}
if(!require(xgboost)){
install.packages("xgboost")
library(xgboost)
}
if(!require(RWeka)){    
install.packages("RWeka")
library(RWeka)
}

if(!require(RWekajars)){    
install.packages("RWekajars")
library(RWekajars)
}
    
# if(!require(extraTrees)){    
# install.packages("extraTrees")
# library(extraTrees)
# }
    
    
if(!require(randomForest)){    
install.packages("randomForest")
library(randomForest)
}

Loading required package: randomForest

randomForest 4.7-1.2

Type rfNews() to see new features/changes/bug fixes.


Attaching package: 'randomForest'


The following object is masked from 'package:ggplot2':

    margin

In [3]:
ifname01<-c("DataMerge20211220oh.csv")
ifname02<-c("DUM.csv")
#ifname1<-c("DataSet500_3.csv")
dataUsed01<-read.delim(ifname01,row.names=1,header=T,sep=",",as.is=TRUE,strip.white=FALSE)  
dataUsed02<-read.delim(ifname02,row.names=1,header=T,sep=",",as.is=TRUE,strip.white=FALSE)  
#df11<-read.delim(ifname11,row.names=1,header=T,sep=",",as.is=TRUE,strip.white=FALSE)  
#df12<-read.delim(ifname12,row.names=1,header=T,sep=",",as.is=TRUE,strip.white=FALSE)  

#columnList<-c("PCEave","PCEcal","PCEdiff","RatioinM","Ratioip1M","Ratioip2M","acRatiop1M","acRatiop2M","acRationM" )
#fmatrix12 <-data.frame(df10[, -which (colnames(df10)%in%columnList)])
#fmatrix13<-fmatrix12
dataUsed01
dataUsed02

     Lay2thickness Aonsetp1Mfilm MwkDap1M LUMOp1M MnkDap1M VolRatioS1
1    30            700                NA   NA       NA     NA
2    30            700                NA   NA       NA     NA
3    30            700                NA   NA       NA     NA
4    30            700                NA   NA       NA     NA
5    30             NA                NA   NA       NA     NA
6    30             NA                NA   NA       NA     NA
7    30             NA                NA   NA       NA     NA
8    30             NA                NA   NA       NA     NA
9    30             NA                NA   NA       NA     NA
10   30             NA                NA   NA       NA     NA
11   30             NA                NA   NA       NA     NA
12   NA            470            6.1009   NA     24.7     NA
13   NA            460            6.6049   NA     25.7     NA
14   30             NA           21.3444   NA     46.2     NA
15   30            750           16.2409   NA     40.3     NA
16   30             NA           11.4244   NA     33.8     NA
17   30             NA           12.9600   NA     36.0     NA
18   30             NA           20.2500   NA     45.0     NA
19   30             NA           19.1844   NA     43.8     NA
20   NA            685           22.5625  3.4     47.5     NA
21   NA            685           27.7729  3.2     52.7     NA
22   NA             NA            6.0025  3.2     24.5     NA
23   NA             NA           15.9201  3.2     39.9     NA
24   30             NA           15.4449   NA     39.3     NA
25   30             NA           18.7489   NA     43.3     NA
26   30             NA            5.7600   NA     24.0     NA
27   30             NA            5.6169   NA     23.7     NA
28   30             NA            5.4289   NA     23.3     NA
29   30             NA            5.6644   NA     23.8     NA
30   30             NA            5.6169   NA     23.7     NA
...  ...           ...           ...      ...     ...      ...
1019 60            730           73.90      NA    23.1      1
1020 60            730           73.90      NA    23.1      1
1021 60            718           47.30      NA    16.9      1
1022 60            718           47.30      NA    16.9      1
1023 60            718           47.30      NA    16.9      1
1024 60            702           59.10      NA    21.1      1
1025 60            702           59.10      NA    21.1      1
1026 60            702           59.10      NA    21.1      1
1027 60            702           59.10      NA    21.1      1
1028 60            702           59.10      NA    21.1      1
1029 60            632           22.90      NA    10.4     NA
1030 60            680           22.90      NA    10.4     NA
1031 60            696           65.60      NA    32.8     NA
1032 NA            632           13.00    3.48     6.2      1
1033 40             NA              NA    3.36      NA      1
1034 40             NA              NA    3.36      NA      1
1035 40             NA              NA    3.36      NA      1
1036 40             NA              NA    3.36      NA      1
1037 40             NA              NA    3.36      NA      1
1038 40            720           49.50    3.61    27.5      1
1039 40            707           33.30    3.58    22.2      1
1040 40            730           49.50    3.61    27.5      1
1041 40            730           49.50    3.61    27.5      1
1042 40            730           49.50    3.61    27.5      1
1043 40            730           49.50    3.61    27.5      1
1044 40            730           49.50    3.61    27.5      1
1045 40            730           49.50    3.61    27.5      1
1046 40            730           49.50    3.61    27.5      1
1047 40            765           32.64    3.67    19.2      1
1048 40            712           34.20    3.72    18.0      1
     Mmonomerp1M Lay6thickness HOMOp1M ALthickness ... namessolvent2_CF
1    NA          60              NA     50         ... 0
2    NA          60              NA    130         ... 0
3    NA          60              NA    130         ... 0
4    NA          60              NA    130         ... 0
5    NA          80            5.00     82         ... 0
6    NA          80            5.10     87         ... 0
7    NA          80            5.00     83         ... 0
8    NA          80            5.10     59         ... 0
9    NA          80            5.10     85         ... 0
10   NA          80            5.10    141         ... 0
11   NA          80            5.10    162         ... 0
12   NA          NA            5.43     NA         ... 0
13   NA          NA            5.50     NA         ... 0
14   NA          60              NA     80         ... 0
15   NA          60              NA     80         ... 0
16   NA          60              NA     80         ... 0
17   NA          60              NA     80         ... 0
18   NA          60              NA     80         ... 0
19   NA          80              NA     80         ... 0
20   NA          NA            5.00     NA         ... 0
21   NA          NA            4.90     NA         ... 0
22   NA          NA            4.90     NA         ... 0
23   NA          NA            4.90     NA         ... 0
24   NA          80              NA     75         ... 0
25   NA          80              NA     67         ... 0
26   NA          80              NA    124         ... 0
27   NA          80              NA    199         ... 0
28   NA          80              NA    123         ... 0
29   NA          80              NA    153         ... 0
30   NA          80              NA    223         ... 0
...  ...         ...           ...     ...             ...
1019 1389         80             NA     NA         ... 0
1020 1389         80             NA     NA         ... 0
1021 1425         80             NA     NA         ... 0
1022 1425         80             NA     NA         ... 0
1023 1425         80             NA     NA         ... 0
1024 1461         80             NA     NA         ... 0
1025 1461         80             NA     NA         ... 0
1026 1461         80             NA     NA         ... 0
1027 1461         80             NA     NA         ... 0
1028 1461        100             NA     NA         ... 0
1029 1028         NA             NA     NA         ... 0
1030 1028         NA             NA     NA         ... 0
1031 1477         NA             NA     NA         ... 0
1032  997         NA           5.44     80         ... 0
1033 1068         70           5.36    270         ... 0
1034 1068         70           5.36    245         ... 0
1035 1068         70           5.36    260         ... 0
1036 1068         70           5.36    250         ... 0
1037 1068         70           5.36    242         ... 0
1038 1201         70           5.31    107         ... 0
1039 1164        100           5.34    115         ... 0
1040 1201         70           5.31    108         ... 0
1041 1201         70           5.31    117         ... 0
1042 1201         70           5.31    206         ... 0
1043 1201         70           5.31    330         ... 0
1044 1201         70           5.31    126         ... 0
1045 1201         70           5.31     97         ... 0
1046 1201         70           5.31    135         ... 0
1047  960        100           5.29     85         ... 0
1048  996        100           5.46     85         ... 0
     namessolvent2_DIO namessolvent2_TCB namessolvent2_oDCB
1    0                 0                 0
2    0                 0                 0
3    0                 0                 0
4    0                 0                 0
5    0                 0                 0
6    0                 0                 0
7    0                 0                 0
8    0                 0                 0
9    0                 0                 0
10   0                 0                 0
11   0                 0                 0
12   0                 0                 0
13   0                 0                 0
14   0                 0                 0
15   0                 0                 0
16   0                 0                 0
17   0                 0                 0
18   0                 0                 0
19   0                 0                 0
20   0                 0                 0
21   0                 0                 0
22   0                 0                 0
23   0                 0                 0
24   0                 0                 0
25   0                 0                 0
26   0                 0                 0
27   0                 0                 0
28   0                 0                 0
29   0                 0                 0
30   0                 0                 0
...  ...               ...               ...
1019 0                 0                 0
1020 0                 0                 0
1021 0                 0                 0
1022 0                 0                 0
1023 0                 0                 0
1024 0                 0                 0
1025 0                 0                 0
1026 0                 0                 0
1027 0                 0                 0
1028 0                 0                 0
1029 0                 0                 0
1030 0                 0                 0
1031 0                 0                 0
1032 0                 0                 0
1033 0                 0                 0
1034 0                 0                 0
1035 0                 0                 0
1036 0                 0                 0
1037 0                 0                 0
1038 0                 0                 0
1039 0                 0                 0
1040 0                 0                 0
1041 0                 0                 0
1042 0                 0                 0
1043 0                 0                 0
1044 0                 0                 0
1045 0                 0                 0
1046 0                 0                 0
1047 0                 0                 0
1048 0                 0                 0
     SMILESinM.1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
24
25
26
27
28   O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
29   O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
30   O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
...  ...
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
     SMILESip1M.1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22   CCCC/C(C(C1=C/2C=CC=C1)=NC2=C/3)=C(N/4)\\C(C=CC=C5)=C5C4=C\\C6=N/C(C7=C6C=CC=C7)=C(CCCCOC(CCCC8(C9=CC=CC=C9)[C@]%10%11[C@@]%128C%13=C%14C%15=C%16C%17=C%13C%18=C%19C(C(C%20=C%21C%22=C%23C%17=C%20%19)=C%24%25)=C%26C%27=C%25C(C%28=C%24C%21=C%29C%30=C%31C(C(C%32=C%23%16)=C%29%22)=C(C%32=C%15C%33=C%14C%11=C%34%35)C%36=C%33C%35=C%37C%36=C%31C%38=C%30%28)=C(C%39=C%27%40)C%38=C%37C%39=C%34C%10=C%40C%26=C%18%12)=O)\\C%41=C(C=CC=C%42)C%42=C3N%41
23   C1(C=CC=C2)=C2C(/C=C(C3=C/4C=CC=C3)\\NC4=C/5)=N/C1=C\\C6=C(C=CC=C7)C7=C(/C=C8C(C=CC=C9)=C9C5=N/8)N6
24
25
26
27
28   C1(C2=CC=CS2)=CC(C=C3C=CC(C4=CC=CS4)=CC3=C5)=C5C=C1
29   C1(C2=CC=CS2)=CC(C=C3C=CC(C4=CC=CS4)=CC3=C5)=C5C=C1
30   C1(C2=CC=CS2)=CC(C=C3C=CC(C4=CC=CS4)=CC3=C5)=C5C=C1
...  ...
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
     SMILESip2M.1 SMILESp2M.1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
...  ...          ...
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
     SMILESnM.1
1    O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
2    O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
3    O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
4    O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
5    O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
6    O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
7    O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
8    O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
9    O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
10   O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
11   O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36
12   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
13   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
14   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
15   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
16   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
17   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
18   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
19   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
20
21   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
22   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
23   O=C(OC)CCCC1(C2=CC=CC=C2)C34C15C(C6=C78)=C9C(C%10=C%11C%12=C%13C%14=C%15%16)=C5C%17=C(C%10=C%12%18)C%19=C%20C%18=C%14C%21=C%20C%22=C%23C%19=C%17C3=C%24C%25=C4C6=C%26C7=C%27C%28=C%29C8=C9C%11=C%29C%13=C%15C%28=C%30C%27=C%31C%26=C%25C%32=C%31C%33=C%30C%16=C%21C%33=C%22C%32=C%24%23
24   O=C(OC)CCCC1(C2=CC=CC=C2)C3(C4=C5C6=C7C8=C9C%10=C6C%11=C4C%12=C%13C%11=C%14C%10=C%15C9=C%16%17)C1%18C%12=C%19C(C%20=C%21C%22=C%23%24)=C%18C%25=C(C%20=C%22%26)C%27=C%28C%26=C(C%29=C%30%31)C%24=C%30C%32=C%33C%23=C%34C%21=C%19C%13=C%34C%14=C%33C%15=C%32C%17=C%31C%35=C%16C8=C%36C7=C%37C5=C3C%25=C%27C%37=C%38C%28=C%29C%35=C%38%36

     Lay2Mname_ Lay2Mname_PEDOTPSS Lay2Mname_ZnO Lay2Mname_ZnOC60
1    0          1                  0             0
2    0          1                  0             0
3    0          1                  0             0
4    0          1                  0             0
5    0          1                  0             0
6    0          1                  0             0
7    0          1                  0             0
8    0          1                  0             0
9    0          1                  0             0
10   0          1                  0             0
11   0          1                  0             0
12   0          1                  0             0
13   0          1                  0             0
14   0          1                  0             0
15   0          1                  0             0
16   0          1                  0             0
17   0          1                  0             0
18   0          1                  0             0
19   0          1                  0             0
20   0          1                  0             0
21   0          1                  0             0
22   0          1                  0             0
23   0          1                  0             0
24   0          1                  0             0
25   0          1                  0             0
26   0          1                  0             0
27   0          1                  0             0
28   0          1                  0             0
29   0          1                  0             0
30   0          1                  0             0
...  ...        ...                ...           ...
1019 0          1                  0             0
1020 0          1                  0             0
1021 0          1                  0             0
1022 0          1                  0             0
1023 0          1                  0             0
1024 0          1                  0             0
1025 0          1                  0             0
1026 0          1                  0             0
1027 0          1                  0             0
1028 0          1                  0             0
1029 0          1                  0             0
1030 0          1                  0             0
1031 0          1                  0             0
1032 0          1                  0             0
1033 0          1                  0             0
1034 0          1                  0             0
1035 0          1                  0             0
1036 0          1                  0             0
1037 0          1                  0             0
1038 0          1                  0             0
1039 0          1                  0             0
1040 0          1                  0             0
1041 0          1                  0             0
1042 0          1                  0             0
1043 0          1                  0             0
1044 0          1                  0             0
1045 0          1                  0             0
1046 0          1                  0             0
1047 0          1                  0             0
1048 0          1                  0             0
     Lay5electronodes1_ Lay5electronodes1_Ag Lay5electronodes1_Al
1    0                  0                    0
2    0                  0                    0
3    0                  0                    0
4    0                  0                    0
5    0                  0                    0
6    0                  0                    0
7    0                  0                    0
8    0                  0                    0
9    0                  0                    0
10   0                  0                    0
11   0                  0                    0
12   0                  0                    0
13   0                  0                    0
14   0                  0                    0
15   0                  0                    0
16   0                  0                    0
17   0                  0                    0
18   0                  0                    0
19   0                  0                    0
20   0                  0                    1
21   0                  0                    1
22   0                  0                    1
23   0                  0                    1
24   0                  0                    0
25   0                  0                    0
26   0                  0                    0
27   0                  0                    0
28   0                  0                    0
29   0                  0                    0
30   0                  0                    0
...  ...                ...                  ...
1019 0                  0                    0
1020 0                  0                    0
1021 0                  0                    0
1022 0                  0                    0
1023 0                  0                    0
1024 0                  0                    0
1025 0                  0                    0
1026 0                  0                    0
1027 0                  0                    0
1028 0                  0                    0
1029 0                  0                    0
1030 0                  0                    0
1031 0                  0                    0
1032 0                  0                    0
1033 0                  0                    0
1034 0                  0                    0
1035 0                  0                    0
1036 0                  0                    0
1037 0                  0                    0
1038 0                  0                    0
1039 0                  0                    0
1040 0                  0                    0
1041 0                  0                    0
1042 0                  0                    0
1043 0                  0                    0
1044 0                  0                    0
1045 0                  0                    0
1046 0                  0                    0
1047 0                  0                    0
1048 0                  0                    0
     Lay5electronodes1_BCP Lay5electronodes1_C60bis Lay5electronodes1_Ca ...
1    0                     0                        0                    ...
2    0                     0                        0                    ...
3    0                     0                        0                    ...
4    0                     0                        0                    ...
5    0                     0                        1                    ...
6    0                     0                        1                    ...
7    0                     0                        1                    ...
8    0                     0                        1                    ...
9    0                     0                        1                    ...
10   0                     0                        1                    ...
11   0                     0                        1                    ...
12   1                     0                        0                    ...
13   1                     0                        0                    ...
14   0                     0                        0                    ...
15   0                     0                        0                    ...
16   0                     0                        0                    ...
17   0                     0                        0                    ...
18   0                     0                        0                    ...
19   0                     0                        0                    ...
20   0                     0                        0                    ...
21   0                     0                        0                    ...
22   0                     0                        0                    ...
23   0                     0                        0                    ...
24   0                     0                        1                    ...
25   0                     0                        1                    ...
26   0                     0                        1                    ...
27   0                     0                        1                    ...
28   0                     0                        1                    ...
29   0                     0                        1                    ...
30   0                     0                        1                    ...
...  ...                   ...                      ...
1019 0                     0                        1                    ...
1020 0                     0                        1                    ...
1021 0                     0                        1                    ...
1022 0                     0                        1                    ...
1023 0                     0                        1                    ...
1024 0                     0                        1                    ...
1025 0                     0                        1                    ...
1026 0                     0                        1                    ...
1027 0                     0                        1                    ...
1028 0                     0                        0                    ...
1029 0                     0                        1                    ...
1030 0                     0                        1                    ...
1031 0                     0                        0                    ...
1032 0                     0                        1                    ...
1033 0                     0                        1                    ...
1034 0                     0                        1                    ...
1035 0                     0                        1                    ...
1036 0                     0                        1                    ...
1037 0                     0                        1                    ...
1038 0                     0                        1                    ...
1039 0                     0                        1                    ...
1040 0                     0                        1                    ...
1041 0                     0                        1                    ...
1042 0                     0                        1                    ...
1043 0                     0                        1                    ...
1044 0                     0                        1                    ...
1045 0                     0                        1                    ...
1046 0                     0                        1                    ...
1047 0                     0                        0                    ...
1048 0                     0                        0                    ...
     namessolvent1_DCM namessolvent1_TCB namessolvent1_THF namessolvent1_oDCB
1    1                 0                 0                 0
2    1                 0                 0                 0
3    1                 0                 0                 0
4    1                 0                 0                 0
5    0                 0                 0                 0
6    0                 0                 0                 0
7    0                 0                 0                 0
8    0                 0                 0                 0
9    0                 0                 0                 0
10   0                 0                 0                 0
11   0                 0                 0                 0
12   0                 0                 0                 0
13   0                 0                 0                 0
14   1                 0                 0                 0
15   1                 0                 0                 0
16   1                 0                 0                 0
17   1                 0                 0                 0
18   1                 0                 0                 0
19   0                 0                 0                 0
20   0                 0                 0                 0
21   0                 0                 0                 0
22   0                 0                 0                 0
23   0                 0                 0                 0
24   0                 0                 0                 0
25   0                 0                 0                 0
26   0                 0                 0                 0
27   0                 0                 0                 0
28   0                 0                 0                 0
29   0                 0                 0                 0
30   0                 0                 0                 0
...  ...               ...               ...               ...
1019 0                 0                 0                 0
1020 0                 0                 0                 0
1021 0                 0                 0                 0
1022 0                 0                 0                 0
1023 0                 0                 0                 0
1024 0                 0                 0                 1
1025 0                 0                 0                 1
1026 0                 0                 0                 1
1027 0                 0                 0                 1
1028 0                 0                 0                 1
1029 0                 0                 0                 0
1030 0                 0                 0                 0
1031 0                 0                 0                 0
1032 0                 0                 0                 1
1033 0                 0                 0                 0
1034 0                 0                 0                 1
1035 0                 1                 0                 0
1036 0                 1                 0                 0
1037 0                 1                 0                 0
1038 0                 0                 0                 1
1039 0                 0                 0                 1
1040 0                 0                 0                 1
1041 0                 0                 0                 1
1042 0                 0                 0                 1
1043 0                 0                 0                 1
1044 0                 0                 0                 1
1045 0                 0                 0                 1
1046 0                 0                 0                 1
1047 0                 0                 0                 0
1048 0                 0                 0                 0
     namessolvent2_ namessolvent2_CB namessolvent2_CF namessolvent2_DIO
1    1              0                0                0
2    1              0                0                0
3    1              0                0                0
4    1              0                0                0
5    1              0                0                0
6    1              0                0                0
7    1              0                0                0
8    1              0                0                0
9    1              0                0                0
10   1              0                0                0
11   1              0                0                0
12   1              0                0                0
13   1              0                0                0
14   1              0                0                0
15   1              0                0                0
16   1              0                0                0
17   1              0                0                0
18   1              0                0                0
19   1              0                0                0
20   1              0                0                0
21   1              0                0                0
22   1              0                0                0
23   1              0                0                0
24   1              0                0                0
25   1              0                0                0
26   1              0                0                0
27   1              0                0                0
28   1              0                0                0
29   1              0                0                0
30   1              0                0                0
...  ...            ...              ...              ...
1019 1              0                0                0
1020 1              0                0                0
1021 1              0                0                0
1022 1              0                0                0
1023 1              0                0                0
1024 1              0                0                0
1025 1              0                0                0
1026 1              0                0                0
1027 1              0                0                0
1028 1              0                0                0
1029 1              0                0                0
1030 1              0                0                0
1031 1              0                0                0
1032 1              0                0                0
1033 1              0                0                0
1034 1              0                0                0
1035 1              0                0                0
1036 1              0                0                0
1037 1              0                0                0
1038 1              0                0                0
1039 1              0                0                0
1040 1              0                0                0
1041 1              0                0                0
1042 1              0                0                0
1043 1              0                0                0
1044 1              0                0                0
1045 1              0                0                0
1046 1              0                0                0
1047 1              0                0                0
1048 1              0                0                0
     namessolvent2_TCB namessolvent2_oDCB
1    0                 0
2    0                 0
3    0                 0
4    0                 0
5    0                 0
6    0                 0
7    0                 0
8    0                 0
9    0                 0
10   0                 0
11   0                 0
12   0                 0
13   0                 0
14   0                 0
15   0                 0
16   0                 0
17   0                 0
18   0                 0
19   0                 0
20   0                 0
21   0                 0
22   0                 0
23   0                 0
24   0                 0
25   0                 0
26   0                 0
27   0                 0
28   0                 0
29   0                 0
30   0                 0
...  ...               ...
1019 0                 0
1020 0                 0
1021 0                 0
1022 0                 0
1023 0                 0
1024 0                 0
1025 0                 0
1026 0                 0
1027 0                 0
1028 0                 0
1029 0                 0
1030 0                 0
1031 0                 0
1032 0                 0
1033 0                 0
1034 0                 0
1035 0                 0
1036 0                 0
1037 0                 0
1038 0                 0
1039 0                 0
1040 0                 0
1041 0                 0
1042 0                 0
1043 0                 0
1044 0                 0
1045 0                 0
1046 0                 0
1047 0                 0
1048 0                 0

In [7]:
#columnList<-c("Jsc","Voc","FF","PCEmax","Egoptp1M","HOMOp1M","LUMOp1M","Mmonomerp1M","MnkDap1M","MwkDap1M","PDIp1M","Lay1Mname","Lay2Mname","Lay5electronodes1","SMILESsnameinM","SMILESsnameip1M",
#          "SMILESsnameip2M","SMILESsnamenM","SMILESsnamep1M","SMILESsnamep2M",
#          "Lay6electronodes2","Additivesname","namessolvent1","namessolvent2","SMILESinM","SMILESip1M","SMILESip2M",
#                              "SMILESp2M","SMILESnM","SMILESp1M")
#fmatrix12 <-data.frame(dataUsed01[, which (colnames(dataUsed01)%in%columnList)])
fmatrix12 <-data.frame(dataUsed01,dataUsed02)
fmatrix12
dataU0<-na.omit(fmatrix12)
tt01<-which(apply(dataU0,2,sd)==0)
length(tt01)
dataUsed00<-dataU0[,-c(tt01)]
dataUsed00

     Lay2thickness Aonsetp1Mfilm MwkDap1M LUMOp1M MnkDap1M VolRatioS1
1    30            700                NA   NA       NA     NA
2    30            700                NA   NA       NA     NA
3    30            700                NA   NA       NA     NA
4    30            700                NA   NA       NA     NA
5    30             NA                NA   NA       NA     NA
6    30             NA                NA   NA       NA     NA
7    30             NA                NA   NA       NA     NA
8    30             NA                NA   NA       NA     NA
9    30             NA                NA   NA       NA     NA
10   30             NA                NA   NA       NA     NA
11   30             NA                NA   NA       NA     NA
12   NA            470            6.1009   NA     24.7     NA
13   NA            460            6.6049   NA     25.7     NA
14   30             NA           21.3444   NA     46.2     NA
15   30            750           16.2409   NA     40.3     NA
16   30             NA           11.4244   NA     33.8     NA
17   30             NA           12.9600   NA     36.0     NA
18   30             NA           20.2500   NA     45.0     NA
19   30             NA           19.1844   NA     43.8     NA
20   NA            685           22.5625  3.4     47.5     NA
21   NA            685           27.7729  3.2     52.7     NA
22   NA             NA            6.0025  3.2     24.5     NA
23   NA             NA           15.9201  3.2     39.9     NA
24   30             NA           15.4449   NA     39.3     NA
25   30             NA           18.7489   NA     43.3     NA
26   30             NA            5.7600   NA     24.0     NA
27   30             NA            5.6169   NA     23.7     NA
28   30             NA            5.4289   NA     23.3     NA
29   30             NA            5.6644   NA     23.8     NA
30   30             NA            5.6169   NA     23.7     NA
...  ...           ...           ...      ...     ...      ...
1019 60            730           73.90      NA    23.1      1
1020 60            730           73.90      NA    23.1      1
1021 60            718           47.30      NA    16.9      1
1022 60            718           47.30      NA    16.9      1
1023 60            718           47.30      NA    16.9      1
1024 60            702           59.10      NA    21.1      1
1025 60            702           59.10      NA    21.1      1
1026 60            702           59.10      NA    21.1      1
1027 60            702           59.10      NA    21.1      1
1028 60            702           59.10      NA    21.1      1
1029 60            632           22.90      NA    10.4     NA
1030 60            680           22.90      NA    10.4     NA
1031 60            696           65.60      NA    32.8     NA
1032 NA            632           13.00    3.48     6.2      1
1033 40             NA              NA    3.36      NA      1
1034 40             NA              NA    3.36      NA      1
1035 40             NA              NA    3.36      NA      1
1036 40             NA              NA    3.36      NA      1
1037 40             NA              NA    3.36      NA      1
1038 40            720           49.50    3.61    27.5      1
1039 40            707           33.30    3.58    22.2      1
1040 40            730           49.50    3.61    27.5      1
1041 40            730           49.50    3.61    27.5      1
1042 40            730           49.50    3.61    27.5      1
1043 40            730           49.50    3.61    27.5      1
1044 40            730           49.50    3.61    27.5      1
1045 40            730           49.50    3.61    27.5      1
1046 40            730           49.50    3.61    27.5      1
1047 40            765           32.64    3.67    19.2      1
1048 40            712           34.20    3.72    18.0      1
     Mmonomerp1M Lay6thickness HOMOp1M ALthickness ... namessolvent1_DCM.1
1    NA          60              NA     50         ... 1
2    NA          60              NA    130         ... 1
3    NA          60              NA    130         ... 1
4    NA          60              NA    130         ... 1
5    NA          80            5.00     82         ... 0
6    NA          80            5.10     87         ... 0
7    NA          80            5.00     83         ... 0
8    NA          80            5.10     59         ... 0
9    NA          80            5.10     85         ... 0
10   NA          80            5.10    141         ... 0
11   NA          80            5.10    162         ... 0
12   NA          NA            5.43     NA         ... 0
13   NA          NA            5.50     NA         ... 0
14   NA          60              NA     80         ... 1
15   NA          60              NA     80         ... 1
16   NA          60              NA     80         ... 1
17   NA          60              NA     80         ... 1
18   NA          60              NA     80         ... 1
19   NA          80              NA     80         ... 0
20   NA          NA            5.00     NA         ... 0
21   NA          NA            4.90     NA         ... 0
22   NA          NA            4.90     NA         ... 0
23   NA          NA            4.90     NA         ... 0
24   NA          80              NA     75         ... 0
25   NA          80              NA     67         ... 0
26   NA          80              NA    124         ... 0
27   NA          80              NA    199         ... 0
28   NA          80              NA    123         ... 0
29   NA          80              NA    153         ... 0
30   NA          80              NA    223         ... 0
...  ...         ...           ...     ...             ...
1019 1389         80             NA     NA         ... 0
1020 1389         80             NA     NA         ... 0
1021 1425         80             NA     NA         ... 0
1022 1425         80             NA     NA         ... 0
1023 1425         80             NA     NA         ... 0
1024 1461         80             NA     NA         ... 0
1025 1461         80             NA     NA         ... 0
1026 1461         80             NA     NA         ... 0
1027 1461         80             NA     NA         ... 0
1028 1461        100             NA     NA         ... 0
1029 1028         NA             NA     NA         ... 0
1030 1028         NA             NA     NA         ... 0
1031 1477         NA             NA     NA         ... 0
1032  997         NA           5.44     80         ... 0
1033 1068         70           5.36    270         ... 0
1034 1068         70           5.36    245         ... 0
1035 1068         70           5.36    260         ... 0
1036 1068         70           5.36    250         ... 0
1037 1068         70           5.36    242         ... 0
1038 1201         70           5.31    107         ... 0
1039 1164        100           5.34    115         ... 0
1040 1201         70           5.31    108         ... 0
1041 1201         70           5.31    117         ... 0
1042 1201         70           5.31    206         ... 0
1043 1201         70           5.31    330         ... 0
1044 1201         70           5.31    126         ... 0
1045 1201         70           5.31     97         ... 0
1046 1201         70           5.31    135         ... 0
1047  960        100           5.29     85         ... 0
1048  996        100           5.46     85         ... 0
     namessolvent1_TCB.1 namessolvent1_THF.1 namessolvent1_oDCB.1
1    0                   0                   0
2    0                   0                   0
3    0                   0                   0
4    0                   0                   0
5    0                   0                   0
6    0                   0                   0
7    0                   0                   0
8    0                   0                   0
9    0                   0                   0
10   0                   0                   0
11   0                   0                   0
12   0                   0                   0
13   0                   0                   0
14   0                   0                   0
15   0                   0                   0
16   0                   0                   0
17   0                   0                   0
18   0                   0                   0
19   0                   0                   0
20   0                   0                   0
21   0                   0                   0
22   0                   0                   0
23   0                   0                   0
24   0                   0                   0
25   0                   0                   0
26   0                   0                   0
27   0                   0                   0
28   0                   0                   0
29   0                   0                   0
30   0                   0                   0
...  ...                 ...                 ...
1019 0                   0                   0
1020 0                   0                   0
1021 0                   0                   0
1022 0                   0                   0
1023 0                   0                   0
1024 0                   0                   1
1025 0                   0                   1
1026 0                   0                   1
1027 0                   0                   1
1028 0                   0                   1
1029 0                   0                   0
1030 0                   0                   0
1031 0                   0                   0
1032 0                   0                   1
1033 0                   0                   0
1034 0                   0                   1
1035 1                   0                   0
1036 1                   0                   0
1037 1                   0                   0
1038 0                   0                   1
1039 0                   0                   1
1040 0                   0                   1
1041 0                   0                   1
1042 0                   0                   1
1043 0                   0                   1
1044 0                   0                   1
1045 0                   0                   1
1046 0                   0                   1
1047 0                   0                   0
1048 0                   0                   0
     namessolvent2_.1 namessolvent2_CB.1 namessolvent2_CF.1 namessolvent2_DIO.1
1    1                0                  0                  0
2    1                0                  0                  0
3    1                0                  0                  0
4    1                0                  0                  0
5    1                0                  0                  0
6    1                0                  0                  0
7    1                0                  0                  0
8    1                0                  0                  0
9    1                0                  0                  0
10   1                0                  0                  0
11   1                0                  0                  0
12   1                0                  0                  0
13   1                0                  0                  0
14   1                0                  0                  0
15   1                0                  0                  0
16   1                0                  0                  0
17   1                0                  0                  0
18   1                0                  0                  0
19   1                0                  0                  0
20   1                0                  0                  0
21   1                0                  0                  0
22   1                0                  0                  0
23   1                0                  0                  0
24   1                0                  0                  0
25   1                0                  0                  0
26   1                0                  0                  0
27   1                0                  0                  0
28   1                0                  0                  0
29   1                0                  0                  0
30   1                0                  0                  0
...  ...              ...                ...                ...
1019 1                0                  0                  0
1020 1                0                  0                  0
1021 1                0                  0                  0
1022 1                0                  0                  0
1023 1                0                  0                  0
1024 1                0                  0                  0
1025 1                0                  0                  0
1026 1                0                  0                  0
1027 1                0                  0                  0
1028 1                0                  0                  0
1029 1                0                  0                  0
1030 1                0                  0                  0
1031 1                0                  0                  0
1032 1                0                  0                  0
1033 1                0                  0                  0
1034 1                0                  0                  0
1035 1                0                  0                  0
1036 1                0                  0                  0
1037 1                0                  0                  0
1038 1                0                  0                  0
1039 1                0                  0                  0
1040 1                0                  0                  0
1041 1                0                  0                  0
1042 1                0                  0                  0
1043 1                0                  0                  0
1044 1                0                  0                  0
1045 1                0                  0                  0
1046 1                0                  0                  0
1047 1                0                  0                  0
1048 1                0                  0                  0
     namessolvent2_TCB.1 namessolvent2_oDCB.1
1    0                   0
2    0                   0
3    0                   0
4    0                   0
5    0                   0
6    0                   0
7    0                   0
8    0                   0
9    0                   0
10   0                   0
11   0                   0
12   0                   0
13   0                   0
14   0                   0
15   0                   0
16   0                   0
17   0                   0
18   0                   0
19   0                   0
20   0                   0
21   0                   0
22   0                   0
23   0                   0
24   0                   0
25   0                   0
26   0                   0
27   0                   0
28   0                   0
29   0                   0
30   0                   0
...  ...                 ...
1019 0                   0
1020 0                   0
1021 0                   0
1022 0                   0
1023 0                   0
1024 0                   0
1025 0                   0
1026 0                   0
1027 0                   0
1028 0                   0
1029 0                   0
1030 0                   0
1031 0                   0
1032 0                   0
1033 0                   0
1034 0                   0
1035 0                   0
1036 0                   0
1037 0                   0
1038 0                   0
1039 0                   0
1040 0                   0
1041 0                   0
1042 0                   0
1043 0                   0
1044 0                   0
1045 0                   0
1046 0                   0
1047 0                   0
1048 0                   0

Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"

[1] 677

     Lay2thickness Aonsetp1Mfilm MwkDap1M LUMOp1M MnkDap1M VolRatioS1
317  40            785            78.000  3.64    24.0     0.97
318  40            785           124.000  3.64    72.9     0.97
319  40            785           249.000  3.64    40.0     0.97
320  40            785           375.000  3.64    48.0     0.97
479  30            755           210.295  2.95    68.5     1.00
480  30            755           210.295  2.95    68.5     1.00
481  30            755           210.295  2.95    68.5     1.00
491  30            755           210.295  2.95    68.5     1.00
492  30            755           210.295  2.95    68.5     1.00
493  30            755           210.295  2.95    68.5     1.00
494  30            755           210.295  2.95    68.5     1.00
495  30            745            23.154  3.15    10.2     1.00
496  30            737            65.514  3.21    18.3     1.00
497  30            716            54.480  3.30    22.7     1.00
594  30            786            22.900  3.20    18.3     1.00
595  30            780            23.200  3.22    16.8     1.00
596  30            777            23.700  3.29    15.9     1.00
597  30            762            19.300  3.31    14.6     1.00
598  30            764            22.700  3.24    16.1     1.00
599  30            768            25.000  3.17    16.7     1.00
600  30            777            23.700  3.29    15.9     1.00
601  30            762            19.300  3.31    14.6     1.00
602  30            764            22.700  3.24    16.1     1.00
603  30            795            99.300  3.40    30.1     1.00
604  30            780            28.400  3.53    16.7     1.00
605  30            785           218.400  3.49    70.0     1.00
728  40            732            70.000  3.56    41.3     1.00
729  40            748            24.900  3.49    16.7     1.00
730  40            697            10.600  3.14     3.4     1.00
731  40            732            70.000  3.56    41.3     1.00
...  ...           ...           ...      ...     ...      ...
761  40            749            26.500  3.91    17.0     1
762  40            765            24.300  3.84    18.0     1
763  40            765            24.300  3.84    18.0     1
764  40            749            26.500  3.91    17.0     1
765  40            749            26.500  3.91    17.0     1
766  40            749            26.500  3.91    17.0     1
767  40            765            24.300  3.84    18.0     1
768  40            765            24.300  3.84    18.0     1
769  40            765            24.300  3.84    18.0     1
877  20            642            71.504  2.30    21.8     1
878  20            642            71.504  2.30    21.8     1
879  20            644           100.300  2.54    34.0     1
880  20            644           100.300  2.54    34.0     1
883  20            642            71.504  2.30    21.8     1
884  20            642            71.504  2.30    21.8     1
885  20            644           100.300  2.54    34.0     1
886  20            644           100.300  2.54    34.0     1
887  20            642            71.504  2.30    21.8     1
888  20            644           100.300  2.54    34.0     1
1038 40            720            49.500  3.61    27.5     1
1039 40            707            33.300  3.58    22.2     1
1040 40            730            49.500  3.61    27.5     1
1041 40            730            49.500  3.61    27.5     1
1042 40            730            49.500  3.61    27.5     1
1043 40            730            49.500  3.61    27.5     1
1044 40            730            49.500  3.61    27.5     1
1045 40            730            49.500  3.61    27.5     1
1046 40            730            49.500  3.61    27.5     1
1047 40            765            32.640  3.67    19.2     1
1048 40            712            34.200  3.72    18.0     1
     Mmonomerp1M Lay6thickness HOMOp1M ALthickness ...
317   918        100           5.22    100         ...
318   918        100           5.22    100         ...
319   918        100           5.22    100         ...
320   918        100           5.22    100         ...
479  1307         80           4.66     80         ...
480  1307         80           4.66     82         ...
481  1307         80           4.66     85         ...
491  1307         80           4.66     80         ...
492  1307         80           4.66     85         ...
493  1307         80           4.66     80         ...
494  1307         80           4.66     82         ...
495  1343         80           4.86     80         ...
496  1343         80           4.92     82         ...
497  1379         80           5.05     85         ...
594   824         80           4.90    100         ...
595   768         80           4.94    100         ...
596   736         80           5.04    100         ...
597   786         80           5.12    100         ...
598   768         80           5.01    100         ...
599   824         80           5.01    100         ...
600   736         80           5.04    100         ...
601   786         80           5.12    100         ...
602   768         80           5.01    100         ...
603   982         80           5.29     90         ...
604   982         80           5.29    102         ...
605  1038         80           5.29     94         ...
728  1113        100           5.25     75         ...
729  1129        100           5.15     75         ...
730   967        100           4.92     75         ...
731  1113        100           5.25     75         ...
...  ...         ...           ...     ...
761  1165         80           5.56    150         ...
762  1181         80           5.46    150         ...
763  1181         80           5.46    150         ...
764  1165         80           5.56    150         ...
765  1165         80           5.56    150         ...
766  1165         80           5.56    150         ...
767  1181         80           5.46    150         ...
768  1181         80           5.46    150         ...
769  1181         80           5.46    150         ...
877   875        100           5.41     95         ...
878   875        100           5.41    100         ...
879  1044        100           5.39     95         ...
880  1044        100           5.39    100         ...
883   875        100           5.41     95         ...
884   875        100           5.41    100         ...
885  1044        100           5.39     95         ...
886  1044        100           5.39    100         ...
887   875        100           5.41    100         ...
888  1044        100           5.39    100         ...
1038 1201         70           5.31    107         ...
1039 1164        100           5.34    115         ...
1040 1201         70           5.31    108         ...
1041 1201         70           5.31    117         ...
1042 1201         70           5.31    206         ...
1043 1201         70           5.31    330         ...
1044 1201         70           5.31    126         ...
1045 1201         70           5.31     97         ...
1046 1201         70           5.31    135         ...
1047  960        100           5.29     85         ...
1048  996        100           5.46     85         ...
     SMILESsnamep1M_PTBDTffDTBT.1 Lay6electronodes2_Ag.1 Lay6electronodes2_Al.1
317  0                            1                      0
318  0                            1                      0
319  0                            1                      0
320  0                            1                      0
479  0                            0                      1
480  0                            0                      1
481  0                            0                      1
491  0                            0                      1
492  0                            0                      1
493  0                            0                      1
494  0                            0                      1
495  0                            0                      1
496  0                            0                      1
497  0                            0                      1
594  0                            0                      1
595  0                            0                      1
596  0                            0                      1
597  0                            0                      1
598  0                            0                      1
599  0                            0                      1
600  0                            0                      1
601  0                            0                      1
602  0                            0                      1
603  0                            0                      1
604  0                            0                      1
605  0                            0                      1
728  0                            0                      1
729  0                            0                      1
730  0                            0                      1
731  0                            0                      1
...  ...                          ...                    ...
761  0                            0                      1
762  0                            0                      1
763  0                            0                      1
764  0                            0                      1
765  0                            0                      1
766  0                            0                      1
767  0                            0                      1
768  0                            0                      1
769  0                            0                      1
877  0                            1                      0
878  0                            1                      0
879  0                            1                      0
880  0                            1                      0
883  0                            1                      0
884  0                            1                      0
885  0                            1                      0
886  0                            1                      0
887  0                            1                      0
888  0                            1                      0
1038 0                            0                      1
1039 0                            0                      1
1040 0                            0                      1
1041 0                            0                      1
1042 0                            0                      1
1043 0                            0                      1
1044 0                            0                      1
1045 0                            0                      1
1046 0                            0                      1
1047 0                            0                      1
1048 1                            0                      1
     Additivesname_.1 Additivesname_DIO.1 namessolvent1_CB.1 namessolvent1_CF.1
317  1                0                   1                  0
318  1                0                   1                  0
319  1                0                   1                  0
320  1                0                   1                  0
479  1                0                   0                  0
480  1                0                   0                  0
481  1                0                   0                  0
491  0                1                   0                  0
492  0                1                   0                  0
493  0                1                   0                  0
494  0                1                   0                  0
495  1                0                   0                  0
496  1                0                   0                  0
497  1                0                   0                  0
594  0                1                   0                  0
595  0                1                   0                  0
596  0                1                   0                  0
597  0                1                   0                  0
598  0                1                   0                  0
599  0                1                   0                  0
600  0                1                   0                  0
601  0                1                   0                  0
602  0                1                   0                  0
603  0                1                   1                  0
604  0                1                   1                  0
605  0                1                   1                  0
728  1                0                   0                  0
729  1                0                   0                  0
730  1                0                   0                  0
731  1                0                   0                  0
...  ...              ...                 ...                ...
761  1                0                   0                  0
762  1                0                   0                  0
763  1                0                   0                  0
764  1                0                   0                  0
765  1                0                   0                  0
766  1                0                   0                  0
767  1                0                   0                  0
768  1                0                   0                  0
769  1                0                   0                  0
877  1                0                   0                  0
878  0                1                   0                  0
879  1                0                   0                  0
880  0                1                   0                  0
883  0                1                   0                  0
884  0                1                   0                  0
885  0                1                   0                  0
886  0                1                   0                  0
887  0                1                   0                  0
888  0                1                   0                  0
1038 1                0                   0                  0
1039 1                0                   0                  0
1040 1                0                   0                  0
1041 1                0                   0                  0
1042 1                0                   0                  0
1043 1                0                   0                  0
1044 0                1                   0                  0
1045 1                0                   0                  0
1046 1                0                   0                  0
1047 1                0                   0                  1
1048 1                0                   0                  1
     namessolvent1_oDCB.1 namessolvent2_.1 namessolvent2_oDCB.1
317  0                    0                1
318  0                    0                1
319  0                    0                1
320  0                    0                1
479  1                    1                0
480  1                    1                0
481  1                    1                0
491  1                    1                0
492  1                    1                0
493  1                    1                0
494  1                    1                0
495  1                    1                0
496  1                    1                0
497  1                    1                0
594  1                    1                0
595  1                    1                0
596  1                    1                0
597  1                    1                0
598  1                    1                0
599  1                    1                0
600  1                    1                0
601  1                    1                0
602  1                    1                0
603  0                    1                0
604  0                    1                0
605  0                    1                0
728  1                    1                0
729  1                    1                0
730  1                    1                0
731  1                    1                0
...  ...                  ...              ...
761  1                    1                0
762  1                    1                0
763  1                    1                0
764  1                    1                0
765  1                    1                0
766  1                    1                0
767  1                    1                0
768  1                    1                0
769  1                    1                0
877  1                    1                0
878  1                    1                0
879  1                    1                0
880  1                    1                0
883  1                    1                0
884  1                    1                0
885  1                    1                0
886  1                    1                0
887  1                    1                0
888  1                    1                0
1038 1                    1                0
1039 1                    1                0
1040 1                    1                0
1041 1                    1                0
1042 1                    1                0
1043 1                    1                0
1044 1                    1                0
1045 1                    1                0
1046 1                    1                0
1047 0                    1                0
1048 0                    1                0

In [9]:
columnList02<-c("Jsc","Voc","FF","PCEmax")
dataU01 <-data.frame(dataUsed00[, -which (colnames(dataUsed00)%in%columnList02)])
dataU02 <-data.frame(dataUsed00[, which (colnames(dataUsed00)%in%columnList02)])
dataUsed02 <-data.frame(dataU02,dataU01)
dataUsed02

     Jsc   Voc   FF     PCEmax Lay2thickness Aonsetp1Mfilm MwkDap1M LUMOp1M
317  13.02 0.790 0.6900 7.02   40            785            78.000  3.64
318  14.02 0.790 0.6910 7.64   40            785           124.000  3.64
319  12.16 0.770 0.6300 5.90   40            785           249.000  3.64
320  11.63 0.770 0.6000 5.35   40            785           375.000  3.64
479  12.31 0.750 0.5610 5.14   30            755           210.295  2.95
480  12.24 0.740 0.5801 5.24   30            755           210.295  2.95
481   9.86 0.720 0.6405 4.53   30            755           210.295  2.95
491   8.35 0.690 0.5692 3.26   30            755           210.295  2.95
492  11.02 0.650 0.6530 4.67   30            755           210.295  2.95
493  12.39 0.630 0.6981 5.40   30            755           210.295  2.95
494  12.55 0.630 0.6637 5.25   30            755           210.295  2.95
495  12.96 0.750 0.6314 6.13   30            745            23.154  3.15
496  13.46 0.790 0.6758 7.19   30            737            65.514  3.21
497  13.52 0.900 0.7002 8.52   30            716            54.480  3.30
594  12.50 0.580 0.6540 4.76   30            786            22.900  3.20
595  12.80 0.600 0.6630 5.10   30            780            23.200  3.22
596  13.10 0.740 0.5680 5.53   30            777            23.700  3.29
597   9.20 0.760 0.4450 3.10   30            762            19.300  3.31
598  10.30 0.680 0.4310 3.02   30            764            22.700  3.24
599   7.74 0.620 0.4700 2.26   30            768            25.000  3.17
600  13.90 0.720 0.5850 5.53   30            777            23.700  3.29
601  13.00 0.740 0.6140 5.90   30            762            19.300  3.31
602  10.70 0.660 0.5800 4.10   30            764            22.700  3.24
603  17.55 0.807 0.6720 9.52   30            795            99.300  3.40
604  16.52 0.813 0.6230 8.37   30            780            28.400  3.53
605  16.22 0.809 0.5600 7.36   30            785           218.400  3.49
728  11.45 0.840 0.6130 5.90   40            732            70.000  3.56
729  10.29 0.750 0.6400 4.94   40            748            24.900  3.49
730   9.47 0.540 0.6060 3.10   40            697            10.600  3.14
731  10.68 0.890 0.6140 5.83   40            732            70.000  3.56
...  ...   ...   ...    ...    ...           ...           ...      ...
761   8.70 0.890 0.640  5.00   40            749            26.500  3.91
762   6.90 0.790 0.470  2.60   40            765            24.300  3.84
763   6.00 0.760 0.480  2.20   40            765            24.300  3.84
764   9.50 0.900 0.560  4.80   40            749            26.500  3.91
765   9.80 0.880 0.650  5.60   40            749            26.500  3.91
766   8.70 0.870 0.590  4.50   40            749            26.500  3.91
767   6.40 0.780 0.510  2.60   40            765            24.300  3.84
768   7.40 0.780 0.480  2.80   40            765            24.300  3.84
769   6.60 0.740 0.380  1.80   40            765            24.300  3.84
877   4.16 0.992 0.479  1.98   20            642            71.504  2.30
878   9.69 0.876 0.518  4.39   20            642            71.504  2.30
879   4.76 0.940 0.563  2.52   20            644           100.300  2.54
880   9.62 0.922 0.620  5.50   20            644           100.300  2.54
883   9.36 0.779 0.406  2.96   20            642            71.504  2.30
884   6.56 0.576 0.345  1.30   20            642            71.504  2.30
885   8.55 0.873 0.559  4.17   20            644           100.300  2.54
886   7.64 0.882 0.570  3.84   20            644           100.300  2.54
887   8.59 0.877 0.462  3.48   20            642            71.504  2.30
888   7.78 0.992 0.553  3.97   20            644           100.300  2.54
1038 11.87 0.680 0.552  4.46   40            720            49.500  3.61
1039 13.17 0.760 0.619  6.20   40            707            33.300  3.58
1040 15.38 0.780 0.692  8.30   40            730            49.500  3.61
1041 13.14 0.780 0.629  6.45   40            730            49.500  3.61
1042 14.28 0.780 0.653  7.27   40            730            49.500  3.61
1043 13.75 0.780 0.612  6.56   40            730            49.500  3.61
1044 12.74 0.760 0.556  5.38   40            730            49.500  3.61
1045 14.26 0.780 0.678  7.54   40            730            49.500  3.61
1046 13.78 0.780 0.598  6.42   40            730            49.500  3.61
1047  6.69 0.680 0.420  1.90   40            765            32.640  3.67
1048 12.17 0.860 0.460  4.80   40            712            34.200  3.72
     MnkDap1M VolRatioS1 ... SMILESsnamep1M_PTBDTffDTBT.1
317  24.0     0.97       ... 0
318  72.9     0.97       ... 0
319  40.0     0.97       ... 0
320  48.0     0.97       ... 0
479  68.5     1.00       ... 0
480  68.5     1.00       ... 0
481  68.5     1.00       ... 0
491  68.5     1.00       ... 0
492  68.5     1.00       ... 0
493  68.5     1.00       ... 0
494  68.5     1.00       ... 0
495  10.2     1.00       ... 0
496  18.3     1.00       ... 0
497  22.7     1.00       ... 0
594  18.3     1.00       ... 0
595  16.8     1.00       ... 0
596  15.9     1.00       ... 0
597  14.6     1.00       ... 0
598  16.1     1.00       ... 0
599  16.7     1.00       ... 0
600  15.9     1.00       ... 0
601  14.6     1.00       ... 0
602  16.1     1.00       ... 0
603  30.1     1.00       ... 0
604  16.7     1.00       ... 0
605  70.0     1.00       ... 0
728  41.3     1.00       ... 0
729  16.7     1.00       ... 0
730   3.4     1.00       ... 0
731  41.3     1.00       ... 0
...  ...      ...            ...
761  17.0     1          ... 0
762  18.0     1          ... 0
763  18.0     1          ... 0
764  17.0     1          ... 0
765  17.0     1          ... 0
766  17.0     1          ... 0
767  18.0     1          ... 0
768  18.0     1          ... 0
769  18.0     1          ... 0
877  21.8     1          ... 0
878  21.8     1          ... 0
879  34.0     1          ... 0
880  34.0     1          ... 0
883  21.8     1          ... 0
884  21.8     1          ... 0
885  34.0     1          ... 0
886  34.0     1          ... 0
887  21.8     1          ... 0
888  34.0     1          ... 0
1038 27.5     1          ... 0
1039 22.2     1          ... 0
1040 27.5     1          ... 0
1041 27.5     1          ... 0
1042 27.5     1          ... 0
1043 27.5     1          ... 0
1044 27.5     1          ... 0
1045 27.5     1          ... 0
1046 27.5     1          ... 0
1047 19.2     1          ... 0
1048 18.0     1          ... 1
     Lay6electronodes2_Ag.1 Lay6electronodes2_Al.1 Additivesname_.1
317  1                      0                      1
318  1                      0                      1
319  1                      0                      1
320  1                      0                      1
479  0                      1                      1
480  0                      1                      1
481  0                      1                      1
491  0                      1                      0
492  0                      1                      0
493  0                      1                      0
494  0                      1                      0
495  0                      1                      1
496  0                      1                      1
497  0                      1                      1
594  0                      1                      0
595  0                      1                      0
596  0                      1                      0
597  0                      1                      0
598  0                      1                      0
599  0                      1                      0
600  0                      1                      0
601  0                      1                      0
602  0                      1                      0
603  0                      1                      0
604  0                      1                      0
605  0                      1                      0
728  0                      1                      1
729  0                      1                      1
730  0                      1                      1
731  0                      1                      1
...  ...                    ...                    ...
761  0                      1                      1
762  0                      1                      1
763  0                      1                      1
764  0                      1                      1
765  0                      1                      1
766  0                      1                      1
767  0                      1                      1
768  0                      1                      1
769  0                      1                      1
877  1                      0                      1
878  1                      0                      0
879  1                      0                      1
880  1                      0                      0
883  1                      0                      0
884  1                      0                      0
885  1                      0                      0
886  1                      0                      0
887  1                      0                      0
888  1                      0                      0
1038 0                      1                      1
1039 0                      1                      1
1040 0                      1                      1
1041 0                      1                      1
1042 0                      1                      1
1043 0                      1                      1
1044 0                      1                      0
1045 0                      1                      1
1046 0                      1                      1
1047 0                      1                      1
1048 0                      1                      1
     Additivesname_DIO.1 namessolvent1_CB.1 namessolvent1_CF.1
317  0                   1                  0
318  0                   1                  0
319  0                   1                  0
320  0                   1                  0
479  0                   0                  0
480  0                   0                  0
481  0                   0                  0
491  1                   0                  0
492  1                   0                  0
493  1                   0                  0
494  1                   0                  0
495  0                   0                  0
496  0                   0                  0
497  0                   0                  0
594  1                   0                  0
595  1                   0                  0
596  1                   0                  0
597  1                   0                  0
598  1                   0                  0
599  1                   0                  0
600  1                   0                  0
601  1                   0                  0
602  1                   0                  0
603  1                   1                  0
604  1                   1                  0
605  1                   1                  0
728  0                   0                  0
729  0                   0                  0
730  0                   0                  0
731  0                   0                  0
...  ...                 ...                ...
761  0                   0                  0
762  0                   0                  0
763  0                   0                  0
764  0                   0                  0
765  0                   0                  0
766  0                   0                  0
767  0                   0                  0
768  0                   0                  0
769  0                   0                  0
877  0                   0                  0
878  1                   0                  0
879  0                   0                  0
880  1                   0                  0
883  1                   0                  0
884  1                   0                  0
885  1                   0                  0
886  1                   0                  0
887  1                   0                  0
888  1                   0                  0
1038 0                   0                  0
1039 0                   0                  0
1040 0                   0                  0
1041 0                   0                  0
1042 0                   0                  0
1043 0                   0                  0
1044 1                   0                  0
1045 0                   0                  0
1046 0                   0                  0
1047 0                   0                  1
1048 0                   0                  1
     namessolvent1_oDCB.1 namessolvent2_.1 namessolvent2_oDCB.1
317  0                    0                1
318  0                    0                1
319  0                    0                1
320  0                    0                1
479  1                    1                0
480  1                    1                0
481  1                    1                0
491  1                    1                0
492  1                    1                0
493  1                    1                0
494  1                    1                0
495  1                    1                0
496  1                    1                0
497  1                    1                0
594  1                    1                0
595  1                    1                0
596  1                    1                0
597  1                    1                0
598  1                    1                0
599  1                    1                0
600  1                    1                0
601  1                    1                0
602  1                    1                0
603  0                    1                0
604  0                    1                0
605  0                    1                0
728  1                    1                0
729  1                    1                0
730  1                    1                0
731  1                    1                0
...  ...                  ...              ...
761  1                    1                0
762  1                    1                0
763  1                    1                0
764  1                    1                0
765  1                    1                0
766  1                    1                0
767  1                    1                0
768  1                    1                0
769  1                    1                0
877  1                    1                0
878  1                    1                0
879  1                    1                0
880  1                    1                0
883  1                    1                0
884  1                    1                0
885  1                    1                0
886  1                    1                0
887  1                    1                0
888  1                    1                0
1038 1                    1                0
1039 1                    1                0
1040 1                    1                0
1041 1                    1                0
1042 1                    1                0
1043 1                    1                0
1044 1                    1                0
1045 1                    1                0
1046 1                    1                0
1047 0                    1                0
1048 0                    1                0

In [10]:
listVar<-c("Jsc","Voc","FF","PCE")
NumVar<-length(listVar)

In [17]:
#------------------------------
ifname0<- "DataAcetyleneConversion.csv"
# alldata2 <- read.delim(rmatrix2, row.names=1,header=T, sep= ",", as.is=TRUE, strip.white=FALSE)
# cor(alldata2)
listVar<-c("Jsc","Voc","FF","PCE")
NumVar<-length(listVar)

#ListAR<-c("kknn")
#ListAR<-c("kknn","gcvEarth","ppr")
ListAR<-c("lars","monmlp","gaussprRadial","svmRadialCost","brnn","WM","kknn","gcvEarth","ppr","Rborist","gaussprLinear","nnls","M5Rules","knn","svmLinear")
#ListAR<-c("xgbLinear","xgbDART","M5Rules","M5","extraTrees","rf")
NumAR<-length(ListAR)
x <- matrix(nrow=NumVar, ncol=NumAR)
rownames(x) <- listVar
colnames(x) <- ListAR

** Ensemble 1
4.118527e-06
** 4.118527e-06

** Ensemble 1
6.216508e-09
** 6.216508e-09

** Ensemble 1
6.251344e-07
** 6.251344e-07

** Ensemble 1
4.900116e-06
** 4.900116e-06

** Ensemble 1
1.747573e-08
** 1.747573e-08

** Ensemble 1
1.317286e-09
** 1.317286e-09

** Ensemble 1
7.916244e-06
** 7.916244e-06

** Ensemble 1
8.39106e-09
** 8.39106e-09

** Ensemble 1
9.077683e-07
** 9.077683e-07

** Ensemble 1
6.294805e-06
** 6.294805e-06

** Ensemble 1
1.478003e-06
** 1.478003e-06

** Ensemble 1
1.654628e-09
** 1.654628e-09

** Ensemble 1
5.395387e-06
** 5.395387e-06

** Ensemble 1
2.831955e-08
** 2.831955e-08

** Ensemble 1
6.103264e-07
** 6.103264e-07

** Ensemble 1
4.055431e-06
** 4.055431e-06

** Ensemble 1
1.449595e-06
** 1.449595e-06

** Ensemble 1
6.489958e-09
** 6.489958e-09

** Ensemble 1
4.497672e-06
** 4.497672e-06

** Ensemble 1
1.698773e-06
** 1.698773e-06

** Ensemble 1
1.881962e-09
** 1.881962e-09

** Ensemble 1
5.629244e-06
** 5.629244e-06

** Ensemble 1
7.117132e-09
** 7.117132e-09

** Ensemble 1
5.712023e-09
** 5.712023e-09

** Ensemble 1
3.936625e-06
** 3.936625e-06

** Ensemble 1
5.189583e-08
** 5.189583e-08

** Ensemble 1
3.433308e-07
** 3.433308e-07

** Ensemble 1
4.600378e-06
** 4.600378e-06

** Ensemble 1
4.197492e-08
** 4.197492e-08

** Ensemble 1
3.015017e-09
** 3.015017e-09

** Ensemble 1
4.202015e-06
** 4.202015e-06

** Ensemble 1
4.770455e-07
** 4.770455e-07

** Ensemble 1
1.774022e-09
** 1.774022e-09

** Ensemble 1
6.19258e-06
** 6.19258e-06

** Ensemble 1
2.327004e-06
** 2.327004e-06

** Ensemble 1
3.647382e-07
** 3.647382e-07

** Ensemble 1
4.40807e-06
** 4.40807e-06

** Ensemble 1
1.326651e-08
** 1.326651e-08

** Ensemble 1
2.344459e-09
** 2.344459e-09

** Ensemble 1
5.408679e-06
** 5.408679e-06

** Ensemble 1
1.014112e-06
** 1.014112e-06

** Ensemble 1
1.802497e-09
** 1.802497e-09

** Ensemble 1
5.144356e-06
** 5.144356e-06

** Ensemble 1
1.979573e-06
** 1.979573e-06

** Ensemble 1
5.604191e-07
** 5.604191e-07

** Ensemble 1
3.709484e-06
** 3.709484e-06

** Ensemble 1
1.833449e-06
** 1.833449e-06

** Ensemble 1
2.346382e-09
** 2.346382e-09

** Ensemble 1
5.728904e-06
** 5.728904e-06

** Ensemble 1
9.978814e-09
** 9.978814e-09

** Ensemble 1
2.134017e-09
** 2.134017e-09

** Ensemble 1
6.056464e-06
** 6.056464e-06

** Ensemble 1
4.548537e-08
** 4.548537e-08

** Ensemble 1
8.105511e-07
** 8.105511e-07

** Ensemble 1
5.219577e-06
** 5.219577e-06

** Ensemble 1
1.117326e-08
** 1.117326e-08

** Ensemble 1
2.597682e-09
** 2.597682e-09

** Ensemble 1
4.107547e-06
** 4.107547e-06

** Ensemble 1
1.422628e-06
** 1.422628e-06

** Ensemble 1
3.169064e-08
** 3.169064e-08

** Ensemble 1
4.21217e-06
** 4.21217e-06

** Ensemble 1
1.718238e-06
** 1.718238e-06

** Ensemble 1
2.415049e-09
** 2.415049e-09

** Ensemble 1
9.49979e-06
** 9.49979e-06

** Ensemble 1
1.507646e-08
** 1.507646e-08

** Ensemble 1
5.14246e-07
** 5.14246e-07

** Ensemble 1
2.901959e-06
** 2.901959e-06

** Ensemble 1
1.028776e-06
** 1.028776e-06

** Ensemble 1
5.605157e-07
** 5.605157e-07

** Ensemble 1
6.295275e-06
** 6.295275e-06

** Ensemble 1
7.542227e-09
** 7.542227e-09

** Ensemble 1
1.393142e-07
** 1.393142e-07

** Ensemble 1
4.215809e-06
** 4.215809e-06

** Ensemble 1
4.146832e-09
** 4.146832e-09

** Ensemble 1
4.898734e-07
** 4.898734e-07

** Ensemble 1
4.602577e-06
** 4.602577e-06

** Ensemble 1
8.701514e-09
** 8.701514e-09

** Ensemble 1
2.155942e-09
** 2.155942e-09

** Ensemble 1
4.962187e-06
** 4.962187e-06

** Ensemble 1
2.242143e-06
** 2.242143e-06

** Ensemble 1
5.810271e-09
** 5.810271e-09

** Ensemble 1
4.227645e-06
** 4.227645e-06

** Ensemble 1
3.298179e-06
** 3.298179e-06

** Ensemble 1
3.638654e-07
** 3.638654e-07

** Ensemble 1
4.632041e-06
** 4.632041e-06

** Ensemble 1
1.985727e-06
** 1.985727e-06

** Ensemble 1
9.668886e-07
** 9.668886e-07

** Ensemble 1
4.641761e-06
** 4.641761e-06

** Ensemble 1
1.723304e-06
** 1.723304e-06

** Ensemble 1
3.964632e-09
** 3.964632e-09

** Ensemble 1
4.168925e-06
** 4.168925e-06

** Ensemble 1
1.235763e-08
** 1.235763e-08

** Ensemble 1
1.878706e-09
** 1.878706e-09

** Ensemble 1
4.914459e-06
** 4.914459e-06

** Ensemble 1
5.128563e-09
** 5.128563e-09

** Ensemble 1
2.715076e-09
** 2.715076e-09

** Ensemble 1
8.898769e-06
** 8.898769e-06

** Ensemble 1
1.844499e-06
** 1.844499e-06

** Ensemble 1
4.30195e-07
** 4.30195e-07

** Ensemble 1
4.739783e-06
** 4.739783e-06

** Ensemble 1
1.872323e-06
** 1.872323e-06

** Ensemble 1
4.931484e-09
** 4.931484e-09

** Ensemble 1
4.022696e-06
** 4.022696e-06

** Ensemble 1
1.637412e-08
** 1.637412e-08

** Ensemble 1
5.284708e-07
** 5.284708e-07

** Ensemble 1
4.442148e-06
** 4.442148e-06

** Ensemble 1
2.112622e-08
** 2.112622e-08

** Ensemble 1
5.500796e-09
** 5.500796e-09

** Ensemble 1
7.976428e-06
** 7.976428e-06

** Ensemble 1
1.428902e-06
** 1.428902e-06

** Ensemble 1
4.527156e-07
** 4.527156e-07

** Ensemble 1
7.549112e-06
** 7.549112e-06

** Ensemble 1
1.330319e-06
** 1.330319e-06

** Ensemble 1
2.342743e-07
** 2.342743e-07

** Ensemble 1
7.377902e-06
** 7.377902e-06

** Ensemble 1
9.569652e-09
** 9.569652e-09

** Ensemble 1
2.800829e-09
** 2.800829e-09

** Ensemble 1
3.896254e-06
** 3.896254e-06

** Ensemble 1
1.56933e-06
** 1.56933e-06

** Ensemble 1
4.251064e-07
** 4.251064e-07

** Ensemble 1
5.341759e-06
** 5.341759e-06

** Ensemble 1
9.476293e-09
** 9.476293e-09

** Ensemble 1
4.538542e-07
** 4.538542e-07

** Ensemble 1
4.73915e-06
** 4.73915e-06

** Ensemble 1
1.469192e-07
** 1.469192e-07

** Ensemble 1
6.459791e-07
** 6.459791e-07

** Ensemble 1
4.084088e-06
** 4.084088e-06

** Ensemble 1
3.141132e-06
** 3.141132e-06

** Ensemble 1
5.334895e-07
** 5.334895e-07

** Ensemble 1
3.675829e-06
** 3.675829e-06

** Ensemble 1
1.387318e-06
** 1.387318e-06

** Ensemble 1
1.904466e-09
** 1.904466e-09

** Ensemble 1
5.83236e-06
** 5.83236e-06

** Ensemble 1
1.234298e-06
** 1.234298e-06

** Ensemble 1
2.788906e-09
** 2.788906e-09

** Ensemble 1
5.451192e-06
** 5.451192e-06

** Ensemble 1
1.675445e-06
** 1.675445e-06

** Ensemble 1
2.358371e-09
** 2.358371e-09

** Ensemble 1
6.068851e-06
** 6.068851e-06

** Ensemble 1
1.972668e-08
** 1.972668e-08

** Ensemble 1
1.606023e-09
** 1.606023e-09

** Ensemble 1
1.186906e-05
** 1.186906e-05

** Ensemble 1
2.82602e-08
** 2.82602e-08

** Ensemble 1
9.496795e-07
** 9.496795e-07

** Ensemble 1
6.522901e-06
** 6.522901e-06

** Ensemble 1
2.663725e-06
** 2.663725e-06

** Ensemble 1
6.03144e-07
** 6.03144e-07

** Ensemble 1
3.716589e-06
** 3.716589e-06

** Ensemble 1
1.177052e-06
** 1.177052e-06

** Ensemble 1
4.821223e-09
** 4.821223e-09

** Ensemble 1
6.199843e-06
** 6.199843e-06

** Ensemble 1
1.920576e-06
** 1.920576e-06

** Ensemble 1
2.243295e-07
** 2.243295e-07

** Ensemble 1
6.100945e-06
** 6.100945e-06

** Ensemble 1
3.147588e-06
** 3.147588e-06

** Ensemble 1
2.81142e-09
** 2.81142e-09

** Ensemble 1
5.400239e-06
** 5.400239e-06

** Ensemble 1
1.063741e-08
** 1.063741e-08

** Ensemble 1
2.17589e-09
** 2.17589e-09

** Ensemble 1
2.916391e-06
** 2.916391e-06

** Ensemble 1
1.110133e-06
** 1.110133e-06

** Ensemble 1
7.943516e-07
** 7.943516e-07

** Ensemble 1
4.540161e-06
** 4.540161e-06

** Ensemble 1
7.758926e-09
** 7.758926e-09

** Ensemble 1
7.752394e-07
** 7.752394e-07

** Ensemble 1
4.410336e-06
** 4.410336e-06

** Ensemble 1
1.280549e-06
** 1.280549e-06

** Ensemble 1
2.565968e-09
** 2.565968e-09

** Ensemble 1
4.288769e-06
** 4.288769e-06

** Ensemble 1
1.127601e-06
** 1.127601e-06

** Ensemble 1
1.282392e-09
** 1.282392e-09

** Ensemble 1
5.366001e-06
** 5.366001e-06

** Ensemble 1
8.864695e-09
** 8.864695e-09

** Ensemble 1
4.386105e-07
** 4.386105e-07

** Ensemble 1
4.352704e-06
** 4.352704e-06

** Ensemble 1
1.86592e-08
** 1.86592e-08

** Ensemble 1
1.967082e-06
** 1.967082e-06

** Ensemble 1
5.844806e-06
** 5.844806e-06

** Ensemble 1
1.988771e-06
** 1.988771e-06

** Ensemble 1
4.604237e-07
** 4.604237e-07

** Ensemble 1
4.578035e-06
** 4.578035e-06

** Ensemble 1
1.771646e-06
** 1.771646e-06

** Ensemble 1
3.19789e-09
** 3.19789e-09

** Ensemble 1
6.345769e-06
** 6.345769e-06

** Ensemble 1
1.615322e-06
** 1.615322e-06

** Ensemble 1
9.909556e-09
** 9.909556e-09

** Ensemble 1
5.317338e-06
** 5.317338e-06

** Ensemble 1
1.920606e-06
** 1.920606e-06

** Ensemble 1
3.956741e-09
** 3.956741e-09

** Ensemble 1
5.943272e-06
** 5.943272e-06

** Ensemble 1
9.413171e-09
** 9.413171e-09

** Ensemble 1
2.168881e-08
** 2.168881e-08

** Ensemble 1
8.183478e-06
** 8.183478e-06

** Ensemble 1
8.710615e-08
** 8.710615e-08

** Ensemble 1
2.484641e-09
** 2.484641e-09

** Ensemble 1
7.264575e-06
** 7.264575e-06

** Ensemble 1
1.295369e-06
** 1.295369e-06

** Ensemble 1
2.622412e-09
** 2.622412e-09

** Ensemble 1
4.45324e-06
** 4.45324e-06

** Ensemble 1
1.490806e-06
** 1.490806e-06

** Ensemble 1
3.959927e-09
** 3.959927e-09

** Ensemble 1
4.506824e-06
** 4.506824e-06

** Ensemble 1
1.642408e-06
** 1.642408e-06

** Ensemble 1
5.517599e-07
** 5.517599e-07

** Ensemble 1
4.409066e-06
** 4.409066e-06

** Ensemble 1
2.163545e-08
** 2.163545e-08

** Ensemble 1
1.078625e-09
** 1.078625e-09

** Ensemble 1
5.92342e-06
** 5.92342e-06

** Ensemble 1
3.160935e-07
** 3.160935e-07

** Ensemble 1
2.137908e-09
** 2.137908e-09

** Ensemble 1
7.236362e-06
** 7.236362e-06

** Ensemble 1
1.81086e-06
** 1.81086e-06

** Ensemble 1
6.227521e-07
** 6.227521e-07

** Ensemble 1
3.638752e-06
** 3.638752e-06

** Ensemble 1
1.520695e-06
** 1.520695e-06

** Ensemble 1
1.012799e-09
** 1.012799e-09

** Ensemble 1
8.469685e-06
** 8.469685e-06

** Ensemble 1
1.096703e-08
** 1.096703e-08

** Ensemble 1
6.875e-07
** 6.875e-07

** Ensemble 1
4.589025e-06
** 4.589025e-06

** Ensemble 1
7.698792e-09
** 7.698792e-09

** Ensemble 1
7.849384e-07
** 7.849384e-07

** Ensemble 1
4.236004e-06
** 4.236004e-06

** Ensemble 1
6.847311e-09
** 6.847311e-09

** Ensemble 1
3.187637e-09
** 3.187637e-09

** Ensemble 1
5.231697e-06
** 5.231697e-06

** Ensemble 1
2.020346e-06
** 2.020346e-06

** Ensemble 1
9.430162e-07
** 9.430162e-07

** Ensemble 1
5.333331e-06
** 5.333331e-06

** Ensemble 1
1.19828e-06
** 1.19828e-06

** Ensemble 1
4.160954e-08
** 4.160954e-08

** Ensemble 1
8.850048e-06
** 8.850048e-06

** Ensemble 1
2.028085e-06
** 2.028085e-06

** Ensemble 1
2.006317e-09
** 2.006317e-09

** Ensemble 1
4.466833e-06
** 4.466833e-06

** Ensemble 1
1.394108e-07
** 1.394108e-07

** Ensemble 1
6.581762e-09
** 6.581762e-09

** Ensemble 1
4.848939e-06
** 4.848939e-06

** Ensemble 1
8.869071e-09
** 8.869071e-09

** Ensemble 1
1.511303e-09
** 1.511303e-09

** Ensemble 1
8.880457e-06
** 8.880457e-06

** Ensemble 1
1.382351e-06
** 1.382351e-06

** Ensemble 1
2.836564e-09
** 2.836564e-09

** Ensemble 1
8.266371e-06
** 8.266371e-06

** Ensemble 1
2.615801e-06
** 2.615801e-06

** Ensemble 1
6.137207e-07
** 6.137207e-07

** Ensemble 1
3.88475e-06
** 3.88475e-06

** Ensemble 1
1.62763e-06
** 1.62763e-06

** Ensemble 1
1.386684e-06
** 1.386684e-06

** Ensemble 1
4.406042e-06
** 4.406042e-06

** Ensemble 1
2.014795e-06
** 2.014795e-06

** Ensemble 1
1.06131e-09
** 1.06131e-09

** Ensemble 1
4.735221e-06
** 4.735221e-06

** Ensemble 1
1.734933e-06
** 1.734933e-06

** Ensemble 1
1.702647e-08
** 1.702647e-08

** Ensemble 1
4.899928e-06
** 4.899928e-06

** Ensemble 1
1.187475e-06
** 1.187475e-06

** Ensemble 1
2.59438e-09
** 2.59438e-09

** Ensemble 1
4.098875e-06
** 4.098875e-06

** Ensemble 1
1.668335e-08
** 1.668335e-08

** Ensemble 1
2.466354e-09
** 2.466354e-09

** Ensemble 1
4.356953e-06
** 4.356953e-06

** Ensemble 1
1.402684e-06
** 1.402684e-06

** Ensemble 1
3.781283e-07
** 3.781283e-07

** Ensemble 1
4.555587e-06
** 4.555587e-06

** Ensemble 1
5.324683e-08
** 5.324683e-08

** Ensemble 1
6.552666e-07
** 6.552666e-07

** Ensemble 1
6.389928e-06
** 6.389928e-06

** Ensemble 1
1.809574e-06
** 1.809574e-06

** Ensemble 1
4.297495e-07
** 4.297495e-07

** Ensemble 1
4.616804e-06
** 4.616804e-06

** Ensemble 1
1.141571e-06
** 1.141571e-06

** Ensemble 1
6.254206e-07
** 6.254206e-07

** Ensemble 1
3.605912e-06
** 3.605912e-06

** Ensemble 1
3.49157e-06
** 3.49157e-06

** Ensemble 1
7.29535e-09
** 7.29535e-09

** Ensemble 1
5.407264e-06
** 5.407264e-06

** Ensemble 1
1.358576e-06
** 1.358576e-06

** Ensemble 1
4.923536e-07
** 4.923536e-07

** Ensemble 1
7.166291e-06
** 7.166291e-06

** Ensemble 1
1.816061e-06
** 1.816061e-06

** Ensemble 1
4.359948e-07
** 4.359948e-07

** Ensemble 1
6.927223e-06
** 6.927223e-06

** Ensemble 1
1.184623e-06
** 1.184623e-06

** Ensemble 1
4.202327e-09
** 4.202327e-09

** Ensemble 1
3.699465e-06
** 3.699465e-06

** Ensemble 1
1.856535e-06
** 1.856535e-06

** Ensemble 1
5.20803e-09
** 5.20803e-09

** Ensemble 1
4.803485e-06
** 4.803485e-06

** Ensemble 1
1.460326e-06
** 1.460326e-06

** Ensemble 1
1.110044e-06
** 1.110044e-06

** Ensemble 1
4.321903e-06
** 4.321903e-06

** Ensemble 1
6.771674e-09
** 6.771674e-09

** Ensemble 1
1.99393e-09
** 1.99393e-09

** Ensemble 1
3.704273e-06
** 3.704273e-06

** Ensemble 1
1.66892e-06
** 1.66892e-06

** Ensemble 1
2.451853e-09
** 2.451853e-09

** Ensemble 1
4.770108e-06
** 4.770108e-06

** Ensemble 1
9.208078e-09
** 9.208078e-09

** Ensemble 1
3.184974e-09
** 3.184974e-09

** Ensemble 1
6.65882e-06
** 6.65882e-06

** Ensemble 1
2.047041e-06
** 2.047041e-06

** Ensemble 1
5.986307e-07
** 5.986307e-07

** Ensemble 1
6.340661e-06
** 6.340661e-06

** Ensemble 1
1.504024e-06
** 1.504024e-06

** Ensemble 1
7.072008e-07
** 7.072008e-07

** Ensemble 1
1.260969e-05
** 1.260969e-05

** Ensemble 1
9.691819e-07
** 9.691819e-07

** Ensemble 1
6.270308e-07
** 6.270308e-07

** Ensemble 1
5.01181e-06
** 5.01181e-06

** Ensemble 1
2.127317e-06
** 2.127317e-06

** Ensemble 1
2.042715e-08
** 2.042715e-08

** Ensemble 1
4.781105e-06
** 4.781105e-06

** Ensemble 1
5.791062e-09
** 5.791062e-09

** Ensemble 1
9.165861e-07
** 9.165861e-07

** Ensemble 1
4.698056e-06
** 4.698056e-06

** Ensemble 1
2.147652e-06
** 2.147652e-06

** Ensemble 1
1.012296e-09
** 1.012296e-09

** Ensemble 1
4.198149e-06
** 4.198149e-06

** Ensemble 1
4.25764e-07
** 4.25764e-07

** Ensemble 1
1.337922e-07
** 1.337922e-07

** Ensemble 1
9.337987e-06
** 9.337987e-06

** Ensemble 1
1.086944e-08
** 1.086944e-08

** Ensemble 1
5.804396e-07
** 5.804396e-07

** Ensemble 1
5.510282e-06
** 5.510282e-06

** Ensemble 1
1.672529e-06
** 1.672529e-06

** Ensemble 1
5.719245e-09
** 5.719245e-09

** Ensemble 1
9.264639e-06
** 9.264639e-06

** Ensemble 1
1.212135e-06
** 1.212135e-06

** Ensemble 1
6.15421e-07
** 6.15421e-07

** Ensemble 1
3.942457e-06
** 3.942457e-06

** Ensemble 1
1.380222e-06
** 1.380222e-06

** Ensemble 1
2.315721e-09
** 2.315721e-09

** Ensemble 1
4.762908e-06
** 4.762908e-06

** Ensemble 1
6.487372e-08
** 6.487372e-08

** Ensemble 1
1.119197e-06
** 1.119197e-06

** Ensemble 1
3.551071e-06
** 3.551071e-06

** Ensemble 1
1.221118e-06
** 1.221118e-06

** Ensemble 1
1.307179e-06
** 1.307179e-06

** Ensemble 1
6.693709e-06
** 6.693709e-06

** Ensemble 1
3.781848e-07
** 3.781848e-07

** Ensemble 1
2.490234e-09
** 2.490234e-09

** Ensemble 1
4.198811e-06
** 4.198811e-06

** Ensemble 1
1.259223e-06
** 1.259223e-06

** Ensemble 1
2.402086e-08
** 2.402086e-08

** Ensemble 1
4.94683e-06
** 4.94683e-06

** Ensemble 1
9.274402e-07
** 9.274402e-07

** Ensemble 1
8.140984e-09
** 8.140984e-09

** Ensemble 1
7.132654e-06
** 7.132654e-06

** Ensemble 1
3.183669e-08
** 3.183669e-08

** Ensemble 1
4.121321e-07
** 4.121321e-07

** Ensemble 1
7.201911e-06
** 7.201911e-06

** Ensemble 1
1.118564e-08
** 1.118564e-08

** Ensemble 1
3.457304e-09
** 3.457304e-09

** Ensemble 1
4.73774e-06
** 4.73774e-06

** Ensemble 1
1.426221e-06
** 1.426221e-06

** Ensemble 1
1.777956e-08
** 1.777956e-08

** Ensemble 1
4.429024e-06
** 4.429024e-06

** Ensemble 1
1.363626e-06
** 1.363626e-06

** Ensemble 1
2.731215e-08
** 2.731215e-08

** Ensemble 1
1.350899e-05
** 1.350899e-05

** Ensemble 1
1.777422e-06
** 1.777422e-06

** Ensemble 1
2.280724e-09
** 2.280724e-09

** Ensemble 1
4.530998e-06
** 4.530998e-06

** Ensemble 1
2.139802e-08
** 2.139802e-08

** Ensemble 1
4.17974e-07
** 4.17974e-07

** Ensemble 1
5.000724e-06
** 5.000724e-06

** Ensemble 1
1.607159e-06
** 1.607159e-06

** Ensemble 1
3.452533e-07
** 3.452533e-07

** Ensemble 1
5.343758e-06
** 5.343758e-06

** Ensemble 1
1.618022e-06
** 1.618022e-06

** Ensemble 1
7.428461e-07
** 7.428461e-07

** Ensemble 1
4.243955e-06
** 4.243955e-06

** Ensemble 1
1.891928e-06
** 1.891928e-06

** Ensemble 1
1.631497e-09
** 1.631497e-09

** Ensemble 1
5.516635e-06
** 5.516635e-06

** Ensemble 1
1.587412e-06
** 1.587412e-06

** Ensemble 1
1.005577e-06
** 1.005577e-06

** Ensemble 1
4.309114e-06
** 4.309114e-06

** Ensemble 1
1.508889e-06
** 1.508889e-06

** Ensemble 1
6.953026e-07
** 6.953026e-07

** Ensemble 1
4.717691e-06
** 4.717691e-06

** Ensemble 1
9.833688e-07
** 9.833688e-07

** Ensemble 1
6.609073e-09
** 6.609073e-09

** Ensemble 1
8.509449e-06
** 8.509449e-06

** Ensemble 1
6.894714e-09
** 6.894714e-09

** Ensemble 1
7.609723e-07
** 7.609723e-07

** Ensemble 1
4.047575e-06
** 4.047575e-06

** Ensemble 1
7.632611e-07
** 7.632611e-07

** Ensemble 1
7.011766e-07
** 7.011766e-07

** Ensemble 1
3.655252e-06
** 3.655252e-06

** Ensemble 1
1.698405e-06
** 1.698405e-06

** Ensemble 1
4.599267e-07
** 4.599267e-07

** Ensemble 1
3.908335e-06
** 3.908335e-06

** Ensemble 1
1.089326e-08
** 1.089326e-08

** Ensemble 1
2.436163e-09
** 2.436163e-09

** Ensemble 1
5.160553e-06
** 5.160553e-06

** Ensemble 1
1.455223e-06
** 1.455223e-06

** Ensemble 1
2.386667e-08
** 2.386667e-08

** Ensemble 1
3.642904e-06
** 3.642904e-06

** Ensemble 1
6.945608e-09
** 6.945608e-09

** Ensemble 1
6.798411e-07
** 6.798411e-07

** Ensemble 1
5.267979e-06
** 5.267979e-06

** Ensemble 1
5.221711e-09
** 5.221711e-09

** Ensemble 1
2.554269e-09
** 2.554269e-09

** Ensemble 1
6.277657e-06
** 6.277657e-06

** Ensemble 1
1.093326e-08
** 1.093326e-08

** Ensemble 1
1.411171e-09
** 1.411171e-09

** Ensemble 1
6.460441e-06
** 6.460441e-06

** Ensemble 1
2.141031e-08
** 2.141031e-08

** Ensemble 1
5.152855e-07
** 5.152855e-07

** Ensemble 1
5.960651e-06
** 5.960651e-06

** Ensemble 1
2.273071e-08
** 2.273071e-08

** Ensemble 1
1.128771e-06
** 1.128771e-06

** Ensemble 1
7.650953e-06
** 7.650953e-06

** Ensemble 1
1.138408e-08
** 1.138408e-08

** Ensemble 1
2.382948e-09
** 2.382948e-09

** Ensemble 1
5.653562e-06
** 5.653562e-06

** Ensemble 1
2.454822e-06
** 2.454822e-06

** Ensemble 1
1.017971e-08
** 1.017971e-08

** Ensemble 1
6.202078e-06
** 6.202078e-06

** Ensemble 1
1.149723e-06
** 1.149723e-06

** Ensemble 1
2.77699e-09
** 2.77699e-09

** Ensemble 1
6.422354e-06
** 6.422354e-06

** Ensemble 1
1.386987e-06
** 1.386987e-06

** Ensemble 1
6.306348e-09
** 6.306348e-09

** Ensemble 1
6.015071e-06
** 6.015071e-06

** Ensemble 1
8.658668e-09
** 8.658668e-09

** Ensemble 1
7.904767e-07
** 7.904767e-07

** Ensemble 1
6.271279e-06
** 6.271279e-06

** Ensemble 1
2.239253e-08
** 2.239253e-08

** Ensemble 1
4.69054e-09
** 4.69054e-09

** Ensemble 1
1.147139e-05
** 1.147139e-05

** Ensemble 1
1.567745e-06
** 1.567745e-06

** Ensemble 1
1.073714e-08
** 1.073714e-08

** Ensemble 1
4.305149e-06
** 4.305149e-06

** Ensemble 1
1.698385e-07
** 1.698385e-07

** Ensemble 1
2.239561e-09
** 2.239561e-09

** Ensemble 1
7.797631e-06
** 7.797631e-06

** Ensemble 1
9.393139e-07
** 9.393139e-07

** Ensemble 1
1.124068e-07
** 1.124068e-07

** Ensemble 1
3.691422e-06
** 3.691422e-06

** Ensemble 1
1.566944e-06
** 1.566944e-06

** Ensemble 1
5.891317e-07
** 5.891317e-07

** Ensemble 1
7.748939e-06
** 7.748939e-06

** Ensemble 1
1.06555e-08
** 1.06555e-08

** Ensemble 1
2.437847e-09
** 2.437847e-09

** Ensemble 1
4.454972e-06
** 4.454972e-06

** Ensemble 1
9.74879e-08
** 9.74879e-08

** Ensemble 1
5.623804e-09
** 5.623804e-09

** Ensemble 1
6.350585e-06
** 6.350585e-06

** Ensemble 1
1.524402e-06
** 1.524402e-06

** Ensemble 1
1.353527e-08
** 1.353527e-08

** Ensemble 1
5.559671e-06
** 5.559671e-06

** Ensemble 1
1.687505e-06
** 1.687505e-06

** Ensemble 1
5.447167e-07
** 5.447167e-07

** Ensemble 1

Error in predict(results.nnet, dataUsed03) :
  object 'results.nnet' not found
Error in data.frame(ydata01, est.Y) : object 'est.Y' not found
Error in se(actual, predicted) : object 'est.Y' not found
Error in is.data.frame(y) : object 'est.Y' not found
Error in xy.coords(x, y, xlabel, ylabel, log) : object 'est.Y' not found
Error in is.data.frame(y) : object 'est.Y' not found

png
  2

In [18]:


for (i in 1:NumVar) {
  set.mesureVar<-i #1:Jsc,2:Voc,3,FF,4:PCE
  
  mindex01<-dataUsed02[,set.mesureVar]
  #mindex<-alldata[,3]  #<-1
  nf01<-dim(dataUsed02)[2]  
  dataUsed03<-data.frame(mindex01,dataUsed02[5:nf01])
  #dataUsed01<-matrix(c(mindex01,rmatrix01[5:nf01]))
  
  #tt01<-which(apply(dataUsed03,2,sd)==0)
  #length(tt01)
  #try(dataUsed04<-dataUsed03[,-c(tt01)])
  
  dimdata<-dim(dataUsed03)
  
  nf02<-dim(dataUsed03)[2]
  
  #========== Set Y ==========
  yset01<-1 
  #===========================
  yname01<-colnames(dataUsed03[yset01])
  ydata01<-dataUsed03[,yset01]
  #-------------------------
  
  xname01<-colnames(dataUsed03)[2:nf02]
  xdata01<- dataUsed03[,-yset01]
  dimdata<-dim(dataUsed03)
  
  dimdata1<-c(dimdata[[1]])
  dimdata2<-c(dimdata[[2]])
  
  #bb<-as.formula(paste("mindex01","~",".", sep=""))
  #-----------------------------

  
  #for(j in seq_along(ARList)){}  
  #for (j in 1:NumAR) {
  for(modelname in ListAR){
    #results.nnet<-train(bb,data=dataUsed03,method=modelname, trControl=trainControl(method="LOOCV"))
    try(results.nnet<-train(mindex01~.,data=dataUsed03,method=modelname, trControl=trainControl(method="LOOCV")))
    
    try(est.Y<-predict(results.nnet,dataUsed03))
    
    try(fdata01<-data.frame(ydata01,est.Y))
    try(RMSE01<-rmse(ydata01,est.Y))
    
    try(s01 <- paste("nData358Mice",listVar[set.mesureVar], modelname,":r = ",sprintf("%5.3f",cor(ydata01,est.Y)),":RMSE = ",sprintf("%5.3f",RMSE01),"sample:",sprintf("%s",dimdata1),"valiable:",sprintf("%s",dimdata2)))
    s02<-paste("Data:",sprintf("%s",ifname0))
    
    #plot(ydata01, est.Y,main=s01,sub=s02)
    #x[i,1]<-cor(ydata01,est.Y)
    # write.csv(x,"ddd.csv")
    
    s03 <- paste("nData358Mice",listVar[set.mesureVar],modelname,".pdf")
    pdf(s03)
    try(plot(ydata01, est.Y,main=s01,sub=s02))
    try(x[i,1]<-cor(ydata01,est.Y))
    dev.off()
    }
  }

Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
  contrasts can be applied only to factors with 2 or more levels
Error in eval(expr, envir) : object 'results.nnet' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found
Error in eval(expr, envir) : object 'est.Y' not found

In [14]:
set.mesureVar<-1 #1:Jsc,2:Voc,3,FF,4:PCE
  
mindex01<-dataUsed02[,set.mesureVar]
  #mindex<-alldata[,3]  #<-1
nf01<-dim(dataUsed02)[2]  
dataUsed03<-data.frame(mindex01,dataUsed02[5:nf01])
#dataUsed01<-matrix(c(mindex01,rmatrix01[5:nf01]))
  
tt01<-which(apply(dataUsed03,2,sd)==0)
print(tt01)

Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"
Warning message in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm):
"NAs introduced by coercion"

named integer(0)

In [15]:
dataUsed02

     Jsc   Voc   FF     PCEmax Lay2thickness Aonsetp1Mfilm MwkDap1M LUMOp1M
317  13.02 0.790 0.6900 7.02   40            785            78.000  3.64
318  14.02 0.790 0.6910 7.64   40            785           124.000  3.64
319  12.16 0.770 0.6300 5.90   40            785           249.000  3.64
320  11.63 0.770 0.6000 5.35   40            785           375.000  3.64
479  12.31 0.750 0.5610 5.14   30            755           210.295  2.95
480  12.24 0.740 0.5801 5.24   30            755           210.295  2.95
481   9.86 0.720 0.6405 4.53   30            755           210.295  2.95
491   8.35 0.690 0.5692 3.26   30            755           210.295  2.95
492  11.02 0.650 0.6530 4.67   30            755           210.295  2.95
493  12.39 0.630 0.6981 5.40   30            755           210.295  2.95
494  12.55 0.630 0.6637 5.25   30            755           210.295  2.95
495  12.96 0.750 0.6314 6.13   30            745            23.154  3.15
496  13.46 0.790 0.6758 7.19   30            737            65.514  3.21
497  13.52 0.900 0.7002 8.52   30            716            54.480  3.30
594  12.50 0.580 0.6540 4.76   30            786            22.900  3.20
595  12.80 0.600 0.6630 5.10   30            780            23.200  3.22
596  13.10 0.740 0.5680 5.53   30            777            23.700  3.29
597   9.20 0.760 0.4450 3.10   30            762            19.300  3.31
598  10.30 0.680 0.4310 3.02   30            764            22.700  3.24
599   7.74 0.620 0.4700 2.26   30            768            25.000  3.17
600  13.90 0.720 0.5850 5.53   30            777            23.700  3.29
601  13.00 0.740 0.6140 5.90   30            762            19.300  3.31
602  10.70 0.660 0.5800 4.10   30            764            22.700  3.24
603  17.55 0.807 0.6720 9.52   30            795            99.300  3.40
604  16.52 0.813 0.6230 8.37   30            780            28.400  3.53
605  16.22 0.809 0.5600 7.36   30            785           218.400  3.49
728  11.45 0.840 0.6130 5.90   40            732            70.000  3.56
729  10.29 0.750 0.6400 4.94   40            748            24.900  3.49
730   9.47 0.540 0.6060 3.10   40            697            10.600  3.14
731  10.68 0.890 0.6140 5.83   40            732            70.000  3.56
...  ...   ...   ...    ...    ...           ...           ...      ...
761   8.70 0.890 0.640  5.00   40            749            26.500  3.91
762   6.90 0.790 0.470  2.60   40            765            24.300  3.84
763   6.00 0.760 0.480  2.20   40            765            24.300  3.84
764   9.50 0.900 0.560  4.80   40            749            26.500  3.91
765   9.80 0.880 0.650  5.60   40            749            26.500  3.91
766   8.70 0.870 0.590  4.50   40            749            26.500  3.91
767   6.40 0.780 0.510  2.60   40            765            24.300  3.84
768   7.40 0.780 0.480  2.80   40            765            24.300  3.84
769   6.60 0.740 0.380  1.80   40            765            24.300  3.84
877   4.16 0.992 0.479  1.98   20            642            71.504  2.30
878   9.69 0.876 0.518  4.39   20            642            71.504  2.30
879   4.76 0.940 0.563  2.52   20            644           100.300  2.54
880   9.62 0.922 0.620  5.50   20            644           100.300  2.54
883   9.36 0.779 0.406  2.96   20            642            71.504  2.30
884   6.56 0.576 0.345  1.30   20            642            71.504  2.30
885   8.55 0.873 0.559  4.17   20            644           100.300  2.54
886   7.64 0.882 0.570  3.84   20            644           100.300  2.54
887   8.59 0.877 0.462  3.48   20            642            71.504  2.30
888   7.78 0.992 0.553  3.97   20            644           100.300  2.54
1038 11.87 0.680 0.552  4.46   40            720            49.500  3.61
1039 13.17 0.760 0.619  6.20   40            707            33.300  3.58
1040 15.38 0.780 0.692  8.30   40            730            49.500  3.61
1041 13.14 0.780 0.629  6.45   40            730            49.500  3.61
1042 14.28 0.780 0.653  7.27   40            730            49.500  3.61
1043 13.75 0.780 0.612  6.56   40            730            49.500  3.61
1044 12.74 0.760 0.556  5.38   40            730            49.500  3.61
1045 14.26 0.780 0.678  7.54   40            730            49.500  3.61
1046 13.78 0.780 0.598  6.42   40            730            49.500  3.61
1047  6.69 0.680 0.420  1.90   40            765            32.640  3.67
1048 12.17 0.860 0.460  4.80   40            712            34.200  3.72
     MnkDap1M VolRatioS1 ... SMILESsnamep1M_PTBDTffDTBT.1
317  24.0     0.97       ... 0
318  72.9     0.97       ... 0
319  40.0     0.97       ... 0
320  48.0     0.97       ... 0
479  68.5     1.00       ... 0
480  68.5     1.00       ... 0
481  68.5     1.00       ... 0
491  68.5     1.00       ... 0
492  68.5     1.00       ... 0
493  68.5     1.00       ... 0
494  68.5     1.00       ... 0
495  10.2     1.00       ... 0
496  18.3     1.00       ... 0
497  22.7     1.00       ... 0
594  18.3     1.00       ... 0
595  16.8     1.00       ... 0
596  15.9     1.00       ... 0
597  14.6     1.00       ... 0
598  16.1     1.00       ... 0
599  16.7     1.00       ... 0
600  15.9     1.00       ... 0
601  14.6     1.00       ... 0
602  16.1     1.00       ... 0
603  30.1     1.00       ... 0
604  16.7     1.00       ... 0
605  70.0     1.00       ... 0
728  41.3     1.00       ... 0
729  16.7     1.00       ... 0
730   3.4     1.00       ... 0
731  41.3     1.00       ... 0
...  ...      ...            ...
761  17.0     1          ... 0
762  18.0     1          ... 0
763  18.0     1          ... 0
764  17.0     1          ... 0
765  17.0     1          ... 0
766  17.0     1          ... 0
767  18.0     1          ... 0
768  18.0     1          ... 0
769  18.0     1          ... 0
877  21.8     1          ... 0
878  21.8     1          ... 0
879  34.0     1          ... 0
880  34.0     1          ... 0
883  21.8     1          ... 0
884  21.8     1          ... 0
885  34.0     1          ... 0
886  34.0     1          ... 0
887  21.8     1          ... 0
888  34.0     1          ... 0
1038 27.5     1          ... 0
1039 22.2     1          ... 0
1040 27.5     1          ... 0
1041 27.5     1          ... 0
1042 27.5     1          ... 0
1043 27.5     1          ... 0
1044 27.5     1          ... 0
1045 27.5     1          ... 0
1046 27.5     1          ... 0
1047 19.2     1          ... 0
1048 18.0     1          ... 1
     Lay6electronodes2_Ag.1 Lay6electronodes2_Al.1 Additivesname_.1
317  1                      0                      1
318  1                      0                      1
319  1                      0                      1
320  1                      0                      1
479  0                      1                      1
480  0                      1                      1
481  0                      1                      1
491  0                      1                      0
492  0                      1                      0
493  0                      1                      0
494  0                      1                      0
495  0                      1                      1
496  0                      1                      1
497  0                      1                      1
594  0                      1                      0
595  0                      1                      0
596  0                      1                      0
597  0                      1                      0
598  0                      1                      0
599  0                      1                      0
600  0                      1                      0
601  0                      1                      0
602  0                      1                      0
603  0                      1                      0
604  0                      1                      0
605  0                      1                      0
728  0                      1                      1
729  0                      1                      1
730  0                      1                      1
731  0                      1                      1
...  ...                    ...                    ...
761  0                      1                      1
762  0                      1                      1
763  0                      1                      1
764  0                      1                      1
765  0                      1                      1
766  0                      1                      1
767  0                      1                      1
768  0                      1                      1
769  0                      1                      1
877  1                      0                      1
878  1                      0                      0
879  1                      0                      1
880  1                      0                      0
883  1                      0                      0
884  1                      0                      0
885  1                      0                      0
886  1                      0                      0
887  1                      0                      0
888  1                      0                      0
1038 0                      1                      1
1039 0                      1                      1
1040 0                      1                      1
1041 0                      1                      1
1042 0                      1                      1
1043 0                      1                      1
1044 0                      1                      0
1045 0                      1                      1
1046 0                      1                      1
1047 0                      1                      1
1048 0                      1                      1
     Additivesname_DIO.1 namessolvent1_CB.1 namessolvent1_CF.1
317  0                   1                  0
318  0                   1                  0
319  0                   1                  0
320  0                   1                  0
479  0                   0                  0
480  0                   0                  0
481  0                   0                  0
491  1                   0                  0
492  1                   0                  0
493  1                   0                  0
494  1                   0                  0
495  0                   0                  0
496  0                   0                  0
497  0                   0                  0
594  1                   0                  0
595  1                   0                  0
596  1                   0                  0
597  1                   0                  0
598  1                   0                  0
599  1                   0                  0
600  1                   0                  0
601  1                   0                  0
602  1                   0                  0
603  1                   1                  0
604  1                   1                  0
605  1                   1                  0
728  0                   0                  0
729  0                   0                  0
730  0                   0                  0
731  0                   0                  0
...  ...                 ...                ...
761  0                   0                  0
762  0                   0                  0
763  0                   0                  0
764  0                   0                  0
765  0                   0                  0
766  0                   0                  0
767  0                   0                  0
768  0                   0                  0
769  0                   0                  0
877  0                   0                  0
878  1                   0                  0
879  0                   0                  0
880  1                   0                  0
883  1                   0                  0
884  1                   0                  0
885  1                   0                  0
886  1                   0                  0
887  1                   0                  0
888  1                   0                  0
1038 0                   0                  0
1039 0                   0                  0
1040 0                   0                  0
1041 0                   0                  0
1042 0                   0                  0
1043 0                   0                  0
1044 1                   0                  0
1045 0                   0                  0
1046 0                   0                  0
1047 0                   0                  1
1048 0                   0                  1
     namessolvent1_oDCB.1 namessolvent2_.1 namessolvent2_oDCB.1
317  0                    0                1
318  0                    0                1
319  0                    0                1
320  0                    0                1
479  1                    1                0
480  1                    1                0
481  1                    1                0
491  1                    1                0
492  1                    1                0
493  1                    1                0
494  1                    1                0
495  1                    1                0
496  1                    1                0
497  1                    1                0
594  1                    1                0
595  1                    1                0
596  1                    1                0
597  1                    1                0
598  1                    1                0
599  1                    1                0
600  1                    1                0
601  1                    1                0
602  1                    1                0
603  0                    1                0
604  0                    1                0
605  0                    1                0
728  1                    1                0
729  1                    1                0
730  1                    1                0
731  1                    1                0
...  ...                  ...              ...
761  1                    1                0
762  1                    1                0
763  1                    1                0
764  1                    1                0
765  1                    1                0
766  1                    1                0
767  1                    1                0
768  1                    1                0
769  1                    1                0
877  1                    1                0
878  1                    1                0
879  1                    1                0
880  1                    1                0
883  1                    1                0
884  1                    1                0
885  1                    1                0
886  1                    1                0
887  1                    1                0
888  1                    1                0
1038 1                    1                0
1039 1                    1                0
1040 1                    1                0
1041 1                    1                0
1042 1                    1                0
1043 1                    1                0
1044 1                    1                0
1045 1                    1                0
1046 1                    1                0
1047 0                    1                0
1048 0                    1                0